### ISSUE TITLE
Calculated measures aren't rolled up properly in preagg queries 

### ISSUE THREAD

**Issue by fouwst** [cube-js/cube#1254]
Given the following schema:

![image](https://user-images.githubusercontent.com/49077823/97233906-65ce6580-17a5-11eb-9c76-7b04a9a6251f.png)

Which produces the following preagg:

![image](https://user-images.githubusercontent.com/49077823/97233953-80084380-17a5-11eb-9d36-65c2a5a844ea.png)

Cube should perform a roll up of the calculated field conversions_per_day when the cube is queried *without* a date granularity. Currently, cube sums the calculated field instead of summing the fields it is composed of, which produces the following result:

![image](https://user-images.githubusercontent.com/49077823/97234192-eb521580-17a5-11eb-9dfa-0543178b3063.png)

This is currently addressable by not including the calculated field in the list of preagg measures.

**Comment by paveltiunov** [comment]
@fouwst Hey Sam! Thanks for posting this!

**Comment by jmadan** [comment]
is there any update on this? I am facing the same issue where calculated measure are not being returned properly as part of pre-aggregation queries

**Comment by paveltiunov** [comment]
The workaround is to remove `conversionsPerDay` from the rollup definition. `conversions` and `days` are enough to resolve `conversionsPerDay` measure.

**Comment by paveltiunov** [comment]
Should be fixed in latest version
