### ISSUE TITLE
Join relationship is hard to understand in the docs

### ISSUE THREAD

**Issue by MattGson** [cube-js/cube#1484]
### Problem

The way cubejs handles join relationships is confusing.

The documentation does not seem to make it clear what exactly the join `relationship` parameter is designed to do.

For example, from the [many-to-many docs](https://cube.dev/docs/many-to-many-relationship#top): 

> In the same way the PostTopics table was specifically created to handle this association in DB, we need to create an associative cube PostTopics, and declare the relationships from it to Topics cube and from Posts to PostTopics. Please note, we’re using the hasMany relationship on the PostTopics cube and direction of joins is selected to be Posts -> PostTopics -> Topics

It says `we're using the hasMany relationship... and direction of joins is selected to be...`. This implies that the relationship is not in fact selecting the direction of joins but some other part of the code. 

In the direction-of-joins docs, it describes an example, concluding with `So we should add join to Orders cube`. implying that the cube which holds the `join` clause will be joined first. However, we are working with relational databases, in many cases, we will want the ability to join in both directions so we will add the join to both sides. So how then, do we know/decide what the join will be?

Is it some combination of the `relationship` field and which cube has which `join` clauses defined?

Further more, the relationship field appears to be like the relationship definitions in most ORMs but the documentation again makes me question this. In a normal ORM, I would model the domain. This would allow me to query the data however I want while maintaining domain consistency.

### Example

For example, in the `Posts -> PostTopics -> Topics` many-to-many example:

I may want to count the posts for each topic per month, or count the average number of topics per post per month.

Using the description given: `A Post can cover many Topics, and a Topic could be covered by many Posts.`
And using the definitions of `hasMany`, `belongsTo` and `hasOne` from the docs:
And using the expected row cardinality relationships in a many-to-many relationship, I arrive at:

- Posts `hasMany` PostTopics (1 - N)
- PostTopics `belongsTo` Posts (N - 1)
- PostTopics `belongsTo` Topics (N - 1)
- Topics `hasMany` PostTopics (1 - N)

However, the docs in fact state:

- Posts `belongsTo` PostTopics (N - 1 ??)
- PostTopics `hasMany ` Topics (1 - N)

This implies (among other things) that each joining row in PostTopics can relate to many rows in Posts. This would only be
possible if many posts had the same key which makes no sense in the domain.

### Solution

Instead of describing two examples why join direction is important (which should be obvious), the direction-of-joins docs should ideally, describe in detail how each part of the schema contributes to the direction of joins. 

The joins documentation should describe what the effect of the `relationships` field is and how it is used. Ideally, for any given schema, there would only be one correct way to specify this field (as is the case in most ORMs) or else it risks being misleading due to the similarity with other ORM libraries.

**Comment by hassankhan** [comment]
Related: https://github.com/cube-js/cube.js/issues/438
