### ISSUE TITLE
`meta` property on cube definition

### ISSUE THREAD

**Issue by TheSPD** [cube-js/cube#1539]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The way we can add `meta` on each dimension or measure, we should be able to add a `meta` on the cubes themselves.

**Describe alternatives you've considered**
Having the meta JSON in the `description` as string

**Additional context**
Would be a great addition for extensibility.

**Comment by igorlukanin** [comment]
Now you can use `meta` on cubes and views:
- https://cube.dev/docs/reference/data-model/cube#meta
- https://cube.dev/docs/reference/data-model/view#meta
