### ISSUE TITLE
Improve Serverless refresh documentation

### ISSUE THREAD

**Issue by magno32** [cube-js/cube#1584]
Per a discussion with @hassankhan, I feel like the documentation for the entire `/run-scheduled-refresh` process is lacking for serverless deployments.

Since Lambda cost is a factor, the current instructions to just keep calling refresh are lacking.  How often should I call it?  What will are response look like when its done?

We are also missing the expected responses that are returned from calling `/run-scheduled-refresh`.

**Comment by hassankhan** [comment]
Hi @magno32  :wave:

Serverless deployments are [deprecated as of Cube v0.31.64](https://github.com/cube-js/cube/blob/master/DEPRECATION.md#serverless-deployments) and we strongly recommend that you migrate to [Docker-based
deployments](https://cube.dev/docs/deployment/platforms/docker). In newer versions of Cube, you can run Refresh Workers to keep pre-aggregations up-to-date.
