### ISSUE TITLE
Boolean filter throws error

### ISSUE THREAD

**Issue by pierre-b** [cube-js/cube#1723]
Hello guys,

Requesting the following filter throws: 
`Invalid query format: child "filters" fails because ["filters" at position 0 does not match any of the allowed types]`

Filter: 
```
{
  "member:" "MyCube.myBooleanDimension",
  "operator": "equals",
  "values": [true]
}
```

Found a workaround to use `'1' `and `'0' ` as values but it took me time to guess where was the issue from!

**Expected behavior**
Booleans in filters should work :)

**Version:**
[0.25.3]

Thanks guys!

**Comment by Saravananalytics** [comment]
Whenever i am edit my cubejs schema file in projectfolder/project.js  and generate it but it will generated default schema file 
i cant change the column value count in cubejs

how to generate edited file into build

**Comment by nandorcsupor** [comment]
Any update on this issue ?

**Comment by vsjoshtait** [comment]
The [documentation](https://cube.dev/docs/query-format#filters-operators-equals) mentions that the `equals` operator only supports `string`, `number` and `time`. Surely it should accept `boolean` as well?

Just adding that mapping to `'1'` or `'0'` works too.

**Comment by kd7lxl** [comment]
I'm confused how this can be marked completed when 818ffbd is not in master. Is it scheduled for future release?
