### ISSUE TITLE
Error: Windows logins are not supported in this version of SQL Server... on Azure SQL Db

### ISSUE THREAD

**Issue by ntxinh** [cube-js/cube#1742]
**Describe the bug**
Windows logins are not supported in this version of SQL Server... error appears when using Azure SQL Database

**Screenshots**
![image](https://user-images.githubusercontent.com/14963070/104078630-b22c2c00-5251-11eb-8465-72cb1e06b416.png)

**Version:**
0.25.13

**Solution**
Adding the `driverFactory` configuration option to cube.js configuration file:

```js
const MSSqlDriver = require('@cubejs-backend/mssql-driver')
module.exports = {
  driverFactory: ({ dataSource }) =>
    new MSSqlDriver({
        authentication: {
            type: 'default'
        },
    }),
};
```

Thank @hassankhan for the solution

**Comment by nguyentrucxinh** [comment]
Sorry to bother you again @hassankhan ,
I created another cubejs project with the serverless template. It doesn't have `cube.js` config file. It has `index.js` file
I updated this file like this, but it's not working
Can you take the time to look at it?
Thank you

```js
const GoogleHandlers = require("@cubejs-backend/serverless-google");
const MSSqlDriver = require("@cubejs-backend/mssql-driver");
module.exports = new GoogleHandlers({
  externalDbType: 'mssql',
  externalDriverFactory: () =>
    new MSSqlDriver({
      authentication: {
        type: "default",
      },
      host: process.env.CUBEJS_EXT_DB_HOST,
      database: process.env.CUBEJS_EXT_DB_NAME,
      port: process.env.CUBEJS_EXT_DB_PORT,
      user: process.env.CUBEJS_EXT_DB_USER,
      password: process.env.CUBEJS_EXT_DB_PASS,
    }),
});
```

**Comment by ovr** [comment]
Hello @nguyentrucxinh,

I am not able to reproduce it, I am using credentials. Can you point my attention to any link with guide that can help me to reproduce this issue?

> I created another CubeJS project with the serverless template. It doesn't have cube.js config file. It has index.js file
I updated this file like this, but it's not working

Serverless still didn't support cube.js configuration.

Thanks

**Comment by ovr** [comment]
@nguyentrucxinh  

Can you try with passing:

```
options: {
   trustedConnection: true,
}
```

refs https://github.com/tediousjs/node-mssql/blob/5923bba2d19bebccf99a72f71996428057d84adc/README.md#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server

Does it resolve the issue?

Thanks

**Comment by florian-fischer-swarm** [comment]
For me, just *not* setting CUBEJS_DB_DOMAIN fixes this problem (which sort of makes sense and is in line with switching to plain authentication manually)

**Comment by hassankhan** [comment]
Hi @nguyentrucxinh :wave:

Were you able to get this working using either @ovr's or @florian-fischer-swarm's suggestions?
