### ISSUE TITLE
Redshift: numeric values returning as strings

### ISSUE THREAD

**Issue by ssealock** [cube-js/cube#1849]
**Describe the bug**
API Project was using MSSQL and needed to convert to AWS Redshift. Connection settings successful and results returned.  Main issue is that all expected numeric values are converted to strings.

Example Query:

```
customerUniqueCount: {
      sql: `customer_uuid`,
      type: `countDistinct`
    },
```

In development => with redshift, its returning as a string

```
“data”: [
        {
            “vSegmentPurchase.customerUniqueCount”: “11193527”
        }
    ],
```

In production => using mssql DB and returns as expected
```
    "data": [
        {
            "vSegmentPurchase.customerUniqueCount": 11196629
        }
    ],
```

**Expected behavior**
All type numbers and aggregations/distinctCount's, etc return numbers

**Screenshots**

**Version:**
```
    "@cubejs-backend/postgres-driver": "^0.25.22",
    "@cubejs-backend/server-core": "^0.25.22",
```

**Additional context**

Problem response with its annotations:
```
{
    "query": {
        "measures": [
            "vSegmentPurchase.customerUniqueCount"
        ],
        "timeDimensions": [],
        "order": [],
        "timezone": "UTC",
        "filters": [],
        "dimensions": []
    },
    "data": [
        {
            "vSegmentPurchase.customerUniqueCount": "11193527"
        }
    ],
    "lastRefreshTime": "2021-01-22T14:01:42.979Z",
    "refreshKeyValues": [
        [
            {
                "floor": 161132407
            }
        ]
    ],
    "usedPreAggregations": {},
    "annotation": {
        "measures": {
            "vSegmentPurchase.customerUniqueCount": {
                "title": "V Segment Purchase Customer Unique Count",
                "shortTitle": "Customer Unique Count",
                "type": "number",
                "drillMembers": [],
                "drillMembersGrouped": {
                    "measures": [],
                    "dimensions": []
                }
            }
        },
        "dimensions": {},
        "segments": {},
        "timeDimensions": {}
    },
    "slowQuery": false
}
```

**Comment by ssealock** [comment]
Checked a few other measures and its happening with them as well. e.g.

`    totalVisits: {
      sql: `count_visits`,
      type: `sum`
    }

Def:
    countVisits: {
      sql: `count_visits`,
      type: `number`
    },
`

Returns this in dev =>
`vConversionsByMarketingChannel.marketingChannel: "Paid Search"
vConversionsByMarketingChannel.source: "Paid Search|product_view"
vConversionsByMarketingChannel.target: "Paid Search|cart_add"
**vConversionsByMarketingChannel.totalVisits: "59976"**
`

Let me know if you need more examples..

**Comment by hassankhan** [comment]
Hi @ssealock  :wave:

I've created a "parent" issue to track this and other similar issues. Thank you for filing the issue 🙌

**Comment by vishwaschoudhary** [comment]
The above mentioned issue is still causing trouble for me so for now i am re-assigning the values that are being returned as string to float using **parseFloat()** . It becomes a bit tedious to reassign the values again and again but that's a simple fix for it.

**Comment by igorlukanin** [comment]
Everyone, please see this comment: https://github.com/cube-js/cube/issues/1879#issuecomment-1954067499
