### ISSUE TITLE
AWS Serverless, working but getting "/bin/sh: hostname: command not found"

### ISSUE THREAD

**Issue by hobojoe** [cube-js/cube#1998]
**Problem**

Hi, my Cubejs is working fine on AWS Lambda, but on both functions (cubejs and cubejsProcess) I keep getting this logged onto Cloudwatch:
`/bin/sh: hostname: command not found`

I found some topics here and on stackoverflow stating that it is usually related to internet access or Redis conectivity. I double-checked and I have internet access enabled on the VPC and access to Redis (keys are being stored there by Cubejs).

What could be causing that error?

Other than that, I am trying to enable logs (so they go to cloudwatch) without success. I add this to my index.js file:
```
module.exports = {
    logger: (msg, params) => {
        console.log(`${msg}: ${JSON.stringify(params)}`);
    },
};
```
By doing this, the API stops functioning, I get "CORS error" on Chrome Dev tools (network tab) and on cloudwatch:
```
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.api is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.api is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
Not sure if I'm doing anything wrong... I seems that every config I try to add to index.js messes up with CubeJs deployment.

I don't know if it could be related to the hostname error I keep getting...

Here are the packages I'm using:
```
"@cubejs-backend/mysql-driver": "^0.25.30",
"@cubejs-backend/server": "^0.26.4",
"@cubejs-backend/serverless": "^0.26.4",
"@cubejs-backend/serverless-aws": "^0.26.4"
```

Thanks!

**Comment by ovr** [comment]
> Other than that, I am trying to enable logs (so they go to cloudwatch) without success. I add this to my index.js file:

`index.js` is the entrypoint file for lambda env that must expose handler, not a configuration object.

For now it's not possible to use a `cube.js` configuration file, but I've prepared a PR for that - https://github.com/cube-js/cube.js/pull/2003

**Comment by hobojoe** [comment]
@ovr , as for the `/bin/sh: hostname: command not found` error, has it been fixed?

Just got the latest version and I still see that message on the logs.

Here is the versions I have:
```
"dependencies": {
    "@cubejs-backend/mysql-driver": "^0.25.30",
    "@cubejs-backend/server": "^0.26.11",
    "@cubejs-backend/serverless": "^0.26.11",
    "@cubejs-backend/serverless-aws": "^0.26.11"
  },
```

Thanks

**Comment by hassankhan** [comment]
Hi all :wave:

Serverless deployments are [deprecated as of Cube v0.31.64](https://github.com/cube-js/cube/blob/master/DEPRECATION.md#serverless-deployments) and we strongly recommend that you migrate to [Docker-based
deployments](https://cube.dev/docs/deployment/platforms/docker).
