### ISSUE TITLE
SECURITY_CONTEXT filter options

### ISSUE THREAD

**Issue by hobojoe** [cube-js/cube#2070]
I would like to know if there are any other options to apply filters using SECURITY_CONTEXT.

On the docs where have this example:

```
cube(`Orders`, {
  sql: `SELECT * FROM public.orders WHERE ${SECURITY_CONTEXT.user_id.filter(
    'user_id'
  )}`,
```

Do we have other options like contains? Or even a way to add multiple parameters?

Thanks!

**Comment by vasilev-alex** [comment]
hi @hobojoe! There're no other options at the moment. Could you tell us more about your use case?

**Comment by LeeJiaLe** [comment]
For example, possible to add multiple id while define jwt token?
`
jwt.sign(
  {
    user_id: [1, 2, 3],
  },
  CUBEJS_API_SECRET,
  {
    expiresIn: '1d',
  },
),
`

**Comment by hobojoe** [comment]
> hi @hobojoe! There're no other options at the moment. Could you tell us more about your use case?

Hello @vasilev-alex , sorry for the late response.

I would like to create some filters like this:
```
WHERE ${SECURITY_CONTEXT.user_id.filter(
    'user_id'
  )}
AND
${SECURITY_CONTEXT.access_role.filter(
    'ADMIN'
  )}
```

Idealy It would be nice to be able to be able to write the query more freely:
```
`SELECT * FROM public.orders WHERE user_id = ${SECURITY_CONTEXT.user_id} AND (${SECURITY_CONTEXT.access_role} = 'ADMIN' OR ${SECURITY_CONTEXT.access_role} = 'MASTER') ;
```

**Comment by hobojoe** [comment]
@vasilev-alex any plans on this being implemented?

**Comment by igorlukanin** [comment]
`queryRewrite` option should be used for this: https://cube.dev/docs/reference/configuration/config#queryrewrite

Please also see the access control recipes for specific examples: https://cube.dev/docs/guides/recipes/overview#access-control
