### ISSUE TITLE
React Dashboard: an Ultimate Guide: Unhandled Rejection (Error): GraphQL error: Variable 'input' has coerced Null value for NonNull type 'ID!'

### ISSUE THREAD

**Issue by m987987** [cube-js/cube#2096]
**Describe the bug**
When starting the dashboard-app, after following the react dashboard ultimate guide, an error appears soon after being shown the actual dashboard containing charts.

**To Reproduce**
1. Begin this guide https://react-dashboard.cube.dev/
2. At the end of part two: "Authentication and GraphQL API" when starting the dashboard-app, everything appears fine for 2-3 seconds. Then the app crashes with the error: 
Unhandled Rejection (Error): GraphQL error: Variable 'input' has coerced Null value for NonNull type 'ID!'

**Expected behavior**
Show the dashboard, and do not crash. Instead of showing a perfect dashboard and soon after crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/79052149/107888024-74828900-6f0a-11eb-8fba-e19f8c74c6a9.png)
![image](https://user-images.githubusercontent.com/79052149/107888031-7f3d1e00-6f0a-11eb-8977-e4071e8f9f30.png)

**Comment by paveltiunov** [comment]
I believe it's the same cause as in #2102. Let's use unique names for local storage of dashboard apps. cc @vasilev-alex

**Comment by igorlukanin** [comment]
The option to generate a dashboard application has been removed from Cube long time ago. So, I guess this makes this question irrelevant now.
