### ISSUE TITLE
Context schema object

### ISSUE THREAD

**Issue by JoshMentzer** [cube-js/cube#2145]
I see in the documentation that there is a context('') object where you can group together Cubes, etc.  It doesn't appear that this information comes back on meta() calls - or is exposed anywhere that I've seen.
Is this implemented and I'm just unable to find, or is this something for future implementation?

**Comment by keydunov** [comment]
Hi @JoshMentzer ,

Thank you for posting this issue.

It's not yet implemented but it is on our roadmap. We're collecting use cases now to make sure the future implementation will cover all of them.

**Comment by JoshMentzer** [comment]
> Hi @JoshMentzer,
> 
> Thank you for posting this issue.
> 
> It's not yet implemented but it is on our roadmap. We're collecting use cases now to make sure the future implementation will cover all of them.

Great, thanks!  In terms of use cases, ours is pretty simple.  We have our own internal dashboard/query building app, and once you start getting a decent number of cubes, the sheer number of measures and dimensions to choose from begins to get a bit overwhelming, especially for new users.  The idea of the context would be for folks to choose a context they want to query within and then only be presented with the measures, dimensions, etc, associated to that context.
If the meta call at a minimum returned the context a cube was a part of, that would be enough for us meet our need.

**Comment by SteffeyDev** [comment]
I have the same use case as @JoshMentzer

**Comment by econtentmaps** [comment]
Our use case is the same as @JoshMentzer, except that we would like to choose what context(s) a user has available to them using claims (specifically cognito group membership). Every user is a member of one at least one group, and that group should have access to one or more tables via a collection of cubes (i.e. context).

**Comment by mhd-adam** [comment]
Thanks, my use case is I have internal and external user groups using the same cube instance and I need to hide sensitive measures from the external users.

**Comment by yuriploc** [comment]
> Thanks, my use case is I have internal and external user groups using the same cube instance and I need to hide sensitive measures from the external users.

Same here. We also have users with location-based access.

**Comment by igorlukanin** [comment]
Hey everyone! Recently, we've consistently introduced `public` options for cubes/views/measures/dimensions that can be set programmatically based on the security context. So, you can make sure that subsets of cubes or views are visible to specific users only.

Read more: https://cube.dev/blog/cube-core-v0-33-data-modeling-update#unified-visibility-control
