### ISSUE TITLE
Athena driver attempts to use OFFSET clause despite not being supported

### ISSUE THREAD

**Issue by yatesdev** [cube-js/cube#2214]
**Describe the bug**
When attempting to use a CubeJs Query that contains a defined offset, cubejs returns the error from the Athena:
```
Error: line 1:1459: mismatched input 'OFFSET' expecting {<EOF>, ',', 'LIMIT', 'NULLS'}
```
This is due to the SQL being generated by cubejs including OFFSET. Which is unsupported by the current versions of Athena.

**To Reproduce**
1. Make a query that contains an offset.
2. See that no results are returned and an error message is displayed.

**Expected behavior**
Query returns as normal, but with an offset being applied to the returned rows.

**Screenshots**

**Version:**
`"@cubejs-backend/athena-driver": "0.24.3"`
`"@cubejs-backend/server": "0.24.3"`

**Additional context**
[SO topic on Athena Offset Support](https://stackoverflow.com/questions/51298622/aws-athena-presto-offset-support)
[AWS Docs showing Athena Engine to Presto version](https://docs.aws.amazon.com/athena/latest/ug/presto-functions.html)

Generated SQL in one of my test queries:
```
SELECT \"finance_daily__tw_partner_id\" \"finance_daily__tw_partner_id\", \"finance_daily__report_date_day\" \"finance_daily__report_date_day\", sum(\"finance_daily__total_revenue\") \"finance_daily__total_revenue\" FROM stb_pre_aggregations_qa.finance_daily_by_d  WHERE (\"finance_daily__tw_company_id\" = ?) AND (\"finance_daily__report_date_day\" >= CAST(date_add('minute', timezone_minute(from_iso8601_timestamp(?) AT TIME ZONE 'UTC'), date_add('hour', timezone_hour(from_iso8601_timestamp(?) AT TIME ZONE 'UTC'), from_iso8601_timestamp(?) AT TIME ZONE 'UTC')) AS TIMESTAMP) AND \"finance_daily__report_date_day\" <= CAST(date_add('minute', timezone_minute(from_iso8601_timestamp(?) AT TIME ZONE 'UTC'), date_add('hour', timezone_hour(from_iso8601_timestamp(?) AT TIME ZONE 'UTC'), from_iso8601_timestamp(?) AT TIME ZONE 'UTC')) AS TIMESTAMP)) GROUP BY 1, 2 ORDER BY 2 ASC OFFSET 50 LIMIT 100
```

**Comment by paveltiunov** [comment]
@yatesdev Hey Mike! Thanks for posting this! Interesting. I believe the only viable way is to use pre-aggregations here. Do you see any other workarounds here?

**Comment by yatesdev** [comment]
@paveltiunov I'm not sure preaggregations would be helpful in this scenario unless I'm misunderstanding.

Any query that returns more than the row limit of 50k defined by Cube would run into this issue, preaggregation or not. There would be no way to get the full data set. Unless you take your time dimension, get the last date that was returned, and reissue the same query with an updated filter until the full set is returned.

Based on the SO answer [here](https://stackoverflow.com/a/51322227) we might be able to wrap the query with a subquery to add `row_number`

```
SELECT * FROM (
    SELECT row_number() over() AS rn, * FROM elb_logs)
WHERE rn BETWEEN 5 AND 10;
```

Which I think would mean creating an AthenaQuery class that extends BaseQuery and overrides the
fullKeyQueryAggregate and groupByDimensionLimit
Specifically to alter the functionality of  this line:
https://github.com/cube-js/cube.js/blob/6a21aa5a2e2323ab10cdae73a4f1b3450e4be74f/packages/cubejs-schema-compiler/src/adapter/BaseQuery.js#L579

**Comment by paveltiunov** [comment]
@yatesdev I mean external pre-aggregations. If you have the query of interest persisted as an external pre-aggregation you can offset and limit it however you want. We're going to support this case in Cube Store. And it should be considered best practice here as per the link you provided https://stackoverflow.com/questions/45114202/offset-on-aws-athena/45114359#45114359. 

As for Athena workaround row_number seems a way to go. It'll require some refactoring in BaseQuery though.

**Comment by paveltiunov** [comment]
`OFFSET` should be supported by Athena right now
