### ISSUE TITLE
Playground should have an option to set the query timezone

### ISSUE THREAD

**Issue by bryceredd** [cube-js/cube#2244]
**Is your feature request related to a problem? Please describe.**
There's no great way to slice data by day and have understandable results if the context is always in UTC.

**Describe the solution you'd like**
A dropdown with a list of timezones would be nice.

**Describe alternatives you've considered**
If there were a way to modify the raw query in playground that would work as well.

**Comment by igorlukanin** [comment]
Since Cube v0.36.x, setting the time zone is now supported in Cube Core as well. Please see the "Options" drop-down: https://cube.dev/docs/product/workspace/playground#composing-queries
