### ISSUE TITLE
Rollup tables on external MySQL keeps failing trying to create the same table again

### ISSUE THREAD

**Issue by vkruoso** [cube-js/cube#2316]
**Describe the bug**
Using rollup tables with external MySQL generates errors when creating pre aggregation tables. 

For instance:

`
Error: Error during create table: CREATE TABLE pre_aggregations.cdr_cdr_rollup_sjepphkd_rn2fq4zo_1g4dpkl ('cdr__asterisk_id' int, 'cdr__disposition' varchar(255) CHARACTER SET utf8mb4, 'cdr__extension' varchar(255) CHARACTER SET utf8mb4, 'cdr__sequence' int, 'cdr__start' timestamp, 'cdr__uniqueid' varchar(255) CHARACTER SET utf8mb4, 'cdr__start_day' timestamp, 'cdr__billmin' decimal(38,10), 'cdr__billsec' decimal(38,10), 'cdr__count' int): ER_TABLE_EXISTS_ERROR: Table 'cdr_cdr_rollup_sjepphkd_rn2fq4zo_1g4dpkl' already exists
`

This happens even to the first call to the API after a full restart and database cleanup.

**Expected behavior**
The query works sometimes, but the error persists if it is triggered. Cleaning up the database and restarting the server causes it to work, but not always. It would be expected that the as the table is already created, it would detect it and not generate the error.

**Version:**
"@cubejs-backend/mysql-driver": "0.26.45",
"@cubejs-backend/server": "0.26.52"

**Comment by kevinleeTCA** [comment]
This issue still exists in version 34. 
```
error: Orchestrator error {"duration":294,"error":"Error: Error during create table: CREATE TABLE dev_pre_aggregations.p_m__teams_p_m_teams_rollup_mgcnktaq_xztohjkr_1jb5je3 (\"p_m__teams__legal_entity_id\" uuid, \"p_m__teams__management_ailorn\" text, \"p_m__teams__management_end_date\" date, \"p_m__teams__management_id\" text, \"p_m__teams__management_start_date\" date, \"p_m__teams__organisation_id\" uuid, \"p_m__teams__property_address\" text, \"p_m__teams__property_type\" text, \"p_m__teams__team_id\" text, \"p_m__teams__team_name\" text): relation \"p_m__teams_p_m_teams_rollup_mgcnktaq_xztohjkr_1jb5je3\" already exists","query":{"dimensions":["GeneralLedger_RentByTenancy.rentAmount","GeneralLedger_RentByTenancy.firstRentCreatedAt","GeneralLedger_RentByTenancy.lastRentCreatedAt","PM_Teams.propertyAddress","PM_Teams.propertyType","PM_Teams.teamId","PaymentMethod.methodType","Tenancies.renterNames","Tenancies.managementId"],"filters":[{"or":[{"member":"PaymentMethod.methodType","operator":"equals","values":["ailo_trust","bank_account","bond","centrepay","credit_card","deposit_to_ledger","tenancy_deposit","tenancy_wallet","offline_payment_account","no_rent_received","other"]},{"member":"PaymentMethod.methodType","operator":"notSet"}]},{"member":"PM_Teams.teamId","operator":"equals","values":["fe35a136-705c-4ffe-b984-2012067ae850","7c502a98-c985-4001-bd18-40082de79ba2","805b2b94-fad1-4b6b-a327-18163b95b217","59c26f7f-cf02-4425-9954-274e5cdba2f6","e8860bd39a55dbb4686dfd621a33bee0"]},{"member":"PM_Teams.organisationId","operator":"equals","values":["d5d264ae-40a4-4ddc-94c6-466406edf9cd"]},
```

We also encounter similar error when cube API query does not work properly with:
```
:"Error: relation \"dev_pre_aggregations.p_m__teams_p_m_teams_rollup_2tjsjx21_0rai2lro_1jb39ls\" does not exist",
```
For the latter one, It is very annoying that we have to disable `CUBEJS_DROP_PRE_AGG_WITHOUT_TOUCH` to prevent the cache being dropped, thus stop such errors, but disable this ENV VAR is causing other issues, i.e., the cube query is querying the deprecated cache sometimes, causing data inconsistency

**Comment by igorlukanin** [comment]
Closing this one as stale. We can continue the conversation in #8546.
