### ISSUE TITLE
How to configure redis TLS certificate

### ISSUE THREAD

**Issue by uulwake** [cube-js/cube#2337]
**Describe the bug**
I want to connect to Redis Memory store in GCP and got the following error:
```
Error: Redis connection to <port> failed - unable to verify the first certificate at TLSSocket.onConnectSecure
(_tls_wrap.js:1502:34) at TLSSocket.emit (events.js:314:20) at TLSSocket._finishInit (_tls_wrap.js:937:8) at
TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) 
```

**To Reproduce**
1. Create redis memory store instance with auth and TLS enabled
2. Create cloud run instance in the same region with redis memory store
3. set `REDIS_URL=rediss://<ip-address>:<port>`
4. set `REDIS_PASSWORD=<redis-auth>`
5. set `REDIS_TLS=true`

**Expected behavior**
Cubejs and redis should connect

**Version:**
0.26.45

**Comment by uulwake** [comment]
My current workaround is to encode the CA certificate to base64 and store the value in the environment variable with name `REDIS_TLS_CERT`.
```
base64 <your .pem file>
```

In `cube.js`, I use `redisPoolOptions` to create redis TLS connection.
```js
const { createRedisClient } = require('@cubejs-backend/query-orchestrator');

module.exports = {
  orchestratorOptions: {
    redisPoolOptions: {
      createClient: () => {
        const { REDIS_URL, REDIS_TLS_CERT } = process.env;
        const ca = Buffer.from(REDIS_TLS_CERT, 'base64').toString('ascii');
        const checkServerIdentity = () => null;

        return createRedisClient(REDIS_URL, {
          tls: { ca, checkServerIdentity },
        });
      },
    },
  },
}
```

**Comment by ovr** [comment]
It's not supported to set SSL configuration for Redis driver by env variables/configuration.

Related to env variables, there is a code that already solves a similar problem (but for database drivers):

https://github.com/cube-js/cube.js/blob/v0.26.62/packages/cubejs-query-orchestrator/src/driver/BaseDriver.js#L96

Supporting SSL configuration by env variables can be done in a similar way.

**Comment by rpaik** [comment]
👋 a quick reminder that we will be replacing Redis with Cube Store as announced in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).
