### ISSUE TITLE
cubejs-api/v1/run-scheduled-refresh cube parameter

### ISSUE THREAD

**Issue by javiramos1** [cube-js/cube#2401]
**Is your feature request related to a problem? Please describe.**
Currently, /run-scheduled-refresh refresh all the pre aggregations, it would be great if we can pass a parameter with the cube name to only refresh the given queue.

**Describe the solution you'd like**
Add a parameter to the api to pass the cube name or the table name.

**Describe alternatives you've considered**
The only current alternative is to refresh everything.

**Additional context**
We would like to display the last refresh time in the UI and have the option to trigger a refresh from the UI. The /run-scheduled-refresh is a good option but we need a more fine grain solution.

Thanks!

**Comment by paveltiunov** [comment]
@javiramos1 Hey Javier! Thanks for posting this! We indeed considering adding support for specific cube/groups refresh however mostly for load distribution purposes. I'm curious what's your use case?

**Comment by javiramos1** [comment]
> @javiramos1 Hey Javier! Thanks for posting this! We indeed considering adding support for specific cube/groups refresh however mostly for load distribution purposes. I'm curious what's your use case?

Our use case is the following:
We want to cache the results because the queries are expensive and the data does not change that often.
Most of the times refreshing every hour or more is okay.
However, if someone is testing something, specially when building a dashboard or before a presentation, waiting 1 hour to see the result is not acceptable, for these cases we want a way to override from the UI the refresh time and trigger a refresh.

**Comment by paveltiunov** [comment]
@javiramos1 Do you mean to see the reflection of schema changes instantly due to development?

**Comment by javiramos1** [comment]
Hi Pavel,

No, we just want to trigger a refresh based on a request from UI. So, currently you can refresh an aggregation based on a sql statement or a schedule. I'm looking for a way to trigger a manual refresh from the API.

**Comment by paveltiunov** [comment]
@javiramos1 Is it to warm up just changed pre-aggregations?

**Comment by javiramos1** [comment]
Yes

**Comment by paveltiunov** [comment]
@javiramos1 It should be done using a separate warmup process which warmups pre-aggregations before deploying a new version of schema to be served by API instances. It's how it works in Cube Cloud. You can see it on this diagram: https://cube.dev/cloud/.

**Comment by gcassarini** [comment]
Hi @paveltiunov 
We have the same need but with a slightly different use case.

We have a lot of cubes based on many tables that are refreshed by different background process in production.
All these processes runs with different scheduled time and what we would like to achieve is to have the possibility to trigger the refresh of the pre-aggregations of a specific cube right after the background job completes its computations.

With the current rest api I would obtain to trigger all the pre-aggregations refreshes every time any of the background job completes. I know that I can introduce something like `select max(date) from ...` as refreshKey but please consider that we use prestodb as datasource, so also these "simple checks" are quite heavy.

This said, this feature will be super useful for our use case. Do you think it would be possible to introduce it?

**Comment by javiramos1** [comment]
Yes, for us is also really useful. We want to keep things in the cache as long as we can but still give the options to certain users to force a refresh.

**Comment by paveltiunov** [comment]
@gcassarini You can have a separate table where you track the progress of your background refresh processes one row per cube. Once the process has been finished it changes a single row in this table. This way you don't need to scan all the data and this status table can be relatively small. @javiramos1 Pretty the same approach can be used in your case.

I'll convert this issue to the enhancement and let's collect some additional feedback about these manual refresh trigger use cases.

**Comment by igorlukanin** [comment]
[/v1/run-scheduled-refresh REST API endpoint](https://github.com/cube-js/cube/blob/master/DEPRECATION.md#v1run-scheduled-refresh-rest-api-endpoint) has been deprecated for quite some time and it was recently removed from Cube v0.36.0. So, this specific issue is not relevant anymore.

That being said, I'd like to point out that refreshing pre-aggregations for specific cubes is supported by the [Orchestration API](https://cube.dev/docs/product/apis-integrations/orchestration-api). It is definitely recommended to be used for this case.
