### ISSUE TITLE
Add redisPool `numTestsPerEvictionRun` option

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube#2573]
**Is your feature request related to a problem? Please describe.**

redisPool use `node-pool`  npm package. default `numTestsPerEvictionRun=3`  maybe too small if we have many requests

with numTestsPerEvictionRun option we can control how fast  redis connections will be  released. if posible i can  make pr 

some links 

https://github.com/coopernurse/node-pool

**Comment by paveltiunov** [comment]
@rongfengliang Yeah. Makes sense to make it ~200-300. Need to test it thoroughly though. cc @ovr

**Comment by rpaik** [comment]
👋 a quick reminder that we will be replacing Redis with Cube Store as announced in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).

**Comment by igorlukanin** [comment]
I believe that this issue is not relevant anymore since Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
