### ISSUE TITLE
Migrate to AWS JavaScript SDK v3

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube#2618]
**Is your feature request related to a problem? Please describe.**
AWS has released a [newer version of their SDK](https://github.com/aws/aws-sdk-js-v3) which is far more lightweight.

Affected packages:
- [x] https://github.com/cube-js/cube.js/pull/3132
- [ ] `@cubejs-backend/serverless-aws`
- [ ] `@cubejs-backend/mysql-aurora-serverless-driver`

**Describe the solution you'd like**
Use the new SDK.

**Describe alternatives you've considered**
Keeping the v2 SDK probably. Not ideal though.

**Additional context**

```bash
❯ yarn why aws-sdk
yarn why v1.22.10
[1/4] :thinking_face:  Why do we have the module "aws-sdk"...?
[2/4] :truck:  Initialising dependency graph...
[3/4] :mag:  Finding dependency...
[4/4] :aerial_tramway:  Calculating file sizes...
=> Found "aws-sdk@2.889.0"
info Reasons this module exists
   - "_project_#@cubejs-backend#athena-driver" depends on it
   - Hoisted from "_project_#@cubejs-backend#athena-driver#aws-sdk"
   - Hoisted from "_project_#@cubejs-backend#serverless-aws#aws-sdk"
   - Hoisted from "_project_#@cubejs-backend#mysql-aurora-serverless-driver#aws-sdk"
   - Hoisted from "_project_#@cubejs-backend#mysql-aurora-serverless-driver#@types#data-api-client#aws-sdk"
info Disk size without dependencies: "62.36MB"
info Disk size with unique dependencies: "63.63MB"
info Disk size with transitive dependencies: "63.86MB"
info Number of shared dependencies: 12
:sparkles:  Done in 1.75s.
```

**Comment by ganeshmani** [comment]
@hassankhan I would like to work on this issue if it's available :-)

**Comment by igorlukanin** [comment]
Closing this one as the rest of the planned work is obsolete now with the [deprecation of serverless packages](https://cube.dev/blog/cube-core-v0-35-updates-to-data-modeling-and-data-sources#legacy-serverless-packages-removed).
