### ISSUE TITLE
Incorrect http status from `EXECABORT` errors  

### ISSUE THREAD

**Issue by craigbeck** [cube-js/cube#2675]
**Describe the bug**

Client receives a `400` status response (bad request) when performing a normal, valid request, that results in a `EXECABORT` error:
```
{"error":"ReplyError: EXECABORT Transaction discarded because of previous errors."}
```

related stacktraces from server: 
```
ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/cube/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/cube/node_modules/redis-parser/lib/parser.js:302:14)
```

**To Reproduce**
n/a

**Expected behavior**

As this is a server issue, this should respond with a `500` error

**Screenshots**

**Version:**
v0.27.7

**Additional context**
n/a

**Comment by ovr** [comment]
Hello @craigbeck ,

1. Do you use a multi-tenancy setup? If yes, can you provide configuration?
2. Can you try to find an original issue with https://redis.io/commands/MONITOR?

Thanks

**Comment by igorlukanin** [comment]
I believe that this issue is not relevant anymore since Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
