### ISSUE TITLE
Bug on build query with hasMany relationship

### ISSUE THREAD

**Issue by tuandiep1** [cube-js/cube#2861]
**Describe the bug**
I added sum measure to a entity and filter with some condition from the parent entity as a flow and got the error: "must appear in the GROUP BY clause or be used in an aggregate function".
The schemas as below:
InspectionViolationSanction =>(n : 1) => InspectionViolation => (n: 1) => Inspection => (1 : 1) => InspectionIndustry

**To Reproduce**
 
![image](https://user-images.githubusercontent.com/73058946/120214133-424d2b00-c25e-11eb-9253-ba292a7ba1ac.png)

![image](https://user-images.githubusercontent.com/73058946/120214161-4d07c000-c25e-11eb-91b3-d54af3ece648.png)

![image](https://user-images.githubusercontent.com/73058946/120214196-58f38200-c25e-11eb-91ac-6aa4c58ec9b8.png)

![image](https://user-images.githubusercontent.com/73058946/120214220-61e45380-c25e-11eb-9c8c-74bb6c6a74ee.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/73058946/120212900-cacacc00-c25c-11eb-8e83-672fbc6ad8b2.png)
![image](https://user-images.githubusercontent.com/73058946/120213124-0b2a4a00-c25d-11eb-9dc3-8f59adbfe3bd.png)

**Expected behavior**
Query is built in correct sql format and able to get data.

**Version:**
 "@cubejs-backend/mssql-driver": "^0.27.5",
 "@cubejs-backend/server": "^0.27.7"

**Comment by igorlukanin** [comment]
I've tried to reproduce this on Cube v0.36.7 with the following data model and it looks like a correct `GROUP BY` clause is generated. So it looks like this has been fixed.

```yaml
