### ISSUE TITLE
Connect multiple data sources using pre-Aggregation

### ISSUE THREAD

**Issue by smartXJ** [cube-js/cube#2933]
I have three data sources A, B, and C.
A has a farm table.
B has a pig table.
C has a sheep table.
The pig table and the sheep table correspond to each other through the farm and farm table ID fields.

now, I want to get the number of pigs and sheep on the farm in one query.
How to write pre-Aggregation?

**Comment by igorlukanin** [comment]
I believe it should be fairly trivial to implement this.

Links to relevant docs pages:
- Joins: https://cube.dev/docs/product/data-modeling/concepts/working-with-joins
- Pre-aggregations: https://cube.dev/docs/product/caching/using-pre-aggregations

@smartXJ If you still need guidance, please feel free to reopen this issue.
