### ISSUE TITLE
Playground member search doesn't support cyrillic letters 

### ISSUE THREAD

**Issue by Mozzarella123** [cube-js/cube#3238]
![cube-1](https://user-images.githubusercontent.com/22841455/129150258-31aa86fa-4d25-4f8c-8524-6644a126042d.png)
![cube](https://user-images.githubusercontent.com/22841455/129150256-02af0030-a5f7-487f-b0cb-75159ef17754.png)

**Comment by rchkv** [comment]
Hey @Mozzarella123 👋 

I'm afraid that at the moment we only support the English language. We are watching the growth of users from other regions and will add support for other languages, like Cyrillic, Chinese, Japanese, etc, as Cube.js becomes more popular in those regions.

Also, you can try to implement Cyrillic support and send a PR. It would be awesome!

**Comment by igorlukanin** [comment]
It is not recommended to use any non-Latin letters in identifiers: https://cube.dev/docs/product/data-modeling/syntax#naming

With the current version (v0.36.2), Cube explicitly disallows identifiers with Cyrillic letters and emits an error like this:

```
куб cube: (name = куб) with value "куб" fails to match the identifier pattern
```

**Comment by oxoxlol** [comment]
Hi, thanks for your product!
Is the reply from @rchkv still relevant?
What level of interest in this feature must there be for it to be done? How can that interest be measured?

But later @igorlukanin commented that “use is not recommended” - is this the final answer and they will not revise their opinion on this issue?

This feature is as important to me as it is to other authors of similar issues. My team and I want to build a “business layer” where users can query data using terms they are familiar with in their native language. Where business users will access data from bi-tools (create their own dashboards based on semantic data model), so cube “titles” don't solve the problem, we need cube names in native language (similar need for measure and dimension names). Users can create dashboards in both views and cubes.

Does this issue have some deep technical limitations and pitfalls, or is it just not a priority for your team?
Can community PR on this issue be pulled? 

Thanks in advance for your reply!
