### ISSUE TITLE
Cube Store Redis prefix to be used as real prefix

### ISSUE THREAD

**Issue by mfulop** [cube-js/cube#3275]
Configured prefix for cube store is currently used in the middle of redis keys generated by cube store eg.:

SQL_PRE_AGGREGATIONS&lt;prefix&gt;...

This is polluting our redis namespace when we are using tools to browse hierarchical keys.

An option to add the prefix at the beginning of generated Redis keys would be awesome!

**Comment by rpaik** [comment]
👋 a quick reminder that we will be replacing Redis with Cube Store as announced in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).

**Comment by igorlukanin** [comment]
I believe that this issue is not relevant anymore since Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
