### ISSUE TITLE
Pre-aggregations for a rolling-window measure

### ISSUE THREAD

**Issue by atotev** [cube-js/cube#329]
##### Description
I have a cube with an unbounded rolling-window measure. I would like to have pre-aggregation support for this type of measures.

##### Pre-agg
```
preAggregations: {
    myRollup: {
      type: `rollup`,
      measureReferences: [myMeasure],
      timeDimensionReference: eventDate,
      granularity: `day`
    },
```
##### Measure
```
measures: {
    myMeasure: {
      type: `avg`,
      sql: `${value}`,
      rollingWindow: {
        trailing: `unbounded`
      }
    },
```
##### Query
Note: This query should trigger the pre-aggregation, but does not.
```
{
   "measures":[
      "MyCube.myMeasure"
   ],
   "timeDimensions":[
      {
         "dimension":"MyCube.eventDate",
         "granularity":"day",
         "dateRange":"Last%20month"
      }
   ]
}
```

**Comment by paveltiunov** [comment]
@atotev Thanks for posting this!

**Comment by yatesdev** [comment]
@paveltiunov I ran into this issue recently and it became a roadblock for how my team was planning to use Cube.js with a particular cube definition containing rollingWindow. My team and I are interested in helping, but could use some guidance on what would be involved / where to look for doing so.. thanks!

**Comment by manikasharma70** [comment]
Do we have any solution to this problem??
I am facing the same problem.

**Comment by hassankhan** [comment]
Hi all,

Just as an update, this issue is on our roadmap and we hope to have something ready this quarter.

**Comment by levenal** [comment]
What's the current ETA on resolution for this?

**Comment by anilb0stanci** [comment]
I can't create pre-aggregation tables for rollingwindow measure types using cube 0.28.64
Any updates regarding this?

**Comment by wub** [comment]
Hey @hassankhan, was this still on the roadmap? Cheers!

**Comment by paveltiunov** [comment]
Implemented in latest versions.
