### ISSUE TITLE
Support for disabling default route for /, when it's running in production mode

### ISSUE THREAD

**Issue by HarshalNathe** [cube-js/cube#335]
When running Cube.js Backend in production mode by setting `NODE_ENV` as a `production` it sends me the HTML response like `Cube.js server is running in production mode. Learn more about production mode`. when I hit http://localhost:3000/. But I use this URI(route) to display the `index.html` page of my application developed in NODEJS (Express). Because of this when an application gets to run, it shows me CubeJS response, not application page.

**My Findings**
When I debug this I found that in the latest NPM update, `else` condition gets added in `initApp()` method. 
```
async initApp(app) {
    checkEnvForPlaceholders();
    const apiGateway = this.apiGateway();
    apiGateway.initApp(app);
    if (this.options.devServer) {
      this.devServer.initDevEnv(app);
    } else {
      app.get('/', (req, res) => {
        res.status(200)
          .send(`<html><body>Cube.js server is running in production mode. <a href="https://cube.dev/docs/deployment#production-mode">Learn more about production mode</a>.</body></html>`);
      });
    }
  }
```
**PS:** Its working fine up to `"@cubejs-backend/server-core": "^0.10.62"`

**Suggestion**
Can we change that route **OR** can we provide the option to disable this route **OR** can we remove that `else` condition from `initApp()` method.

**Comment by hassankhan** [comment]
Hi @HarshalNathe, perhaps I'm mistaken (and @paveltiunov could clarify) but I was under the impression that the Playground only worked in development mode. Are you trying to get the playground to work in production?

**Comment by HarshalNathe** [comment]
Hi @hassankhan, I don't want to get playground to work in production. Actually I want to route `index.html` page of my application in production, when I hit http://localhost:3000/. But I am seeing the HTML message like `Cube.js server is running in production mode. Learn more about production mode`.

**Comment by paveltiunov** [comment]
Hey @HarshalNathe ! You can override root route by setting it before cube.js init:
```javascript
require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const CubejsServerCore = require('@cubejs-backend/server-core');

const app = express();
app.use(require('cors')());
app.use(bodyParser.json({ limit: '50mb' }));

app.get('/', (req, res) => {
  res.json({ status: 'ok' });
});

const serverCore = CubejsServerCore.create();
serverCore.initApp(app);

const port = process.env.PORT || 4000;
app.listen(port, (err) => {
  if (err) {
    console.error('Fatal error during server start: ');
    console.error(e.stack || e);
  }
  console.log(`🚀 Cube.js server is listening on ${port}`);
});
```

As many of users encountering this problem let's detect if default route was handled somewhere else before handling it.

**Comment by HarshalNathe** [comment]
@paveltiunov I tried it in express its working absolutely fine. But in Loopback we load our application pages using middleware.json file.

**Comment by HarshalNathe** [comment]
@paveltiunov Can we change this **['/']** route in ```initApp()``` method? **OR** can we provide the option to disable this route.

When I removed the ```else``` condition from ```initApp()``` method my Loopback application start to load ```index.html``` file properly.

**Comment by rpeterson** [comment]
I just invested a ton of time into building reports into our internal suite of tools, then found this out when we rolled to testing environment. Not sure if there's a timeline or plan for this, if not, will work on patching and submit a PR as assuming it's the only app on an express route of / is just a bad architecture assumption to make.

**Comment by paveltiunov** [comment]
@rpeterson Hey Ryan! Thanks for the feedback here. We spent some time figuring out our relationship with express and embedding Cube.js in general. What we find out is Cube.js should be scaled very differently rather than other parts of the big express app. Even if small to medium deployments work in this configuration it's a dead-end in terms of devops and infrastructure in long term. Given that we decided to abandon express embedding support and soon we'll ship several major updates to Cube.js which significantly change Cube.js-express relationship. Embedding still be around for some time for backward compatibility however it won't be the recommended way of deployment.

That being said I'm curious to learn more about your use case and your plan in terms of scalability: how many servers do you plan to have, how and where do you plan to deploy, and if you considered running Cube.js as a microservice?

Thanks!

**Comment by rpeterson** [comment]
@paveltiunov - Happy to discuss here what we're working on here, will ping you in slack.

**Comment by ivanaszuber** [comment]
Heya @paveltiunov , I'm also curious about this. We have the same problem with embedding Cubejs into an existing express server. Unfortunately setting the root route before cube.js init doesn't seem to work.
Are there any plans for supporting this in the future? We've already setup everything locally and would really love to use this in production 🙏

**Comment by igorlukanin** [comment]
We've released an official Docker image and encourage developers to migrate from embedding Cube.js into Express to standalone microservices. Read more in blog: https://cube.dev/blog/cubejs-loves-docker/

![cubejs-docker-1 1-2](https://user-images.githubusercontent.com/3852894/100650400-ee1bc980-3354-11eb-9a57-4358603dccd7.png)

**Comment by nikolasj** [comment]
I deployed the cube for prod. I am getting the error `Cube.js server is running in production mode. [Learn more about production mode](https://cube.dev/docs/deployment/production-checklist).`. How to fix it?

**Comment by igorlukanin** [comment]
@nikolasj I believe what you see is more a notification than an actual error. As detailed by the [link provided](https://cube.dev/docs/deployment/production-checklist), in production, the development mode is disabled; so, the [Developer Playground](https://cube.dev/docs/dev-tools/dev-playground) is disabled, too.

If you'd like to see the Developer Playground there, probably you'd need to rethink your use case. Please feel free to join Cube's Slack at https://slack.cube.dev and ask a question about that. We'd be happy to help.

**Comment by nikolasj** [comment]
@igorlukanin 
> As detailed by the [link provided](https://cube.dev/docs/deployment/production-checklist), in production, the development mode is disabled; so, the [Developer Playground](https://cube.dev/docs/dev-tools/dev-playground) is disabled, too.

Sorry. I don't understand. I deployed cube from a helm chart in a production environment `CUBEJS_DEV_MODE=false`. When I try to navigate to the url / I get a message `Cube.js server is running in production mode`. But how do I work with a cube in a production environment?

**Comment by igorlukanin** [comment]
> But how do I work with a cube in a production environment?

In production environment, you are supposed to use one of Cube's APIs to access the data (REST, GraphQL, or SQL).

> Do I need development mode or prod mode to customize charts?

If you'd like to works with charts and customize them, these are best options:
* connect a BI tool or a data notebook to Cube and build/customize charts there; see https://cube.dev/docs/config/downstream; Metabase, Superset, Hex, or Deepnote are all fine options, among others
* create a custom dashboard app (maybe using the Playground) and deploy it separately; then, you'll be able to change it however you want as your front-end skills permit
