### ISSUE TITLE
"last n" timeDimension range short by 1 day for n > 1

### ISSUE THREAD

**Issue by datananda** [cube-js/cube#3451]
**Describe the bug**
Running a "last n months" timeDimension query returns a dateRange that is short by 1 date when n > 1.

**To Reproduce**
1. Queries are tested against a DimDates Cube schema (1 row per date, no missing dates).
2. Run 'last month' query:
```
{
  "dimensions":[
    "DimDates.shortDate"
  ],
  "timeDimensions":[
    {
      "dimension":"DimDates.shortDate",
      "dateRange":"last month",
      "granularity":"month"
    }
  ]
}
```
3. Observe the dateRange in the response as expected:
```
"timeDimensions": [
    {
        "dimension": "DimDates.shortDate",
        "dateRange": [
            "2021-08-01T00:00:00.000",
            "2021-08-31T23:59:59.999"
        ],
        "granularity": "month"
    }
],
```
4. Run 'last 2 months' query:
```
{
  "dimensions":[
    "DimDates.shortDate"
  ],
  "timeDimensions":[
    {
      "dimension":"DimDates.shortDate",
      "dateRange":"last 2 months",
      "granularity":"month"
    }
  ]
}
```
5. Observe the dateRange in the response end date is shorted by 1 day:
```
"timeDimensions": [
    {
        "dimension": "DimDates.shortDate",
        "dateRange": [
            "2021-07-01T00:00:00.000",
            "2021-08-30T23:59:59.999"
        ],
        "granularity": "month"
    }
],
```

**Expected behavior**
Expect the dateRange in the response of 'last 2 months' query to be:
```
"timeDimensions": [
    {
        "dimension": "DimDates.shortDate",
        "dateRange": [
            "2021-07-01T00:00:00.000",
            "2021-08-31T23:59:59.999"
        ],
        "granularity": "month"
    }
],
```

**Screenshots**

**Version:**
"@cubejs-backend/cubestore-driver": "^0.27.2",
"@cubejs-backend/postgres-driver": "^0.27.2",
"@cubejs-backend/server": "^0.27.3",
"@cubejs-backend/serverless": "^0.27.3",
"@cubejs-backend/serverless-aws": "^0.27.3",

**Additional context**

**Comment by JoshMentzer** [comment]
hey @datananda ,
I believe this was fixed in #2824
