### ISSUE TITLE
Time dimension on a runningTotal measure on Snowflake mixes quoted and unquoted columns

### ISSUE THREAD

**Issue by leogodin217** [cube-js/cube#3452]
**Describe the bug**
Using a time dimension on a runningTotal measure on Snowflake mixes quoted and unquoted columns in the query. This fails the query, because Snowflake has specific rules about quoted columns. Specifically:

- All unquoted column names are treated as upper case
- Quoted column names are case sensitive. 

So "date_from" <> date_from

**To Reproduce**
1. Create a runningTotal measure in a cube with Snowflake as the database
2. In the sandbox add that measure and a time dimension
3. Run the chart and see the error
4. Update start and end dates in the query (these are parameterized near the bottom of the query)
5. Run the query on Snowflake
6. See the error: SQL compilation error: error line 52 at position 115 invalid identifier '"OFFERINGS.firstTradeDate_series"."date_to"'

**Expected behavior**
It should not create an error. I would suggest adding the column aliases to "OFFERINGS.firstTradeDate_series" and quote date_to and date_from. When I do that, the query runs fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/180385/133851730-80595f53-c7f4-4e6d-8038-b3b064b82faf.png)

**Version:**
28.32 according to running /usr/local/bin/cubejs --version on the Latest Docker version 

**Additional context**

This is the generated query. Notice that line 2 quotes "date_from", but but when the aliases are created, they are not quoted. In snowflake, this means they are not the same column. 

Also, 
Snowflake requires the column aliases for "OFFERINGS.firstTradeDate_series". I tested this and was surprised. When we add the column type in the select query, the parent subquery does not inherit the column name.  I pasted a simpler query below to show what Snowflake expects. 

```
SELECT
  "OFFERINGS.firstTradeDate_series"."date_from" "o_f_f_e_r_i_n_g_s__first_trade_date_month",
  sum("o_f_f_e_r_i_n_g_s__cumulative_num_offerings") "o_f_f_e_r_i_n_g_s__cumulative_num_offerings"
FROM
  (
    SELECT
      date_from :: timestamp,
      date_to :: timestamp
    FROM
      (
        VALUES
          (
            '2021-07-01T00:00:00.000',
            '2021-07-31T23:59:59.999'
          ),
          (
            '2021-08-01T00:00:00.000',
            '2021-08-31T23:59:59.999'
          ),
          (
            '2021-09-01T00:00:00.000',
            '2021-09-30T23:59:59.999'
          )
      ) AS dates (date_from, date_to)
  ) AS "OFFERINGS.firstTradeDate_series"
  LEFT JOIN (
    SELECT
      date_trunc(
        'MONTH',
        CONVERT_TIMEZONE(
          'UTC',
          "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative___o_f_f_e_r_i_n_g_s"."FIRST_TRADE_DATE" :: timestamp_tz
        ) :: timestamp_ntz
      ) "o_f_f_e_r_i_n_g_s__first_trade_date_month",
      sum(count(*)) "o_f_f_e_r_i_n_g_s__cumulative_num_offerings"
    FROM
      "DATALAB_STG"."OFFERINGS" AS "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative___o_f_f_e_r_i_n_g_s"
    WHERE
      (
        CONVERT_TIMEZONE(
          'UTC',
          "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative___o_f_f_e_r_i_n_g_s"."FIRST_TRADE_DATE" :: timestamp_tz
        ) :: timestamp_ntz >= CONVERT_TIMEZONE('UTC', ? :: timestamp_tz :: timestamp_tz) :: timestamp_ntz
        AND CONVERT_TIMEZONE(
          'UTC',
          "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative___o_f_f_e_r_i_n_g_s"."FIRST_TRADE_DATE" :: timestamp_tz
        ) :: timestamp_ntz <= ? :: timestamp
      )
    GROUP BY
      1
  ) AS "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative__base" ON "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative__base"."o_f_f_e_r_i_n_g_s__first_trade_date_month" >= '2021-07-01T00:00:00.000'
  AND "o_f_f_e_r_i_n_g_s_cumulative_num_offerings_cumulative__base"."o_f_f_e_r_i_n_g_s__first_trade_date_month" <= "OFFERINGS.firstTradeDate_series"."date_to"
GROUP BY
  1
LIMIT
  10000
```

```
select
    letter,
    number
from (
    select
        letter :: varchar,
        number :: int
    from (
        values
            ('a', '1'),
            ('b', '2')
    ) as data(letter, number)
) as data2 (letter, number) -- When column types are specified for letter and number, this is needed
```

**Comment by paveltiunov** [comment]
@leogodin217 Hey Leo! Thanks for posting it! As a workaround, you can use rolling window rollup.

**Comment by leogodin217** [comment]
Rolling window is a good workaround. Unfortunately, I'm more of a Python programmer, so I will not be able to fix this myself.

**Comment by ferreroxc** [comment]
@paveltiunov I would like to work on this issue, do you still need help? I am new to open source and I am excited to find this good-first-issue!

**Comment by igorlukanin** [comment]
Recently, we've deprecated running total measures in favor of the rolling window option: https://cube.dev/blog/cube-core-v0-33-43-duckdb-support-langchain-integration#running_total-deprecation
