### ISSUE TITLE
Compile error on auto generated schema having hyphen (-) in their name

### ISSUE THREAD

**Issue by anuragphadnis** [cube-js/cube#3455]
When I auto generate schmea from any source which is having hyphen in the name, the schema gets generated with same name (includes hyphen) but server gives a compile error stating that `child "name" fails because ["name" with value "something-something" fails to match the identifier pattern]`.

**To Reproduce**
1. Start a mongo server with a collection named test-collection
2. Connect it to cubejs server
3. Create schema from developer playground
4. Restart the server
5. Go to build page

**Expected behavior**
The name of generated schema should be automatically converted to the specifications that cubejs requires ("-" should be replaced with "_")

**Screenshots**
![image](https://user-images.githubusercontent.com/10177121/133991969-9c406839-be9d-4eb4-b776-adcf79af0576.png)

**Comment by paveltiunov** [comment]
Hey @anuragphadnis ! Thanks for posting this! As a workaround, you can fix these identifiers by editing the schema file manually.

**Comment by anuragphadnis** [comment]
I would like to work on it, if you can guide me with the current flow of the feature.

**Comment by anuragphadnis** [comment]
> 
> 
> Hey @anuragphadnis ! Thanks for posting this! As a workaround, you can fix these identifiers by editing the schema file manually.

I would like to work on it, if you can guide me with the current flow of the feature.

**Comment by igorlukanin** [comment]
Looks like https://github.com/cube-js/cube/issues/2614 is really similar to this issue. I've left a comment about it there. Let me then close this one as a duplicate.
