### ISSUE TITLE
feat:(`@cubejs-client/core`) convert numerical measures to `Number` and `BigInt`

### ISSUE THREAD

**Issue by hassankhan** [cube-js/cube#349]
**Is your feature request related to a problem? Please describe.**

Currently CubeJS (mostly) serializes all values as strings. This is obviously very useful for large numbers (since JSON does not support them), however it would be really nice if numerical values were converted back to the `Number` or `BigInt` type after receiving a response from the CubeJS Server.

**Describe the solution you'd like**
`ResultSet#tablePivot()` should look up any numerical measures from the schema and cast values to `Number` or `BigInt`

**Describe alternatives you've considered**
You could manually post-process the results from the result set.

**Additional context**
https://cube-js.slack.com/archives/CC0403RRR/p1579123638123400

**Comment by reify-thomas-smith** [comment]
Currently, it doesn't look like it's possible to specify that a dimension or measure is an integer (versus a floating point number). As a result, it's not clear how `tablePivot()` would choose whether to produce a `Number` or a `BigInt`.

**Comment by igorlukanin** [comment]
This is what `castNumerics` is for: https://cube.dev/blog/cube-core-v0-34-34-python-and-powerful-updates#castnumerics-in-front-end-sdks
