### ISSUE TITLE
cube.js client core with http poll will not running if cube.js api server stop and then recovery

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube#3493]
**Describe the bug**

**To Reproduce**

write one web app with subscribe
insert some datas in db and view change
stop cube.js backend
wait for seconds then restart cube.js backend

**Version:**
[e.g. 0.28.39]

**Comment by paveltiunov** [comment]
Hey @rongfengliang ! Is it HTTP transport subscribe or web socket one? It seems HTTP but just wanted to double check.
