### ISSUE TITLE
Multi-tenancy aware Time Zones

### ISSUE THREAD

**Issue by vincent-benbria** [cube-js/cube#3509]
**Is your feature request related to a problem? Please describe.**
I need to pre-aggregate on each timezone that my clients want reporting on, but I have a diversified group of clients and they are each mostly only interested in their own timezones.

The impact is pretty simple; I have ~500 clients, about 250 are interested in EST, 200 in PST, 5 in BST, 3 in BT (china) and the rest in basically all timezones across Canada/USA. Overall it means that each of my clients need data timezoned to an average of ~1.2 timezones each, but to provide the adequate coverage i need to enable 8 timezones, forcing me to cache 7 times more data than optimal.

**Describe the solution you'd like**
Introduce a per-tenant timezone list, similar to every other multi-tenancy options

**Comment by vincent-benbria** [comment]
Yes, I do realize that there are half-hour timezones and such.

I am asking for the ability to specify which timezones is aggregated PER tenant, so that my Chinese tenant data is not also preaggregated for EST simply because I also have EST tenants.

**Comment by paveltiunov** [comment]
@vincent-benbria I see what you're saying. Yeah. It makes sense to have an option to control it on a per-tenant level. I guess it should be done here: 
https://github.com/cube-js/cube.js/blob/d143d4dda87a9fac4139fdf47f70b3cdc0b0009b/packages/cubejs-server-core/src/core/server.ts#L783

Looking forward for contributions here!
