### ISSUE TITLE
Support filter array of value in cube playground

### ISSUE THREAD

**Issue by thiennhan2310** [cube-js/cube#3588]
Look like cube playground can not demonstrate filter by array of value yet.
For ex:  `id equals 1,2,3`
Do we have plan to support it soon?

**Comment by paveltiunov** [comment]
@thiennhan2310 It's indeed only working for strings as of now. Looking forward for contributions here!

**Comment by igorlukanin** [comment]
Since v0.36.x, the UI to compose queries and add filters has been updated. Please see https://cube.dev/docs/product/workspace/playground#composing-queries

<img width="900" alt="Screenshot 2024-09-30 at 15 49 57" src="https://github.com/user-attachments/assets/5ace059e-c9f6-48f7-b5c2-6f3e85536907">
