### ISSUE TITLE
How can I use Databricks with Cube.js?

### ISSUE THREAD

**Issue by AntonioEduardo1998** [cube-js/cube#3645]
**Problem**
I've already noticed that the Databricks `Simba` driver is compatible even though it wasn't shown in the Cube.js interface, but I can't find a way to use it. I'm trying with Cube.js CLI with `npx cubejs-cli create project name databricks-jdbc` and the installation goes fine but after running npm run dev It asks me for a `.env `parameter called `CUBEJS_DB_DATABRICKS_URL`, so I pass my databricks JDBC URL  and the error stops, but in the interface, it just keeps an eternal load without logs.

**Database**
Databricks

**Connection method**
JDBC

**Comment by paveltiunov** [comment]
Hey @AntonioEduardo1998 ! Databricks driver is a work in progress. We're looking for contributors who'll be to finish it.

**Comment by saggarsunil** [comment]
@paveltiunov Thanks for the update. Is the databricks-jdbc available for use now ?

**Comment by iamvjperumal** [comment]
s the databricks-jdbc available for use now ? @paveltiunov
