### ISSUE TITLE
Clickhouse queries: number filters

### ISSUE THREAD

**Issue by jonathanroze** [cube-js/cube#374]
Hi,

I'm trying to use the lastest version of Cube.JS 0.17.0 with a ClickHouse Database.

It works well but when I want to compare number I have an error 

> error: Error: Illegal types of arguments (UInt32, String) of function greater (version 19.17.3.7 (official build))

And I think it's because of this in Clickhouse driver 

 ```
          } else if (meta.type.includes("Int") || meta.type.includes("Float")) {
              // convert all numbers into strings
              row[field] = `${value}`;
            }
```

So I'd like to know why and if i have a way to bypass this code ? 

Thanks

**Comment by paveltiunov** [comment]
@jonathanroze Hey Jonathan! Thanks for posting this! I believe code you're referring to is about response preparation. I believe it's more about dialect which lacks casts for number filters. For example for BigQuery it's defined here: https://github.com/cube-js/cube.js/blob/2f0179173c24604eba4f5f7cc8fca0804240dc6d/packages/cubejs-schema-compiler/adapter/BigqueryQuery.js#L22

**Comment by jonathanroze** [comment]
Yes you right ! 

And I looked on ClickhouseQuery adapter file and there isn't case for number ! 

I guess in the query it "property" > "0" instead of "property" > 0

**Comment by paveltiunov** [comment]
@jonathanroze Yep. I guess so.

**Comment by jonathanroze** [comment]
Can i custom this file without cloning the entire project ? Like a custom adapter or something like this?

**Comment by paveltiunov** [comment]
@jonathanroze You can monkey patch it. Just require file and override prototype properties. However community can benefit if you can contribute it as a pull request.

**Comment by ralfbecher** [comment]
Having the same issue here but with filter on a dimension (year as number). What would be the solution?

**Comment by paveltiunov** [comment]
Fixed in latest version
