### ISSUE TITLE
Adding session tokens and more flexibility to the AthenaDriver constructor

### ISSUE THREAD

**Issue by lrichomme** [cube-js/cube#3831]
**Is your feature request related to a problem? Please describe.**
I'm doing a project where I must use AWS session tokens and change the s3 output location per query (using driverFactory in the config file). And the current state of the Athena Driver doesn't support session tokens and uses only the env value CUBEJS_AWS_S3_OUTPUT_LOCATION for the output location.

**Describe the solution you'd like**
I would need the driver to take the session token in its credentials and the possibility to set a new s3 ouput location when calling the driver.

**Describe alternatives you've considered**
I don't think there are any alternatives with my problem as I'm not able to use aws credentials without session tokens. And I really need to be able to change the s3 ouput location with each query as I'm accessing different databases with different accounts meaning different sets of s3 buckets.

**Additional context**
I already modified cubejs' AthenaDriver constructor in my local version, and everything works. I also modified every other parameter so they can be set as well when calling the driver in case someone would need to do this later. Also I guessed that adding a new parameter in the config variable would mean setting a new variable in the .env file so I added CUBEJS_AWS_SESSION_TOKEN in it. Here's the modified constructor :
```javascript
constructor(config = {}) {
    super();

    this.config = {
      credentials: {
        accessKeyId: config.accessKeyId || process.env.CUBEJS_AWS_KEY,
        secretAccessKey: config.secretAccessKey || process.env.CUBEJS_AWS_SECRET,
        // Added session token support
        sessionToken: config.sessionToken || process.env.CUBEJS_AWS_SESSION_TOKEN
      },
      // Added the possibility to set region, s3 output location and workgroup values
      region: config.region || process.env.CUBEJS_AWS_REGION,
      S3OutputLocation: config.s3OutputLocation || process.env.CUBEJS_AWS_S3_OUTPUT_LOCATION,
      workGroup: config.workGroup || (process.env.CUBEJS_AWS_ATHENA_WORKGROUP || 'primary'),
      ...config,
      pollTimeout: (config.pollTimeout || getEnv('dbPollTimeout')) * 1000,
      pollMaxInterval: (config.pollMaxInterval || getEnv('dbPollMaxInterval')) * 1000,
    };

    this.athena = new AWS.Athena(this.config);
  }
```
If you're okay with this request I can follow the contributing guide, I'm just not sure how to run tests properly.

**Comment by ivan-vdovin** [comment]
@lrichomme 
Thank you!
Let me add @ovr so he can take a look.

**Comment by lrichomme** [comment]
I would like to work on this issue.

**Comment by RacknerFrank** [comment]
Has there been any movement on this? Need to be able to use cubejs within ECS and have rotating credentials. Need to be able to use a session token
