### ISSUE TITLE
Connecting cubestore to s3 storage failing for af-south-1 region

### ISSUE THREAD

**Issue by andrew-musoke** [cube-js/cube#3848]
**Describe the bug**
Followed [this](https://cube.dev/docs/caching/running-in-production) tutorial to deploy production CubeJS. When running cubestore as docker image and  the `CUBESTORE_S3_REGION` is set to `af-south-1`, the application will fail to start with below DNS error. 

![image](https://user-images.githubusercontent.com/25344830/147354075-5771d793-b3fe-4aed-8ed4-9440be106566.png)

**To Reproduce**
1. Setup s3 bucket and IAM user with appropriate permissions.
2. Set following cubestore environment variables
```
  CUBESTORE_AWS_ACCESS_KEY_ID: "<redacted>"
  CUBESTORE_AWS_SECRET_ACCESS_KEY: "<redacted>"
  CUBESTORE_S3_BUCKET: "cube-store"
  CUBESTORE_S3_REGION: "af-south-1"
  CUBESTORE_S3_SUB_PATH: "subfolder"
```
2. Run Docker image.

**Expected behavior**
Expected the image to start without error

**Version:**
Docker image `cubestore:v0.29.10`

**Additional context**
The problem seems to only present with region `af-south-1`. From what I gathered, Cubejs couldn't formulate a URL in the form `https://cubestore-storage.s3.af-south-1.amazonaws.com` as expected.
I changed the region to `us-east-1` and this behaviour changed and the app started properly.

**Comment by paveltiunov** [comment]
Hey @andrew-musoke ! `af-south-1` isn't indeed on the list of regions https://github.com/durch/rust-s3/blob/75e2eb3dd9acfa5c1add4893ce64569dbac6d4f0/aws-region/src/region.rs#L98. However you can use `s3.af-south-1.amazonaws.com` as `CUBESTORE_S3_REGION` instead.

**Comment by PieterVanZyl-Dev** [comment]
Hey Andrew !
Great to see more adoptions of cube in the African Continent.

Have you tried pavel's suggestion, this bug seems to be in [ rust-s3](https://github.com/durch/rust-s3)

I created a [bug ](https://github.com/durch/rust-s3/issues/245)in rust-s3's repo 

We can probably close this.

**Comment by andrew-musoke** [comment]
Hi @PieterVanZyl-Dev If we are successful with cube in prod, shall definitely start evangelizing it here :)

Just got a chance to try @paveltiunov work around but brings a different error. FYI upgraded to `v0.29.23`. 

![image](https://user-images.githubusercontent.com/25344830/151146791-4e8aa81a-90e4-44a1-9a52-56890315bae6.png)

Thanks for raising the rust issue. Will follow up there.

**Comment by jonasdebeukelaer** [comment]
Bit late to the party, but I notice that in version `0.29.0` of rust-s3, they've added the missing `af-south-1` region. see https://github.com/durch/rust-s3/compare/v0.28.0...v0.29.0

**Comment by ovr** [comment]
It should work starting from https://github.com/cube-js/cube/releases/tag/v0.35.17

Thanks, @jonasdebeukelaer, for your contribution!
