### ISSUE TITLE
Failed to create Vue dashboard app from playground

### ISSUE THREAD

**Issue by openpim** [cube-js/cube#3866]
**Describe the bug**
I was trying to create VUE dashboard app from playground and received an error.
I am using docker version cubejs/cube:latest with CUBEJS_CACHE_AND_QUEUE_DRIVER=memory

**To Reproduce**
1. Start docker image and try to create Vue dashboard app from playground

**Expected behavior**
Dashboard app must be created

**Screenshots**
I have such error at the screen:
Error: npx @vue/cli create -m npm -n -d dashboard-app  failed with exit code 1. Please check your console.
    at ChildProcess.<anonymous> (/cube/node_modules/@cubejs-backend/shared/src/helpers.ts:27:11)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

Plus I have this error in the log
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/509/lib/node_modules/@vue/cli/node_modules/@apollo/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @apollo/protobufjs@1.2.2 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @apollo/protobufjs@1.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-30T12_53_14_066Z-debug.log
Install for [ '@vue/cli@latest' ] failed with code 1
Error: npx @vue/cli create -m npm -n -d dashboard-app  failed with exit code 1. Please check your console.
    at ChildProcess.<anonymous> (/cube/node_modules/@cubejs-backend/shared/src/helpers.ts:27:11)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

**Comment by ivan-vdovin** [comment]
Hi @openpim !
Could you confirm that it is still relevant? We've fixed the dashboards couple of days ago.

**Comment by DraftProducts** [comment]
Hi @ivan-vdovin, I confirm that it is still relevant.

I was trying to create the Vue dashboard app from playground too.
I am using docker version `cubejs/cube:latest` in docker-compose with no extra options.

**Comment by cortegaunam** [comment]
I have the same problem when trying to create an app with VUE from playground, apparently the problem has not been solved.

**Comment by PhilippGsell** [comment]
Did anyone find a workaround yet?

**Comment by igorlukanin** [comment]
Dashboard app generation was removed from Cube some time ago. Please use the JavaScript SDK to integrate with Cube and create your own dashboard application: https://cube.dev/docs/product/apis-integrations/javascript-sdk
