### ISSUE TITLE
Failed to create React dashboard app from template

### ISSUE THREAD

**Issue by meskill** [cube-js/cube#3870]
**Describe the bug**
Creating a new dashboard app generates a broken app inside `cubejs/cube:latest` image

**To Reproduce**
1. Start cubejs image in dev mode
2. Go to `localhost:4000` and try to create a new dashboard-app
3. After some time page will show the button `Start dashboard app` which in not loading

**Expected behavior**

**Screenshots**
I get this in logs when generating app
```
cube-js_1            | Please remove any global installs with one of the following commands:
cube-js_1            | - npm uninstall -g create-react-app
cube-js_1            | - yarn global remove create-react-app
cube-js_1            | You are running `create-react-app` 4.0.3, which is behind the latest release (5.0.0).
cube-js_1            | 
cube-js_1            | We no longer support global installation of Create React App.
cube-js_1            | 
cube-js_1            | The latest instructions for creating a new app can be found here:
cube-js_1            | https://create-react-app.dev/docs/getting-started/
```

And this when trying to start the app:
```
cube-js_1            | Dashboard react-app failed with exit code 254
```

**Version:**
v0.29-alpine

**Additional context**
There is an [issue for the create-react-app](https://github.com/facebook/create-react-app/issues/11816) with the suggestion to use latest version of create-react-app

**Comment by paveltiunov** [comment]
Hey @meskill ! It seems it's still unresolved here https://github.com/facebook/create-react-app/issues/11816. We depend on 4.0.3 of create-react-app and they broke the backward compatibility of the whole installation flow. Ideally, create-react-app should fix this as I believe releasing new versions shouldn't break old ones. Alternatively, we can upgrade create-react-app but it'll require all react dependencies upgrade. We're looking for a volunteer here.

**Comment by ranrao** [comment]
@paveltiunov, any temporary workaround to resolve this issue? Problem still exists. Thank you

**Comment by matthieuCarlini** [comment]
Hi, is there a way to bypass this issue ? Do you think this issue could be added at the roadmap ?
Tanks.

**Comment by igorlukanin** [comment]
The option to generate a dashboard application has been removed from Cube long time ago. So, I guess this makes this question irrelevant now.
