### ISSUE TITLE
Hybrid view feeding from pre-aggregations and live data -- Lambda view

### ISSUE THREAD

**Issue by mkherlakian** [cube-js/cube#3887]
**Is your feature request related to a problem? Please describe.**
Right now when querying for pre-aggregated data, we have to choose between performance and slightly stale data, or a slow query (no pre-aggregation) and live data. In some of our applications at Hoodkeck, we'd like to  have as up to date data as possible with no impact on performance since our webhook count is an important metric for our users.

**Describe the solution you'd like**
In applications where data that ages becomes quickly static, it would be great to have the possibility of haveing a hybrid view that would combine pre-aggregated data with live data. So if the update window is set to 1 hour, and we request 1 day's worth of data, get 23 hours from pre-aggregations, and the one hour from live data.

**Describe alternatives you've considered**
The only alternative that we considered (and that we will end up implementing) is doing the merge on the client side. We'd request the data we know to be pre-aggregated up to 1 hour ago, and then we would create a different cube to get live data (which would be another interesting feature request - ability to bypass pre-aggregation from a query)/

**Additional context**
Data in the bar chart is fed from cubejs

![image](https://user-images.githubusercontent.com/1141190/148459743-9ee11c8a-f7fa-492d-8b27-1c95d7447890.png)

Thanks!

**Comment by igorlukanin** [comment]
[Lambda pre-aggregations](https://cube.dev/docs/product/caching/lambda-pre-aggregations) are supported by Cube for a long time.
