### ISSUE TITLE
API that allows querying rollups only

### ISSUE THREAD

**Issue by jcw-** [cube-js/cube#392]
**Describe the solution you'd like**
The use case is for a CubeJS usage that is intended to exclusively leverage pre-aggregations (rollups). In this case, it is desirable for the CubeJS API to only be used to get results from the pre-aggregation tables, and to avoid hitting the source DB (other than for the scheduled refresh).

Why? To ensure that the consumers of the API are getting speedy results and aren't accidentally straying away from level 2 caching and starting to see slower queries.

**Additional context**
https://cube-js.slack.com/archives/CC0403RRR/p1581702345073300?thread_ts=1581671608.067600&cid=CC0403RRR

**Comment by paveltiunov** [comment]
@jcw- Hey Jc! Thanks for posting this one! Agree on that one and I think it should be query level option so clients can opt-in for such behavior. For server-wide setting https://cube.dev/docs/@cubejs-backend-server-core#options-reference-query-transformer can be used to enforce it for all the queries.

**Comment by igorlukanin** [comment]
This is what `CUBEJS_ROLLUP_ONLY` is intended for: https://cube.dev/docs/reference/configuration/environment-variables#cubejs_rollup_only
