### ISSUE TITLE
Cube.js with Redis IO library returns error during fail over.

### ISSUE THREAD

**Issue by javiramos1** [cube-js/cube#3962]
**Describe the bug**

Cube.js with Redis IO library returns error during fail over.

**To Reproduce**

- Deploy Redis as a stateful set using sentinel, see: https://github.com/bitnami/charts/tree/master/bitnami/redis
- Connect Cube.js to redis using sentinel.
- Kill Master Pod.
- Wait few seconds for Sentinel to elect a new master.

**Expected behavior**

Expected Results: Cube.js retries Redis calls and wait a few seconds or skips Redis and queries the source data.
Actual Results: Cube.js API return error to the client.

**Screenshots**

**Version:**
0.29.21

**Comment by rpaik** [comment]
👋 a quick reminder that we will be replacing Redis with Cube Store as announced in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).

**Comment by igorlukanin** [comment]
I believe that this issue is not relevant anymore since Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
