### ISSUE TITLE
Add FusionCharts code/config generation in Developer Playground

### ISSUE THREAD

**Issue by adnanrahic** [cube-js/cube#4086]
**Is your feature request related to a problem? Please describe.**
When I use [FusionCharts](https://www.fusioncharts.com/), I need to write the code and config manually. The Developer Playground supports other charts like Chart.js, Recharts, etc, out of the box, but not FusionCharts. 

<img width="500" alt="Screen Shot 2022-02-14 at 15 19 01" src="https://user-images.githubusercontent.com/15029531/153881342-ec065f83-8d54-49bb-8fdb-74663aba212c.png">

**Describe the solution you'd like**
In the same way that Cube has the generation of code for Chart.js, Recharts, Bizcharts, and D3, add an option for FusionCharts as well. Here's an [example from the FusionCharts docs](https://www.fusioncharts.com/react-charts?framework=react).

**Describe alternatives you've considered**
The only alternative now is to manually write the config for FusionCharts.

**Additional context**
This was a question that was mentioned during the Cube + Appsmith Live Event you can check out [here](https://www.youtube.com/watch?v=i49L2eerQ8I).

**Comment by igorlukanin** [comment]
Dashboard app generation was removed from Cube Core long time ago.
