### ISSUE TITLE
Dev server does not respect the CUBESTORE_DATA_DIR variable

### ISSUE THREAD

**Issue by JaySunSyn** [cube-js/cube#4133]
**Describe the bug**

It would be great if we could define the data path of where `cubejs-server` stores the pre-aggregation files.

```
CUBESTORE_DATA_DIR=.cubestore/test-data cubejs-server
```

does not work as `CUBESTORE_DATA_DIR` is a cube store env var I guess. 

The pre-aggregation data is stored in `.cubestore/data` no matter the value of CUBESTORE_DATA_DIR.

**To Reproduce**
1. Run CUBESTORE_DATA_DIR=.cubestore/test-data cubejs-server
2. Check the local .cubestore/ folder

**Additional context**
I’ve created a Jest query test reporter which runs its own instance of the dev server. If additionally, the normal dev server runs, the data gets conflicted as they both use the same data folder.

**Comment by igorlukanin** [comment]
I guess this change (https://github.com/cube-js/cube/pull/3045) will fix this issue.

**Comment by igorlukanin** [comment]
@JaySunSyn By any chance, could you please check that this works as expected on the latest version of Cube?
