### ISSUE TITLE
Make dashboard app port configurable

### ISSUE THREAD

**Issue by jsbrain** [cube-js/cube#4136]
https://github.com/cube-js/cube.js/blob/7d2cf5469ea62fe20f18fc60044e0fd88d233ecd/packages/cubejs-server-core/src/core/server.ts#L414

Apparently, the dashboard app port is hardcoded which is a bummer if one already has an app running on port `3000`.

Manually "hacking" the port in the `package.json` to `"react scripts start --port 3111"` does start the dashboard on the other port but the start command will be messy as my logs show:

```
cube_1   | 
cube_1   | > dashboard-app@0.1.0 start /cube/conf/dashboard-app
cube_1   | > react-scripts start --port 3111 "--port" "3000" "--host" "0.0.0.0"
cube_1   | 
````

Also it doesn't help much as the dashboard while starting on port `3111` won't be connected to the playground.

This means one always has to reconfigure a potentially already configured application to get the dashboard app up and running and working with the playground.

Is there any specific reason why it's implemented like that or am I missing something here?

**Comment by jsbrain** [comment]
Having `CUBEJS_DASHBOARD_APP_PORT` would be amazing and easy to implement (I think)?

**Comment by igorlukanin** [comment]
Dashboard app generation was removed from Cube Core long time ago.
