### ISSUE TITLE
Add a way to specify that a dimension/measure is an integer

### ISSUE THREAD

**Issue by reify-thomas-smith** [cube-js/cube#4200]
**Is your feature request related to a problem? Please describe.**
When I get results from `useCubeQuery`, I would like to automatically convert them to the proper data types — `number` or `bigint`. I would like to do this based on the defined schema. However, the schema does not provide that information.

**Describe the solution you'd like**
Either new values for `type` or (perhaps more practically) a new `integer` key.

**Describe alternatives you've considered**

- Manually specify this information elsewhere and keep it up to date as the schema changes.
- Just convert everything to `number` and hope that this doesn't result in loss of precision.

**Additional context**
Might be relevant to https://github.com/cube-js/cube.js/issues/349.

**Comment by igorlukanin** [comment]
This is what `castNumerics` is for: https://cube.dev/blog/cube-core-v0-34-34-python-and-powerful-updates#castnumerics-in-front-end-sdks
