### ISSUE TITLE
Athena: SYNTAX_ERROR: IN value and list items must be the same type

### ISSUE THREAD

**Issue by 9teen90nine** [cube-js/cube#43]
This error happens when you set a filter for a numeric (or other non-string) dimension or measure with multiple values. It looks like athena requires to cast all values in the IN statement to the type of dimension/measure.

**Comment by rajanjha786** [comment]
Hello
I'm getting a somewhat similar error
IN value and list items must be the same type: varchar

I'm querying Athena using boto3
`Query: SELECT a.column1 FROM ABC a WHERE a.column1 IN ('abc', 'xyz')`

python: 3.8
boto3: 1.24.30

Is there any updates ?

**Comment by aayush801** [comment]
Any fixes to this ?

**Comment by chandrakantsn** [comment]
I am also facing the same issue, any fixes to this ?
