### ISSUE TITLE
Directly edit query by editing Json query field.

### ISSUE THREAD

**Issue by mercer2000** [cube-js/cube#4377]
In the playground area, I would like to be able to edit the Json query directly and then use the drop-down fields to make changes. 

Sometimes I need to make changes to a query and often find myself having to rebuild the query using the drop downs. I would like to be able to paste the Json query and then make changes.

**Comment by igorlukanin** [comment]
Since v0.36.x, pasting a REST API query is now supported in Cube Core as well. Please see https://cube.dev/docs/product/workspace/playground#pasting-a-query
