### ISSUE TITLE
Add support to rename the query tabs

### ISSUE THREAD

**Issue by mercer2000** [cube-js/cube#4378]
I would like to be able to edit the query tabs to make it easier to find the queries I am working on. 

Currently, the query names are Query 1, Query 2, Query 3, etc. Being able to rename the query would make it easier to use the playground area when developing multiple queries.

**Comment by ganeshmani** [comment]
@paveltiunov can I work on this issue?

**Comment by paveltiunov** [comment]
@ganeshmani Yep. Sure! It'd be great!

**Comment by igorlukanin** [comment]
This is implemented long time ago: https://cube.dev/blog/cube-cloud-update-query-history-sql-runner#renaming-tabs-in-playground
