### ISSUE TITLE
Upgrade Docker image from Node 14 to Node 16

### ISSUE THREAD

**Issue by robd003** [cube-js/cube#4437]
**Problem**

I've had trouble building Cube.js on arm64 using the Docker image, but was able to build after upgrading the image from node14 to node16.

Is there any reason to use a soon to be out of date Node release? It'd be great to move to Node 16 which will be supported till Apr 2024.

**Comment by paveltiunov** [comment]
@robd003 Are you building a custom image on top of Cube one?

**Comment by robd003** [comment]
I was building dev builds of Cube

**Comment by johanjvrens** [comment]
In the Docker image, I see the node version is: ENV NODE_VERSION=14.18.2
This version is in maintenance mode: https://nodejs.org/en/about/releases/ maybe bump to newer Node16 or 18 as they are active and current?

**Comment by igorlukanin** [comment]
Docker images has been updated to Node 16.20.2: https://github.com/cube-js/cube/blob/master/packages/cubejs-docker/latest.Dockerfile#L1
