### ISSUE TITLE
An approach for automatic member type conversion

### ISSUE THREAD

**Issue by reify-thomas-smith** [cube-js/cube#4469]
Cube record values are often returned as strings. However, they often represent other data types, such as numbers, and in order to work with them it's usually necessary to convert them. But the Cube schema already contains information about the types of cube members — the `type` property, which is `"string" | "number" | "boolean" | "time"`.

#349 suggests accessing the Cube metadata in order to perform automatic type conversions. This could work, but doing it at runtime has two main disadvantages: it requires an extra call at runtime, and the type information is not available at compile time. Instead, I have a script that queries the schema, gets the declared type of each cube member, and saves it to a TypeScript file. This file is committed in the repository and re-generated when the Cube schema changes. Using this type definition file, it is possible to write a function that takes a record, determines the intended type of each member, and automatically converts that value to the correct type.

Implementing this approach in the Cube.js core would require three new “moving parts”:

#### Type definition generator

We'd need a script exposed by one of the Cube.js packages that takes in the information required to access a Cube.js service and produces a type definition file. The structure of the file could simply be a mapping from Cube member names `e.g. Foo.bar` to Cube member types (`"string" | "number" | "boolean" | "time"`)`. A user project could invoke the script via `npx` or add a `script` to their `package.json`.

In order to provide complete TypeScript type inference, the type definition file would have to be a TypeScript file. However, as an option, the script could instead produce a JavaScript file or a JSON file and everything would work fine, only without complete TypeScript type inference.

If desired, the script could examine additional Cube metadata. For instance, there could be a new optional field that would let users specific a different type string for a member. For instance, a user might specify that a member was an integer, or a UUID.

(As an added bonus, a file like this could also be used by user code to statically detect errors resulting from misspelled or nonexistent cubes or cube members.)

#### Type constructors

For each cube member type (`"string" | "number" | "boolean" | "time"`), we'd need a constructor function that takes in a value of type `string | number | boolean | null` and converts it to an appropriate data type, such as `number` or `Date`. If the value can't be converted, then the constructor should throw a TypeError; this would indicate either a bug in the driver or bad info in the schema.

Different user applications could call for different construction. For instance, while reasonable default behavior would be to turn a Cube `time` into a native JS `Date`, users may want to use alternative date libraries. Or, if the type definition generator allows users to specify custom Cube types, such as `integer` or `uuid`, then the user code would need a type constructor for that type.

#### Typing function

We'd need a function that takes in a) a record returned from a Cube query, b) the mapping from the type definition file, and c) a mapping of Cube type names to constructors, and does the appropriate type conversions. This is actually a very simple operation; my implementation is about 30 lines, most of which is detailed error handling.

Perhaps surprisingly, this can all be strictly type-inferred.

---

Obviously, this is not a trivial suggestion. I've been using it for a week or so, and it works great for me. There's a lot going on, but the user-facing parts are very simple while allowing for a lot of customization.

Before I even think of making a PR, I'd appreciate feedback — how does this approach sound? Is there any obstacle or downside I'm missing? Is there any existing plan for providing automatic type conversion that this might conflict with?

**Comment by igorlukanin** [comment]
This is what `castNumerics` is for: https://cube.dev/blog/cube-core-v0-34-34-python-and-powerful-updates#castnumerics-in-front-end-sdks
