### ISSUE TITLE
Epic: Databricks data warehouse support

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#4494]
- [x] Integration with Databricks.
- [ ] Export bucket feature for enhanced pre-aggregations support.

**Comment by alxsbn** [comment]
Hi @rpaik . Any news about this one?

**Comment by igorlukanin** [comment]
Hi @alxsbn 👋 

[Databricks](https://cube.dev/docs/product/configuration/data-sources/databricks-jdbc) is fully supported by Cube. [Export buckets](https://cube.dev/docs/product/configuration/data-sources/databricks-jdbc#export-bucket) are also supported for AWS and Azure.

Closing this one as complete—but please feel free to reopen.

**Comment by alxsbn** [comment]
@rpaik Thanks. It wasn't obvious at first, bc running the container didn't give me the Databricks driver on the list 
![image](https://github.com/user-attachments/assets/0e006a67-b400-4122-b05a-9614b8a93646)
