### ISSUE TITLE
Query is matching with preaggregation in which dimension doesn't exist

### ISSUE THREAD

**Issue by ashwanisinghh** [cube-js/cube#4563]
**Describe the bug**
I have created a preagg with set measures & dimensions. But when I am querying the data with filter on dimension which doesn't exist in preaggregation, it throws error that column does not exist.

**To Reproduce**
create preaggregation with 1 measure & 1 dimension without any timeDimension
Then create a query for that preagg with 1 additional filter on dimension which is not in preaggregation (filter type any except equal)
It throws error that column doesn't exists

**Expected behavior**
The query must not have matched with preaggregation & fetched data from source db instead of preaggregation, as newly added filter is not in preaggregation table

**Screenshots**
Preagg Definition
![image](https://user-images.githubusercontent.com/13466549/169336293-c3f010b3-200c-4ee7-8bca-b7cd4b2b7040.png)

Error when querying with dimension which is not in preagg
![image](https://user-images.githubusercontent.com/13466549/169336481-31171594-1d2b-47e7-a549-32a42f613fc0.png)

**Version:**
[0.29.55]

**Comment by ashwanisinghh** [comment]
@ivan-vdovin any status on this please

**Comment by paveltiunov** [comment]
Should be fixed in latest version.
