### ISSUE TITLE
Dbt Integration: Get dbt metric description populated in measures description

### ISSUE THREAD

**Issue by chaos87** [cube-js/cube#4849]
Hi there👋,

Thanks a lot for the integration with dbt project.

As of now it is possible to get dbt metric name, sql and the underlying model.

I would like to get the description attribute for a dbt metric mapped to a measure description.

**Comment by lewisosborne** [comment]
+1 - and descriptions for all dimensions also

**Comment by keydunov** [comment]
Due to the [change in direction](https://docs.getdbt.com/blog/deprecating-dbt-metrics) at dbt, we are deprecating `@cubejs-backend/dbt-schema-extension`. When a new dbt metrics package becomes available, we will update and reintroduce our integration.
