### ISSUE TITLE
Epic: Replace Redis with Cube Store

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#5042]
Currently, Cube relies on Redis for in-memory caching and queue management, and this is inefficient and not scalable. Redis cluster coordination consumes a lot of resources under the high load and becomes the bottleneck to scaling the API concurrency.

Cube Store will replace Redis for in-memory caching and queue management and you will find more details in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).

**Comment by igorlukanin** [comment]
Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
