### ISSUE TITLE
Epic: Build metrics in Cube data model

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#5044]
Cube allows to define the foundation of the data model through cube objects and joins between them, but it currently lacks a framework to define metrics as a second layer on top of the data model. While it is possible now to expose cubes through the SQL API, it is not yet sufficient to support the internal BI (metrics) use cases.

This epic will introduce a way to build metrics in the Cube data model, and allow data consumers to discuss/document/social metrics with a metric object.

**Comment by JPHaus** [comment]
Hi @rpaik, do you have thoughts on being able to import [dbt metrics](https://docs.getdbt.com/docs/building-a-dbt-project/metrics) into cube?

**Comment by rpaik** [comment]
Thanks @JPHaus...

@paveltiunov can you share your thoughts on @JPHaus questions 👆?

**Comment by rpaik** [comment]
@JPHaus actually, have you seen this [blog post](https://cube.dev/blog/dbt-metrics-meet-cube)?
