### ISSUE TITLE
dashboard-app filter bug

### ISSUE THREAD

**Issue by GUISSEBOCAR** [cube-js/cube#5115]
Hi
I integrated the Vue 2 dashboard into our platform (it works) but I have a little problem with the filters.

if I add for example 2 filters and remove 1 afterwards, the dashboard does not load.

I also tested with

https://vue-query-builder-demo.cube.dev/#/

I have the same problem

**Comment by igorlukanin** [comment]
The option to generate a dashboard application has been removed from Cube long time ago. So, I guess this makes this question irrelevant now.
