### ISSUE TITLE
Alternative to `checkSqlAuth`

### ISSUE THREAD

**Issue by lsowen** [cube-js/cube#5430]
Currently, authentication for the SQL API is handled by implementing `checkSqlAuth(request, username)`, which, based on the user passed in returns the expected password and security context for the user (https://github.com/cube-js/cube.js/blob/074655ec57493b4ddf711d466749b82b46d87c42/docs/content/SQL-API/Authentication-and-Authorization.mdx).

Is there any interest in an alternative `checkSqlAuth(request, username, suppliedPassword)`, where the handler would be responsible for checking if the password is correct?  This would have a few benefits:

1. Allow the use of non-cleartext passwords, as the `checkSqlAuth` could check if the hash of the suppliedPassword matches the stored hash
2. Allow the use of "pass-through" authentication.  For example, if the username/password supplied matches a username/password on the underlying database, allow access
3. Other, more complicated schemes without further altering Cube.  For example LDAP, kerberos, etc

**Comment by fbvdka** [comment]
Totally in favor of this alternative!

**Comment by DanlBradley** [comment]
Agreed. I can see issues on Cube's end with suppliedPassword. 

Another workaround would be to build some sort of functionality for hashing supplied passwords. Main point is we do not want to be storing cleartext passwords in our databases for cube multitenancy.

**Comment by paveltiunov** [comment]
@lsowen @fbvdka @DanlBradley Thanks for providing the feedback! I think if we stick with cleartext auth for Postgres, we can provide such an option.

**Comment by lsowen** [comment]
@paveltiunov are you open to contributions on this?  I would be willing to take a stab at implementing, but wanted to make sure there was interest in it.

**Comment by paveltiunov** [comment]
@lsowen Yep! Please feel free to provide PR for that!

**Comment by lsowen** [comment]
Awesome, I'll work on it over the next couple of weeks

**Comment by lsowen** [comment]
Looks like this was originally implemented this way due to the MySQL cubesql API: https://github.com/cube-js/msql-srv/blob/e3010bd6680a89feff53bcd3f74afa21f5403f70/src/lib.rs#L559-L589

It looks like this will eventually be removed, but not sure the timeline.

**Comment by fbvdka** [comment]
Ok. But can we think of an evolution with checkSqlAuth(request, username, suppliedPassword) and keep the same behavior after (return password) ? 
Here is an example with an authentication from systme like Keycloak:

```
  checkSqlAuth: async (req, username, password) => {
    try {
      const token = await tokenFromUser(username, password);
      if (token && token.length>0) {
        return {
            password: password,
            superuser: false,
            securityContext: {
              tenantId: md5(username),
              tenant: username,
              password: password,
            },
        };
      } else {  
        throw new Error('Incorrect user name or password'); 
      }

    } catch (err) {
      throw new Error('Incorrect user name or password');
    }
  }
```

**Comment by iamzjk** [comment]
Hi,

Is there any update on this? We are trying to use the SQL API in a multi tenancy setup. We’d love to see this new change.

**Comment by iamzjk** [comment]
Hi @paveltiunov 

I wonder if anyone is still actively working on this. If not, if you can give me a few pointers, I can give it a try.
