### ISSUE TITLE
@cubejs-client/ngx - Angular 14 IVY Support

### ISSUE THREAD

**Issue by Mutondi** [cube-js/cube#5439]
**Problem**

Good Day,

Has this library been upgraded to Angular 14, we have one project heavily reliant on this and experiencing serious optimization issues due to the library not being IVY compliant.

Do we have a solution/roadmap it would suck to have to replace this in production

**Comment by paveltiunov** [comment]
Hey @Mutondi ! This is outside of core team roadmap however feel free to provide PR for that!

**Comment by Mutondi** [comment]
Sure I will take this on

**Comment by brieucdlf** [comment]
@Mutondi Are you on it? I can check if needed :)

**Comment by Mutondi** [comment]
> @Mutondi Are you on it? I can check if needed :)

Hey please feel free to get on it !
