### ISSUE TITLE
DBT integration fails when metrics sql contains "."

### ISSUE THREAD

**Issue by yinkaihsu** [cube-js/cube#5464]
**Describe the bug**
When I use the DBT integration with the following code:
```
import dbt from '@cubejs-backend/dbt-schema-extension'

asyncModule(async () => {
  await dbt.loadMetricCubesFromDbtProject('/dbt');
});
```

It will return error like below:

```
Compile errors:
DwhBigqueryFctEvents cube: (dimensions.events.eventType = [object Object]) is not allowed
```

The `manifest.json` of dbt project would look like:
```
"metrics": {
        "metric.dwh_bigquery.total_event_count": {
            "name": "total_event_count",
            "description": "The total event count of event tracking table",
            "label": "Total Event Count",
            "type": "count",
            "sql": "events.id",
            "timestamp": "events.created_at",
            "filters": [],
            "time_grains": [
                "day",
                "week",
                "month"
            ],
            "dimensions": [
                "events.event_type",
                "events.city",
                "events.browser",
                "events.traffic_source",
                "users.age",
                "users.gender",
                "users.country"
            ],
            "model": "ref('fct_events')",
           ...
        }
    },
```

**Expected behavior**
I think this error happens because it wrongly treat "." as an element within the object, but instead it should be a `RECORD` column in BigQuery, which is like the dimension `"events.event_type"` above. In that way, metrics & dimensions could be set and sync correctly from `manifest.json` of dbt project.

**Comment by keydunov** [comment]
Due to the [change in direction](https://docs.getdbt.com/blog/deprecating-dbt-metrics) at dbt, we are deprecating `@cubejs-backend/dbt-schema-extension`. When a new dbt metrics package becomes available, we will update and reintroduce our integration.
