### ISSUE TITLE
Incorrect logic in LIKE in Cube SQL API

### ISSUE THREAD

**Issue by frimuchkov** [cube-js/cube#5519]
**Describe the bug**
LIKE operator works as a regexp, not as LIKE

**To Reproduce**
1. Write a query like this `Report."campaign" LIKE '%Brand Awareness - SS 5_ Purchase - Full Price [CAMPAIGN]%'`
2. Call this query on data with preaggregations
3. Call this query on data without preaggregations
4. See different results (Cube doesn't parse `_`)

Problem with additional percent:
1. Write a query like this `Report."campaign" LIKE '%Brand Awareness - SS 5%[CAMPAIGN]%'`
2. See an error

LIKE works as a regexp:
1. Write a query like this `Report."campaign" LIKE 'Brand Awareness - SS 5.{1} Purchase - Full Price \[CAMPAIGN\]'`
2. Call this query on data with preaggregations
3. See the result, but there shouldn't be any rows, because LIKE is not a regexp.

**Expected behavior**
We expect, LIKE support `%` and `_` symbols. Users are able to use these symbols in any place.
LIKE shouldn't parse a string as a regexp.

**Screenshots**
![image](https://user-images.githubusercontent.com/19934346/197852831-4e5e86af-90d5-4ed5-9589-b12a192553bb.png)
![image](https://user-images.githubusercontent.com/19934346/197852844-500465ab-150c-49e4-80a6-a13a2ad364e3.png)

**Version:**
0.31.1

**Comment by gandronchik** [comment]
Hello @frimuchkov. Thank you for this issue. We added it to backlog and I will notify you when it is done

**Comment by paveltiunov** [comment]
Fixed in latest version.
