### ISSUE TITLE
 Cube.js should acknowledge filter: tag in DBT  Metrics when it transform DBT Metrics into its .js file. 

### ISSUE THREAD

**Issue by prince-lumiq** [cube-js/cube#5591]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dkucharc** [comment]
Are there any plans to start supporting filters tag in the nearest future?

**Comment by paveltiunov** [comment]
@dkucharc Yep. We're considering adding it to our roadmap as well as looking forward to contributions here!

**Comment by dkucharc** [comment]
@paveltiunov More than happy to contribute here. I would appreciate your help in getting the above PR approved and merged.

**Comment by keydunov** [comment]
Due to the [change in direction](https://docs.getdbt.com/blog/deprecating-dbt-metrics) at dbt, we are deprecating `@cubejs-backend/dbt-schema-extension`. When a new dbt metrics package becomes available, we will update and reintroduce our integration.
