### ISSUE TITLE
loadMetricCubesFromDbtCloud function fails due to metadata api incorrect response

### ISSUE THREAD

**Issue by fd2533** [cube-js/cube#5599]
**Describe the bug**
Compilation error in cube cloud when trying to extend a cube created with the loadMetricCubesFromDbtCloud function.

It seems to be a problem with the DBT cloud metadata api response returning the same model for every single metric fetched.

**To Reproduce**
1. Implement the @cubejs-backend/dbt-schema-extension (version 0.31.13)
2. Create a new cube extending the one created from loadMetricCubesFromDbtCloud 
3. Load your server.
<img width="1071" alt="Screenshot 2022-11-10 at 11 33 50" src="https://user-images.githubusercontent.com/33346354/201080813-1eb8734d-9ce9-4956-8a75-0730cdb2dab6.png">

**Expected behavior**
To load the correct metrics.

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
import { schema_override } from "../config";

cube(`Item`, {
  ...(schema_override
    ? { sql: `select * from ${schema_override}.itemTableName` }
    : {}),

  extends: DbtProjectNameItem,
  preAggregations: {
    statsDay: {
      measures: [
        Item.itemCount,
        Item.itemCumulativeCount,
        Item.itemRolling7Days,
        Item.itemRolling14Days,
        Item.itemRolling30Days],
      dimensions: [
        Item.itemId,
        Item.itemName,
      ],
      timeDimension: Item.itemCreatedOn,
      granularity: `day`,
      partitionGranularity: `month`,
    },
  },

  joins: {},

  measures: {
    itemCumulativeCount: {
      type: `count`,
      sql: `item_id`,
      rollingWindow: {
        trailing: `unbounded`,
      },
    },
    itemRolling7Days: {
      type: `count`,
      sql: `item_id`,
      rollingWindow: {
        trailing: `7 day`,
      },
    },
    itemRolling14Days: {
      type: `count`,
      sql: `item_id`,
      rollingWindow: {
        trailing: `14 day`,
      },
    },
    itemRolling30Days: {
      type: `count`,
      sql: `item_id`,
      rollingWindow: {
        trailing: `30 day`,
      },
    },
  },


```

**Version:**
0.30.46

**Comment by hienduyph** [comment]
Maybe related,  https://github.com/cube-js/cube.js/pull/5746.
DBT >= 1.3 changed metrics fields like `type -> calculation_method`, `sql -> expression`

**Comment by paveltiunov** [comment]
Related issue #5591

**Comment by keydunov** [comment]
Due to the [change in direction](https://docs.getdbt.com/blog/deprecating-dbt-metrics) at dbt, we are deprecating `@cubejs-backend/dbt-schema-extension`. When a new dbt metrics package becomes available, we will update and reintroduce our integration.
