### ISSUE TITLE
Prefer .yaml file extension for YAML files

### ISSUE THREAD

**Issue by reify-thomas-smith** [cube-js/cube#5651]
[The documentation for YAML models](https://cube.dev/blog/introducing-cube-support-for-yaml-data-modeling) uses the `.yml` extension for YAML files. While the YAML language spec does not specify any file extension (as that's outside the scope of the spec), the [YAML FAQ](https://yaml.org/faq.html) does specify `.yaml` as the preferred extension for YAML files.

Usage in the wild is split between `.yaml` and the `.yml`, so Cube.js should probably accept/look for both. But since this is a new feature, the documentation will effectively establish the convention, so it may as well use the preferred extension.

**Comment by paveltiunov** [comment]
@reify-thomas-smith Yep. Agree. Cube already supports both. We haven't decided yet what should be a doc standard, though. While `.yaml` is more aligned with a spec, `.yml` seems much more adopted. Would love to hear more community opinions here.

**Comment by igorlukanin** [comment]
As Pavel mentioned, Cube already supports both extension and we'll carry on recommending `.yml` by default since it's a more adopted version. Closing this issue for now.
