### ISSUE TITLE
Issue with extensions when building webpack

### ISSUE THREAD

**Issue by Mikhail-1985** [cube-js/cube#5653]
**Problem**

Sorry, I'm new to frontend and have the following problem. When I use webpack to build, I get the error "ERROR in ./node_modules/@cubejs-client/react/dist/cubejs-client-react.esm.js" because it uses jsx markup in js. Changing the extension from js to jsx solves the problem, but this solution is not suitable for working with pipelines on remote servers. Is there any standard solution for working with webpack?

**Related Cube.js schema**

It's not important

**Related Cube.js generated SQL**

It's not important

**Comment by igorlukanin** [comment]
Hey @Mikhail-1985 👋 Is this issue still relevant?

**Comment by Mikhail-1985** [comment]
Hey @igorlukanin ! the issue can be closed.
