### ISSUE TITLE
cache: support event driven cache invalidation

### ISSUE THREAD

**Issue by derekperkins** [cube-js/cube#5683]
**Is your feature request related to a problem? Please describe.**
Polling for the `refreshKey` is inefficient, can be costly, and prevents you from running as close to real-time as possible.

**Describe the solution you'd like**
I already have events defined when my underlying data changes, so I would prefer to turn off polling and instead make an api call to manually invalidate the cache

**Describe alternatives you've considered**
I understand polling is the simplest choice and works with all underlying datastores. I've considered creating a separate table to poll that I update manually, but that doubles tables under management for minimal gain.

**Additional context**
This idea could potentially be integrated into the core product down the road. With other tools like Debezium and Airbyte, listening on a CDC stream for a db could be monitored for cache invalidation.

**Comment by paveltiunov** [comment]
@derekperkins It's supported for kSQL right now.

**Comment by derekperkins** [comment]
Is there not an api call that can do it for any data source?

**Comment by paveltiunov** [comment]
@derekperkins There's no public API for that however Cube Store supports ingestion of upserts through MySQL interface. You'd need to write your own database driver that would manage pre-aggregation tables creation and population to use that.

**Comment by derekperkins** [comment]
Is this being closed as a wontfix? I still think it's a very valid use case, and ksql or custom mysql driver support aren't really solutions.

**Comment by paveltiunov** [comment]
@derekperkins Could you please elaborate on your use case? What data source do you use that you want to update pre-aggregations for in an event-based/real-time fashion?

**Comment by derekperkins** [comment]
Any data source could benefit from non-polling event driven updates. Why poll BigQuery 1k times and have an arbitrary delay in updating when I could listen for job completion and proactively inform Cube that the underlying BigQuery data has changed? Now the polling connection doesn't have to be kept open, conserving resources on both sides, with no wasted work or query costs. Many systems will already have those events available.

The underlying mechanism already exists in some form, e.g. when polling detects a change, it triggers a refresh. I'm asking for that to be exposed via API, turn off polling, and manage the refresh lifecycle manually.

**Comment by paveltiunov** [comment]
@derekperkins I guess what you're looking for is https://cube.dev/docs/rest-api/#api-reference-cubejs-system-v-1-pre-aggregations-jobs.

**Comment by paveltiunov** [comment]
@derekperkins Does it solve your issue?
