### ISSUE TITLE
SQL API - Different node.js versions in Cubejs Docker images returning Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js

### ISSUE THREAD

**Issue by rili-ib** [cube-js/cube#5748]
**Describe the bug**
I have been working on trying to add the SQL API to our cubejs service using Docker but have hit a blocker with the different nodejs versions. In our Docker image, we are currently using `cubejs/cube:v0.31.20-alpine` as our base image but when adding the `CUBEJS_PG_SQL_PORT=5432`, `CUBEJS_SQL_USER=myusername`, `CUBEJS_SQL_PASSWORD=mypassword` as specified in the docs, we're immediately hit with an error message, `Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js, probably your system (x64-linux) with Node.js v14.18.2 is not supported.`. 

However, this is not the case when using `cubejs/cube:latest`. After investigating the different node versions, it looks like alpine docker image is using v14.18.2 as shown in https://github.com/cube-js/cube.js/blob/master/packages/cubejs-docker/latest-alpine.Dockerfile#L1 but `cubejs/cube:latest` is using https://github.com/cube-js/cube.js/blob/master/packages/cubejs-docker/latest.Dockerfile#L1. 

**To Reproduce**
1. Update the base image to `cubejs/cube:v0.31.20-alpine` in the `docker-compose.yml`
2. Add `CUBEJS_PG_SQL_PORT=5432`, `CUBEJS_SQL_USER=myusername`, `CUBEJS_SQL_PASSWORD=mypassword` to .env
3. Run `docker-compose up`
4. See error: `Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js v14.18.2 is not supported.`. 

**Expected behavior**
I would expect while using `cubejs/cube:v0.31.20-alpine`, it should not have returned an error message regarding the unsupported node.js version when adding cube sql API. 

**Version:**
node.js v14.18.20

**Comment by ovr** [comment]
Hello @rili-ib,

It's related to `alpine`, because alpine uses MUSL libc, not a GNU libc. Right now, We don't support it.

**Comment by ovr** [comment]
Hello!

It's related to alpine because it uses MUSL libc, which we still don't support.

Thanks

**Comment by igorlukanin** [comment]
Hi @rili-ib 👋 

Some time ago, we stopped maintaining [Alpine images](https://cube.dev/blog/cube-core-v0-35-updates-to-data-modeling-and-data-sources#alpine-based-docker-images-removed). Could you please check on a recent Cube image, e.g., [v0.36.7](https://hub.docker.com/layers/cubejs/cube/v0.36.7/images/sha256-29bc336a7a15e9734444228eed0a2ba56dfc610d112b4e773a7152c16b6631d4?context=explore)?
