### ISSUE TITLE
SAP Hana Support

### ISSUE THREAD

**Issue by oguzCoel** [cube-js/cube#576]
Can it be assumed that SAP Hana will also be supported as a database in the near future?

We would use Cube js very professionally in the health care sector. Unfortunately we see that SAP Hana is not supported. We would be happy if the support can be given. 

Is there any other way to integrate the node hdb (Sap Hana driver for Nodejs) driver into the cube js?

Thanking you for your answers in advance

**Comment by paveltiunov** [comment]
@oguzCoel Hey Oguz! Thanks for posting this! There's a guide on how to implement driver: https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md#implementing-driver

**Comment by oguzCoel** [comment]
Thank you, for your quick response. I will try to install the node hdb, according to the guide.
I will give a feedback shortly.

**Comment by oguzCoel** [comment]
@paveltiunov The guide is quite abstract, according to which specifications the driver must be installed. In the package folder I see various drivers for other database systems which are always implemented differently. We want to integrate the driver below. 

https://github.com/SAP/node-hdb

Can you give us more details or help us to install this driver. Is possible that we did not understand one or the other point in the description.

Many thanks for your support in advance.

**Comment by zhjuncai** [comment]
I knew this is an old thread, just would like to ask if there is any progress? @oguzCoel did you get any luck that hdb driver installed successfully?

**Comment by igorlukanin** [comment]
For the record, there's a community-supported HANA driver right now: https://www.npmjs.com/package/cubejs-hana-driver
