### ISSUE TITLE
dashboard is not working with lastest version of node v18.12.1 

### ISSUE THREAD

**Issue by fahadmhd** [cube-js/cube#5837]
[error.txt](https://github.com/cube-js/cube.js/files/10240359/error.txt)

I have been using dashboard with 14.16.0 , it was working well. But now I updated nodejs to v18.12.1 and dashboard is not working. I am unable to resolve node js dependencies.
 Any help is appreciated

**Comment by igorlukanin** [comment]
Hi @fahadmhd 👋 Were you able to resolve this issue? Is it relevant anymore?

**Comment by paveltiunov** [comment]
Closing as dashboard feature was deprecated
