### ISSUE TITLE
Cognito auth unexpectly fails with "Unable to find keys inside response from JWK_URL"

### ISSUE THREAD

**Issue by hugoJuhel** [cube-js/cube#5853]
**Describe the bug**
CubeJS's Cognito Auth failed to read the "keys" attribute of AWS's .well-known/jwks.json.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an AWS Cognito User Poll and Application
2. Open your browser and go to `https://cognito-idp.<AWS_REGION>.amazonaws.com/<USER_POOL_ID>/.well-known/jwks.json`. Note that a top-level `keys` attribute is present in the well-known.
3. Configure Cognito Auth as per CubeJS's documentation
4. Execute a query against Cube and check the Logs. CubeJS (latest) fails with "Unable to find keys inside response from JWK_URL"

**Expected behavior**
CubeJS should be able to read the `keys` attribute.

**Version:**
v0.31.29

**Comment by paveltiunov** [comment]
@hugoJuhel Could you please reproduce it in Cube Cloud?
