### ISSUE TITLE
'Field "x" doesn't exist in row' for external dimensions

### ISSUE THREAD

**Issue by leopedrassoli** [cube-js/cube#5911]
**Problem**
 
Please consider that I'm using docker-compose file with lastest images.
 
I'm using the Cube.js schema below and I'm trying to use **cardColumn2** as a dimension in query, but I'm getting the following error:
_Error during processing PostgreSQL message: Internal: Execution error: Unexpected response from Cube.js, Field "accounts.cardColumn2" doesn't exist in row_
 
```javascript
cube(`Accounts`, {
  sql: `SELECT * FROM accounts`,
  preAggregations: {
  },
  joins: {
    Cards: {
      relationship: `belongsTo`,
      sql: `${CUBE.id} = ${Cards.id}`
    }
  },
  measures: {
    measure1: {
      sql: `id`,
      filters: [{
        sql: ` ${CUBE}.accountColumn1 = true and ${Cards}.cardColumn2 is not null`
      }],
      type: `countDistinct`
    }
  },
  dimensions: {
    Id: {
      sql: `id`,
      type: `string`,
      primaryKey: true
    },
    accountColumn1: {
      sql: `column1`,
      type: `boolean`
    },
    cardColumn2: {
      sql: `${Cards.cardColumn2}`,
      type: `string`
    }
  },
  dataSource: `default`
});
 
 
cube(`Cards`, {
  sql: `SELECT * FROM cards`,
  preAggregations: {
  },
  joins: {
  },
  measures: {
  },
  dimensions: {
    Id: {
      sql: `id`,
      type: `string`,
      primaryKey: true
    },
    cardColumn2: {
      sql: `column2`,
      type: `string`
    }
  },
  dataSource: `default`
});
```
 
Query that generates the error:
```sql
SELECT id, "cardColumn2"
FROM public."accounts"
LIMIT 10;
```
 
When I try to run this query on cube "accounts" I'm getting the mentioned error message. But if get the JSON query (from cube_api logs) and try it in the API (/cubejs-api/v1/load) is works successfully. It also works successfully if it's in a pre-aggregated data.
 
 
**JSON Query:**
```json
{
  "measures": [],
  "dimensions": [
    "accounts.id",
    "accounts.cardColumn2"
  ],
  "segments": [],
  "limit": 10
}
```
 
**Question**: What could I possibly be doing wrong? Considering that the relationship between the cubes seems to be working correctly, as the **accounts.measure1** returns the values ​​correctly. Thanks.

**Comment by paveltiunov** [comment]
@leopedrassoli Did you have a chance to try running it without quotes?
```
SELECT id, cardColumn2
FROM public."accounts"
LIMIT 10;
```

**Comment by leopedrassoli** [comment]
Hi @paveltiunov , a few updates:
- The schema is correct, because I’ve tested it on Redshift and is working as expected, so it seems to be a problema with Athena Driver.
- It only occurs when I’m trying to manipulate dimensions from another cube because it may contain _null_ values. If I add _where cardColumn2 is not null_ into the query, it works as expected.
- Maybe using coalesce function in cube schema can solve this problem with null vale’s but I’ve made a few tests in Athena driver and this line fixed the problem in ***lazyRowIterator** function:

Old:
`fields[c.Name] = (_a = row.Data) === null || _a === void 0 ? void 0 : _a[j].VarCharValue;`

Fix:
`fields[c.Name] = (_a = row.Data) === null || _a === void 0 || _a[j]['VarCharValue'] == undefined ? null : _a[j].VarCharValue;`

**Comment by darapuk** [comment]
Seeing the same issue when using the Athena connector. Filtering fields for not empty/null does seem to fix the issue.

Could reproduce this with Metabase as well as Superset.
