### ISSUE TITLE
Validate Cube.js schemas via the cli

### ISSUE THREAD

**Issue by tromika** [cube-js/cube#597]
**Problem to solve**

Currently, we're following the [Gitlab flow](https://docs.gitlab.com/ee/topics/gitlab_flow.html) during the development of Cube.js cubes.
Even with a local dev environment may happen that we left some typos or other issues in the schema files. These issues ending up with a broken cube that we realize in the prod environment after merging a feature branch to the master branch. We would like to introduce a CI/CD pipeline internally to be able to test the schema before we merge it into the master. Currently, I don't know how we could validate our schemas with ease and programmatically. 

**Proposal**
[There is no option in the CLI](https://cube.dev/docs/reference) currently to do something like this but I guess it would be great to have a `validate` command to do so.

As I see Cube.js is using @hapi/joi for schema validation and there is a [cube validator ](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/compiler/CubeValidator.js) and a [cube evaluator](https://github.com/cube-js/cube.js/blob/master/packages/cubejs-schema-compiler/compiler/CubeEvaluator.js) under the cubejs-schema-compiler that could be used.

**Comment by paveltiunov** [comment]
@tromika Hey Tamas! Thanks for posting this one! Yeah I think it's good idea to provide such API. However in order to check schema we'd need to compile it and it requires some tenant environment. Do you use multitenant or single tenant environment?

**Comment by tromika** [comment]
@paveltiunov we have a single-tenant environment so that's why I was not really familiar in details with https://cube.dev/docs/multitenancy-setup. After checking, I see it can be difficult to support it broadly with different setups.

**Comment by hhaidar** [comment]
@tromika this might not be exactly what you're looking for but our company has been building a testing framework to catch issues like this and a bit more. We created a tool  called [flan](https://github.com/sdelements/flan) to rapidly load/save snapshots of different sample databases and then run some jest tests against them. I know some other people had concerns about things like the order of joins or switching between versions and something like this should help alleviate a lot of that.

Here's a brief example but I'd happy to provide more details if there's interest:

```
flan fetch cube-query-db-smoke@1.1.3
flan load cube-query-db-smoke@1.1.3
```

```javascript
import cubejs from "@cubejs-client/core";

const cubejsApi = cubejs(process.env.CUBEJS_TEST_TOKEN, {
  apiUrl: process.env.CUBEJS_TEST_API_URL
});

it("Returns the total number of projects", async () => {
  const resultSet = await cubejsApi.load({
    measures: ["Project.count"],
  });

  expect(resultSet.rawData()[0]).toEqual(
    expect.objectContaining({
      "Project.count": "5",
    })
  );
});

it("Returns Project Status Report with regulation filter", async () => {
  const resultSet = await cubejsApi.load({
    dimensions: [
      "Application.id",
      "Application.name",
      "Project.id",
      "Project.name",
      "Project.isRelease",
      "RiskPolicy.name",
      "Project.isCompliant",
    ],
    measures: ["Task.completeCount", "Task.incompleteCount", "Task.naCount"],
    order: [
      ["Task.completeCount", "desc"],
      ["Project.id", "asc"],
    ],
    filters: [
      {
        member: "Regulation.name",
        operator: "contains",
        values: ["TEST-REG"],
      },
    ],
  });

  expect(resultSet.rawData()).toEqual([
    {
      "Application.id": 1,
      "Application.name": "APP1",
      "Project.id": 9,
      "Project.name": "PROJ4",
      "Project.isRelease": false,
      "RiskPolicy.name": "On-Boarding Policy",
      "Project.isCompliant": null,
      "Task.completeCount": "0",
      "Task.incompleteCount": "23",
      "Task.naCount": "0",
    },
  ]);
```
