### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by NikKomarov** [cube-js/cube#6059]
**Problem**

I want to log query errors and cannot figure out where I should catch them.
For example query text logging can be made using queryRewrite, because this method is a part of request pipeline and is called for every request. What is the best place in requests pipeline for catching errors (e.g. database erros, request validation errors and so on)?

**Comment by paveltiunov** [comment]
@NikKomarov I guess you want to use `CUBEJS_LOG_LEVEL=trace`https://cube.dev/docs/reference/environment-variables#cubejs-log-level. This is the most verbose level and provides all error information on all levels during query execution.
