### ISSUE TITLE
How to calculate date difference between two timestamp fields?

### ISSUE THREAD

**Issue by atom36942123** [cube-js/cube#6112]
I have two columns by the name created_at, and updated_at.

I want to have a day difference dimension of two dates.

**Comment by Rajatkanwar7** [comment]
timestamp format for date and time: YYYY-MM-DD HH:MI:SS
Timestamp format for date: YYYY-MM-DD
Program:


SELECT
  created_at,
  updated_at,
  TIMESTAMPDIFF(DAY, created_at, updated_at) AS difference
FROM table_name;
