### ISSUE TITLE
How can I generate a schema for jsonb objects in postgres databases automatically?

### ISSUE THREAD

**Issue by luismoriguerra** [cube-js/cube#6134]
**Problem**
How can I generate  schema for jsonb objects in postgres databases automatically?

is it any way  to generate custom schemas for a selected table that has a jsonb column ?

let say I have a table with 2 columns `id` and `metadata` and metadata has JSON as value
I would like to be able to go deep into the json and generate dimensions based on json properties and nested properties

**Related Cube.js schema**
```javascript
 dimensions: {
    user_name: {
      sql: `${CUBE}.metadata->'actor'->>'login'`,
      type: `string`
    },
    repository: {
      sql: `${CUBE}.metadata->'repo'->>'name'`,
      type: `string`
    },
    createdAt: {
      sql: `${CUBE}.metadata->>'created_at'`,
      type: `time`
    },
```
I was reviewing the cubejs documentation but I wasn't able to find any doc about it.

**Comment by paveltiunov** [comment]
@luismoriguerra I'd suggest to look into https://cube.dev/docs/schema/advanced/dynamic-schema-creation#dynamic-schema-creation.
