### ISSUE TITLE
rewriteQuery for filter pushup/pushdown doesn't work

### ISSUE THREAD

**Issue by ephor** [cube-js/cube#6168]
**Describe the bug**
What is the main purpose of rewriteQueries? Based on the documentation, I expect that it will optimize the query and theoretically remove duplicate conditions, but it does not. Maybe I do not understand correctly why this thing is needed? because there is only one sentence about this in the documentation. I read about proposes to use this option here - https://github.com/cube-js/cube.js/issues/3477 but it does not work in both configuration and cubes.

**To Reproduce**
1. Go to Playground
2. Select filter by gender
3. Open Sql tab
4. See SELECT with two WHERE

**Expected behavior**
```sql
SELECT
    count(`patient`.id) `patient__count`
    FROM ( SELECT * FROM ehr."Patient" WHERE gender = 'male' ) AS `patient`
LIMIT 10000 FORMAT JSON
```

**SQL Result**

#### Sql in Playground

```sql
SELECT
  count(`patient`.id) `patient__count`
  FROM ( SELECT * FROM ehr."Patient" WHERE gender = ?) AS `patient` WHERE (`patient`.gender = ?)
LIMIT 10000
```

#### Sql in Clickhouse

```sql
SELECT
    count(`patient`.id) `patient__count`
    FROM ( SELECT * FROM ehr."Patient" WHERE gender = 'male' ) AS `patient` WHERE (`patient`.gender = 'male') 
LIMIT 10000 FORMAT JSON
```

**Minimally reproducible Cube Schema**
```javascript
cube(`Patient`, {
      sql: `SELECT * FROM ehr."Patient" WHERE ${FILTER_PARAMS.Patient.gender.filter("gender")}`,
      measures: {
        count: {
          type: `count`
        }
      },
      joins: {},
      dimensions: {
        id: {
          sql: `id`,
          type: `string`,
          primaryKey: true
        },
        gender: {
          sql: `gender`,
          type: `string`
        }
      }
    });
```

**Version:**
0.31.32

**Additional context**
Clickhouse DB

**Comment by paveltiunov** [comment]
Closing in favor of #3477. I mentioned `rewriteQuery` is the expected approach to solve this issue but it hasn't been implemented yet.
