### ISSUE TITLE
Refresh Scheduler Error in AWS

### ISSUE THREAD

**Issue by palaforcade** [cube-js/cube#6176]
**Problem**

We have a CubeJS process running within an AWS ECS instance and are experiencing slowness and the following error : 

`{"message":"Refresh Scheduler Interval Error","error":"Previous interval #2 was not finished with 60000 interval"}`

From which process is the error coming from ? (cubestore_router, cubestore_worker, main cube process, etc...)
We already increased the instance size, but it doesn't seem to be effective. Maybe we should replicate one of the above processes to distribute the load. 

Please note that we are still using Redis in an elasticache cluster. 

Thanks a lot for the help !

**Comment by paveltiunov** [comment]
@palaforcade It might indicate you have a lot of tenants, a lot of pre-aggregations to refresh, or both. If you're using multi-tenancy you'd need to deploy a Cube cluster per reduced set of tenants so there will be multiple refresh workers which will work only on a subset of your tenants. If you're using Cube Cloud you can use a multi-cluster feature that is automatically doing this for you.
