### ISSUE TITLE
jsonwebtoken unrestricted key type could lead to legacy keys usage

### ISSUE THREAD

**Issue by DhanushNehru** [cube-js/cube#6178]
When configuring dependabot alerts for our repository we are running into an issue where the jsonwebtoken needs to be upgraded.

Possible to upgrade the jsonwebtoken used by cube with version greater than 9.0.0 would resolve this issue. Can it be upgraded by the cube team ?

<img width="1160" alt="Screenshot 2023-02-20 at 5 50 57 PM" src="https://user-images.githubusercontent.com/22955675/220105702-36b0ec04-c128-4849-a4b9-e1f99c7814d0.png">

**Comment by paveltiunov** [comment]
@DhanushNehru Feel free to provide PR for that. We also have separate enterprise images, which have different set of dependencies and update cadence. Please contact us if you'd like to consider this option https://cube.dev/contact.

**Comment by DhanushNehru** [comment]
Hi @paveltiunov I have provided a PR, can you please check #6183

**Comment by DhanushNehru** [comment]
Hi @paveltiunov I have provided a PR, can you please check https://github.com/cube-js/cube.js/pull/6183

**Comment by DhanushNehru** [comment]
Hi @paveltiunov I have provided a PR, can you please check the updated one https://github.com/cube-js/cube/pull/6183

**Comment by DhanushNehru** [comment]
Hi @paveltiunov I have provided a PR, can you please check the updated one https://github.com/cube-js/cube/pull/6527
