### ISSUE TITLE
Making a generic measure

### ISSUE THREAD

**Issue by Dekel-Eli** [cube-js/cube#6188]
**Problem**

Hey, In my data base for each row there is a column label. I am trying to make a dynamic measure that can count according to a certain label, and show each count in as a different measure (different column when presenting in a table). Is there an efficient way to make this generic measure? (without defining for each label with filter: label = 'x')

**Related Cube.js schema**
cubes:
  - name: AmyResult
    sql: SELECT * FROM public."AmyResult"
    measures:
// example of one measure
      - name: invoice_count
        type: count
        filters:
          - sql: "{label} = 'INVOICE"

dimensions:
...
      - name: label
        sql: label
        type: string
...
    dataSource: default

**Comment by igorlukanin** [comment]
Hey @Dekel-Eli 👋 

I think here's what would work for you:
1. Define a simple `count` measure without any filters.
2. To get counts for every value of the `label` dimension, include the `count` measure and the `label` dimension into the query.
3. To get a count for a particular value of the `label` dimension, include the `count` measure and a [filter](https://cube.dev/docs/query-format/#query-properties) for that value of the `label` dimension.

I hope it helps.
