### ISSUE TITLE
Document the streaming mode for the SQL API

### ISSUE THREAD

**Issue by electroheadfx** [cube-js/cube#6209]
In the cubeJS api I don't see any cursor method, only offset. I there something similar that cursor ?

https://mithle.sh/the-pagination-dilemma-offset-vs-cursor-part-2/

**Comment by paveltiunov** [comment]
@electroheadfx Streaming queries support SQL API is WIP. Do you want to use SQL or REST API with cursor?

**Comment by electroheadfx** [comment]
Hey, thanks for answer, REST API is fine, maybe SQL too.

**Comment by paveltiunov** [comment]
@electroheadfx You can try it out using `CUBESQL_STREAM_MODE=true` for SQL API.

**Comment by igorlukanin** [comment]
Resolved by https://github.com/cube-js/cube/pull/8593.

- [Row limit](https://cube.dev/docs/product/apis-integrations/queries#row-limit)
- [Streaming mode](https://cube.dev/docs/product/apis-integrations/sql-api#streaming) in the SQL API
