### ISSUE TITLE
Why does Cube.js respond with "dateRange" to a Retool API Request which has "compareDateRange" specified in the query?

### ISSUE THREAD

**Issue by singerdaniel** [cube-js/cube#6231]
**Problem**

I am trying to compare a measure (totalPrice) across two different time periods in a Retool App. When generating the query in Retool I have made use of the "compareDateRange" function where two different date ranges have been outlined in the required format. Within Retool I have also specified the 'queryType' to 'multi'. This was done in-line with advice seen in https://github.com/cube-js/cube.js/issues/461. However, the response from the API request from this query returns the "dateRange" instead of "compareDateRange", as specified. 

**Query Image**

<img width="1002" alt="Screenshot 2023-03-02 at 11 13 22" src="https://user-images.githubusercontent.com/126763253/222384231-87ad3e55-1782-4022-bb21-2857ad19272d.png">

**Cube.js API Response Snippet**

<img width="387" alt="Screenshot 2023-03-02 at 11 00 38" src="https://user-images.githubusercontent.com/126763253/222384326-870b2818-9bb5-4cfd-800e-fe0d82c76e5e.png">

As can be seen above, the response only return the first date range specified in the "compareDateRange". I am not sure why this is the case. Wondering if I need to configure the deployment in a way to allow for "compareDateRange" to be used? 

Any advice is much appreciated. Please let me know if I have left out any relevant information :)

**Comment by igorlukanin** [comment]
@singerdaniel Is this issue still relevant? Please feel free to reopen if so

**Comment by BrevAlessioMk** [comment]
I am facing the same problem, was there a solution found?
