### ISSUE TITLE
No connection could be made when connecting to Cube SQL API after few hours

### ISSUE THREAD

**Issue by gojumprope** [cube-js/cube#6252]
**Describe the bug**
Cube SQL API down but Rest API still can works, after restart cube docker container then everything back to normal, but after certain of time, Cube SQL API down again, where can we check the postgres log or other logs to diagnose with this issue?

**To Reproduce**
1. Build CubeJS in Docker with SQL API
2. PowerBI connect CubeJS with no issue
3. After few hours/few days (uncertain)
5. PowerBI (or other database tools) unable to connect to CubeJS (No connection could be made)
6. CubeJS Rest API still works but posgres not working
7. psql -h localhost -p 5432
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

**Expected behavior**
Postgres should not closed the connection, any logs we can check to prevent this issue happen again?

**Screenshots**
PowerBI:
![image](https://user-images.githubusercontent.com/38604290/223299788-904b498b-8490-40f9-b701-f06f673ba878.png)

**Version:**
cubejs:latest

**Comment by ovr** [comment]
Hello @gojumprope,

> where can we check the postgres log or other logs to diagnose with this issue?

It uses the same STDOUT as Cube.

Do you see any kind of errors in the logs?

Thanks

**Comment by gojumprope** [comment]
Hi @ovr, sorry for the late reply.

I didn't see any error logs in the docker container. This issue appears randomly, currently don't have any issue since my last restart. I will monitor it for few more days first and see if the issue still occurs or not.

**Comment by gojumprope** [comment]
Hi @ovr, the issue still occurs after few days, when I go in the container and check the tcp listening, it does not listen to postgres port anymore.
![image](https://user-images.githubusercontent.com/38604290/224584420-47eb2632-1f86-41c3-8088-d06eec0d0bd1.png)

this is my docker compose yml file
`services:
  cube_api:
    restart: always
    image: cubejs:latest
    ports:
      - 4000:4000
      - 5432:5432
    environment:
      - CUBEJS_DEV_MODE=false
      - CUBEJS_PG_SQL_PORT=5432
      - CUBEJS_SQL_USER=postgres
      - CUBEJS_SQL_PASSWORD=password
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - cubestore_worker_1
      - cubestore_worker_2
      - cube_refresh_worker
      - redis

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:latest
    environment:
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - .:/cube/conf

  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore/router:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_1:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_2:/cube/data
    depends_on:
      - cubestore_router

  redis:
    restart: always
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
`

**Comment by Raven888888** [comment]
Hi @ovr , I am facing the exact same issue. I have these in the container logs:

```
warning You are using old Cube.js packages (^0.29.15) with new Docker image (^0.32.3)
ðŸ”— Cube SQL (pg) is listening on 0.0.0.0:5432
ðŸš€ Cube API server (0.32.3) is listening on 4000
...
... (query stuffs, deliberately hidden)
...
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2023-3-15 00:00:00, _f: undefined, _strict: undefined, _locale: [object Object]
Error:
    at Function.createFromInputFallback (/cube/node_modules/moment/moment.js:319:25)
    at configFromString (/cube/node_modules/moment/moment.js:2536:19)
    at configFromInput (/cube/node_modules/moment/moment.js:2977:13)
    at prepareConfig (/cube/node_modules/moment/moment.js:2960:13)
    at createFromConfig (/cube/node_modules/moment/moment.js:2927:44)
    at createLocalOrUTC (/cube/node_modules/moment/moment.js:3021:16)
    at Function.createUTC [as utc] (/cube/node_modules/moment/moment.js:105:16)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/query.js:226:22
    at Array.map (<anonymous>)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/query.js:223:43
    at Array.map (<anonymous>)
    at normalizeQuery (/cube/node_modules/@cubejs-backend/api-gateway/src/query.js:211:50)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1312:27
    at Array.map (<anonymous>)
    at ApiGateway.getNormalizedQueries (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1309:15)
    at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1709:20)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:101:13
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', /__w/cube.js/cube.js/rust/cubesql/cubesql/src/sql/postgres/service.rs:63:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CubeError { message: "Unexpected panic. Reason: called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: \"Transport endpoint is not connected\" }", cause: Internal(None), backtrace: Some(<disabled>) }', src/lib.rs:162:51
```

I suspect something to do with the thread panicked causing sql api port unable to use anymore, but rest api still OK. Any idea?

**Comment by ovr** [comment]
Hello @Raven888888 ,

What OS & Linux kernel do you use on the host machine?

Thanks

**Comment by Raven888888** [comment]
@ovr 
Ubuntu 20.04, 5.4.0-124-generic

**Comment by ovr** [comment]
@Raven888888

> Just wondering, if CUBEJS_DEV_MODE=false but refresh worker container is not running, will it eventually cause the above error?

It cannot. 

> Also, I tried setting RUST_BACKTRACE=1 in cube_api container, but that makes connecting psql client to its SQL API port extremely slow, can take up to 5 minutes just to establish connection. Without the setting, connecting usually takes a few seconds only.

Strange, I will take a look.

**Comment by ovr** [comment]
@Raven888888 @gojumprope

I've prepared a fix that should fix the crash related to the pg server, Could you give a try with [v0.32.8](https://github.com/cube-js/cube.js/releases/tag/v0.32.8)?

Thanks

**Comment by gojumprope** [comment]
Hi @ovr , thanks for the update!

I will try [v0.32.8](https://github.com/cube-js/cube.js/releases/tag/v0.32.8) and monitor few days to see if the issue still occurs, once the issue has solved, I will close this issue.
