### ISSUE TITLE
Dashboard App is not running/refuses to start

### ISSUE THREAD

**Issue by themediapot** [cube-js/cube#6264]
**Describe the bug**
Cube.js playground was set up via Docker Compose.  Postgres connection to my instance was also established.  Attempting to start Dashboard App to no avail.

**To Reproduce**
1. Go to cube.js playground via localhost:4000
2. Click on Dashboard App
3. It reports that Dashbard App is not running, and offers a Start dashboard app button.
4. Click on Start dashboard app.
5. After several minutes of trying, it failed.
6. Console logs shows:

n02cb  | Warning. There is no cube.js file. Continue with environment variables
n02cb  | 🔥 Cube Store (0.32.3) is assigned to 3030 port.
n02cb  | Warning. Option apiSecret is required in dev mode. Cube.js has generated it as b1f754ea96d00e1043d97059937c6324
n02cb  | 🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
n02cb  | 🦅 Dev environment available at http://localhost:4000
n02cb  | 🚀 Cube API server (0.32.3) is listening on 4000
n02cb  | 2023-03-09 02:53:34,910 INFO  [cubestored] <pid:18> Cube Store version 0.32.3
n02cb  | 2023-03-09 02:53:34,966 INFO  [cubestore::http::status] <pid:18> Serving status probes at 0.0.0.0:3031
n02cb  | 2023-03-09 02:53:34,967 INFO  [cubestore::metastore::rocks_fs] <pid:18> Using existing metastore in /cube/conf/.cubestore/data/metastore
n02cb  | 2023-03-09 02:53:35,079 INFO  [cubestore::mysql] <pid:18> MySQL port open on 0.0.0.0:13306
n02cb  | 2023-03-09 02:53:35,079 INFO  [cubestore::http] <pid:18> Http Server is listening on 0.0.0.0:3030
n02cb  | Dashboard react-app failed with exit code 254

7. Also tried running 'npm run start' within the container and it showed this:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /cube/conf/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/cube/conf/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-09T03_01_03_420Z-debug-0.log

8. /root/.npm/_logs/2023-03-09T03_01_03_420Z-debug-0.log shown below in Additional context.

**Expected behavior**
Dashboard app starts and shows on screen.

**Version:**
[e.g. 0.32.3]

**Additional context**

0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.19.3
2 info using node@v16.19.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/cube/conf/.npmrc Completed in 0ms
10 timing config:load:project Completed in 32ms
11 timing config:load:file:/root/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 47ms
19 timing npm:load:configload Completed in 48ms
20 timing npm:load:mkdirpcache Completed in 2ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm run start
23 verbose argv "run" "start"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 4ms
26 timing npm:load:display Completed in 6ms
27 verbose logfile logs-max:10 dir:/root/.npm/_logs
28 verbose logfile /root/.npm/_logs/2023-03-09T03_01_03_420Z-debug-0.log
29 timing npm:load:logFile Completed in 10ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 70ms
33 silly logfile done cleaning log files
34 timing command:run Completed in 22ms
35 verbose stack Error: ENOENT: no such file or directory, open '/cube/conf/package.json'
36 verbose cwd /cube/conf/dashboard-app
37 verbose Linux 6.2.1-arch1-1
38 verbose node v16.19.1
39 verbose npm  v8.19.3
40 error code ENOENT
41 error syscall open
42 error path /cube/conf/package.json
43 error errno -2
44 error enoent ENOENT: no such file or directory, open '/cube/conf/package.json'
45 error enoent This is related to npm not being able to find a file.
45 error enoent
46 verbose exit -2
47 timing npm Completed in 116ms
48 verbose code -2
49 error A complete log of this run can be found in:
49 error     /root/.npm/_logs/2023-03-09T03_01_03_420Z-debug-0.log

**Comment by paveltiunov** [comment]
@themediapot Dashboard in the playground has been deprecated and removed.
