### ISSUE TITLE
Documentation on how to use druid

### ISSUE THREAD

**Issue by omrihaber** [cube-js/cube#6278]
**Problem**

I want to try and use druid i tried searching for examples but couldn't find something concrete.
specifically i want to use histogram/approx_histograms with druid. but if there is any documentation examples those would be appreciated.

I also tried searching about the cube.js drivers for these data sources and they seem to be community supported/archived. are these still supported somehow or i should avoid them? do i have any other options?(someway to get data by custom code?)

**Comment by igorlukanin** [comment]
@omrihaber Connectivity to Druid is indeed enabled by a community-supported driver: https://cube.dev/docs/product/configuration/data-sources/druid

I don't have much experience with it myself but I believe other Cube community members might have some—it's worth it to ask in slack.cube.dev!

Please feel free to reopen the issue if you'd like to follow up
