### ISSUE TITLE
Refresh worker and first cache update

### ISSUE THREAD

**Issue by cndev123** [cube-js/cube#6304]
Is it correct that when using a refresh worker only the first cube query of a kind will be executed against the DB or pre-agg tables?

e.g.:

1. system with refresh worker and 1min refresh is in place
2. first query comes in
3. in-memory cache is empty
4. query is executed against db or pre-agg tables
5. cache is filled
6. result is returned for query
7. 1 min later
8. refresh worker updates cache
9. 30sec later
10. 2 query comes in
11. in-memory cache is valid, result from cache is returned

In other words, the refresh worker will ensure that the cache for the query stays up-to-date forever and, therefore, there is no need for a cached cube query to wait for execution against db or pre-agg tables after the first time the cube query was executed. 

This would also mean that pre-agg would only make the very first cube query execution of a kind faster because afterwards a cube query of the same kind is always answered from in-memory cache. 

This would also mean, I can speed up my app by executing every cube query right after a redeployment once to fill all the caches. 

If I follow this would pre-agg still give me any benefit for my cube queries?

**Comment by igorlukanin** [comment]
Hey @cndev123 👋 

Thanks for this very elaborate question! Let me clarify a few things here.

> In other words, the refresh worker will ensure that the cache for the query stays up-to-date forever and, therefore, there is no need for a cached cube query to wait for execution against db or pre-agg tables after the first time the cube query was executed.

The duty of a refresh worker is to keep _pre-aggregations_ up-to-date. So, with a refresh worker in place, pre-aggregations defined and built, queries will use pre-aggregations (if they match) and never need to wait for execution against the database.

> This would also mean that pre-agg would only make the very first cube query execution of a kind faster because afterwards a cube query of the same kind is always answered from in-memory cache.

The pre-aggregation will make all of your query executions faster.

> This would also mean, I can speed up my app by executing every cube query right after a redeployment once to fill all the caches.

What you need to ensure after redeployment is that all pre-aggregations are built. One way to do so is to run a set of queries that will trigger the build of all pre-aggregations you have defined. A single query per pre-aggregation is enough.

In Cube Cloud, there's an option only to make a new deployment available to users once all pre-aggregations have been fully built. This is called "pre-aggregations warm-up" and ensures all queries have minimal latency possible.

> If I follow this would pre-agg still give me any benefit for my cube queries?

Pre-aggregations give you all the benefits here. Please use them.

I hope it helps!

**Comment by paveltiunov** [comment]
@cndev123 Refresh worker just invalidates the cache but not populates it. In-memory cache is lazily populated when Cube is queried. Only pre-aggregations are eagerly populated by refresh workers.
