### ISSUE TITLE
Cube Store without pre-aggregation required?

### ISSUE THREAD

**Issue by cndev123** [cube-js/cube#6305]
Is a separate cube store instance required for setup without pre-aggregations?

I assume based on this https://cube.dev/docs/releases/v0-32#breaking-changes-and-deprecations-breaking-changes it is now.

Would it then be enough to just run one cube store instance without a cube store router in production?

This page here https://cube.dev/docs/caching/running-in-production#scaling indicates that mulliple cube store instances are required when using partitions but partitions are an pre-agg feature, or not? 

So if I do not use pre-agg, do I need to use cube store at all and if so, do I need more than one instance in production?

**Comment by paveltiunov** [comment]
@cndev123 Starting 0.32 Cube Store is required to run Cube in production however you can run it without workers for now if you don't use pre-aggregations.

**Comment by paveltiunov** [comment]
@cndev123 
1. You need only a Cube Store router to run Cube in production.
2. See 1.
3. Yes however this is only available in Cube Cloud. In Cube Cloud multiple Cube Store routers can be run for one deployment.
