### ISSUE TITLE
 Cannot Connect Cube.js with SQL API 

### ISSUE THREAD

**Issue by akhlaq-ha** [cube-js/cube#6334]
**Problem**

i have a self hosted cube which i can successfully connect via REST API. 
But when i try to connect via SQL API it gives foloowing error: 
![image](https://user-images.githubusercontent.com/77789142/226915205-d9326676-b3ee-49c6-a81b-e0b365a04aaf.png)

**Related Cube.js env**
```
CUBEJS_DB_BQ_PROJECT_ID=plexus-336107
CUBEJS_DB_BQ_KEY_FILE=big-query-key.json
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=bigquery
CUBEJS_API_SECRET=aaaa
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_PG_SQL_PORT=5432
CUBEJS_SQL_USER=postgres
CUBEJS_SQL_PASSWORD=password

```

Let me know what i am doing wrong. Thanks

**Comment by giftcash-dakota** [comment]
Looking at your env file and your error message, you may have used the wrong user name when connecting to the SQL API. In your case, the username should be `postgres`, and the password should be `password`.

**Comment by akhlaq-ha** [comment]
@giftcash-dakota apologies for the confusion i must've pasted old config as i was testing with different usernames

`CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=bigquery
CUBEJS_API_SECRET=aaaa
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_PG_SQL_PORT=5432
CUBEJS_SQL_USER=myusername
CUBEJS_SQL_PASSWORD=password
`
that is what i am using right now

**Comment by akhlaq-ha** [comment]
so I was able to solve it. i was using 20 version of cube JS which showed no log regarding Cube SQL ( pg ). when I upgraded to 32 version I showed that port was in use. changing port for postrgres resolved the issue.
