### ISSUE TITLE
Publish more images for rust-cross targets

### ISSUE THREAD

**Issue by mcandre** [cube-js/cube#6355]
**Is your feature request related to a problem? Please describe.**

Hi,

I rather enjoy your Docker images for rust-cross on Docker Hub:

https://hub.docker.com/r/cubejs/rust-cross/tags

This makes it easier for me to port my Rust applications to more platforms.

However, I noticed a few gaps in the targets supported by these images.

**Describe the solution you'd like**

Can we please push a cubejs/rust-cross image for more Windows target triples as well?

* aarch64-pc-windows-msvc
* i586-pc-windows-msvc
* i686-pc-windows-msvc
* etc.

**Describe alternatives you've considered**

Skipping Windows ARM support for my users and leaving them out in the cold :/

**Comment by ovr** [comment]
Hello @mcandre ,

There are no plans to support that because we build/use these images as a workaround for some issues in `cross-rs/cross`.

https://github.com/cross-rs/cross

Did you see this repository? This project aims to do that.

Thanks
