### ISSUE TITLE
All measure types get reported as number type when using views

### ISSUE THREAD

**Issue by DPHonys** [cube-js/cube#6356]
**Describe the bug**
When using new [measure types](https://cube.dev/docs/schema/reference/types-and-formats#measure-types) (string, time, boolean) from version [v0.31.28](https://github.com/cube-js/cube/releases/tag/v0.31.28) they all get reported as a number type IF YOU ARE USING [VIEWS](https://cube.dev/docs/schema/reference/view). If you are using simple [cube](https://cube.dev/docs/schema/reference/cube) it seems to work correctly. So probably the view rewrites the type of the measure.

Affected by this is a playground and probably all packages for frontend integration of cube. Tested playground and Vue package.

**To Reproduce**
1. Register measure with string type in your schema and reference it in view
2. Open playground
3. Try to create a filter
- if you create a filter on the cube you gonna see the correct operators
- if you gonna create a filter on a measure that is referenced in view you gonna see operators for number type (e.g. 'gte',...), not string type (e.g. 'contains',...)

**Expected behavior**
If you have a measure with the string type, I would expect it to be reported as string type in the meta-object even when if it is through the view. So playground shows the correct operators for the type and frontend integration can also see its type to show the correct operators.

**Screenshots**
Filter created on cube file
![correct operators (cube file)](https://user-images.githubusercontent.com/38984391/228205651-b09c4b47-c301-4d1b-8e74-fff5135d1281.png)

Filter created on view file that references measure from cube file
![wrong operators (view file)](https://user-images.githubusercontent.com/38984391/228205684-9aa6eaa5-be69-42e9-ad32-217973983af8.png)

**Minimally reproducible Cube Schema**
Task.js
```javascript
cube(`Task`, {
  sql: `SELECT * FROM public.task`,
  
  measures: {
    count: {
      type: `count`,
    },

    high_or_low: {
      type: `string`,
      sql: `CASE WHEN ${CUBE.count} > 100 THEN 'high' ELSE 'low' END`,
    },
  },
  
  dataSource: `default`
});
```

TaskView.js
```javascript
view(`TaskView`, {
  description: `Task view`,

  includes: [
    Task.count,
    Task.high_or_low
  ],
});
```

**Version:**
v0.32.16

**Comment by DPHonys** [comment]
Hi, took me a bit before I got to test it... the issues seem to persist even when updating to the newest backend (v0.32.21) and frontend packages (v0.32.17)... By releases, it seems like it was already added into the [v0.32.18](https://github.com/cube-js/cube/releases/tag/v0.32.18).

I don't know If I wasn't clear enough, but I will try to explain the problem again.

The problem is when you include measures in the view object with `includes: []` the measure gets its type rewritten (or it seems like it). So the playground and frontend packages for cube integration get the wrong type (instead of `string` it gets `number`).

This time screenshot from Vue.js devtools.
![image](https://user-images.githubusercontent.com/38984391/230745831-cd8f8f80-e4eb-4aa1-ba10-863b6012a0c4.png)
The object with index 1 is measure straight from the cube object in the schema (Task.js) and the object with index 3 is measure included in the view object (TaskView.js). But the `type` properties are different and I would expect they would be the same.

Maybe I've missed something so correct me if possible. I will gladly try to elaborate more on the issue if needed. @paveltiunov

**Comment by DPHonys** [comment]
Hi @paveltiunov, any updates on this? Also, I've found maybe a related issue to the views [6778](https://github.com/cube-js/cube/issues/6778)

**Comment by c-kirkeby** [comment]
Possibly related, the `format` value is seemingly also `undefined` for each field on a view and the `title` field seems to be ignored.

**Comment by igorlukanin** [comment]
@c-kirkeby Could you please check with the latest version? There were some [relevant changes](https://cube.dev/blog/cube-core-v0-35-updates-to-data-modeling-and-data-sources#title-and-format-for-view-members) recently.

These changes does not address the original data type bug but it might be addressed soon

**Comment by igorlukanin** [comment]
@DPHonys I have just checked on Cube v0.36.7 (latest) and it looks like this issue has been resolved.

Here's the output of the `/meta` call that I have just ran:

```json
{
  "cubes": [
    {
      "name": "Task",
      "type": "cube",
      "title": "Task",
      "isVisible": true,
      "public": true,
      "measures": [
        {
          "name": "Task.count",
          "title": "Task Count",
          "shortTitle": "Count",
          "cumulativeTotal": false,
          "cumulative": false,
          "type": "number",
          "aggType": "count",
          "drillMembers": [],
          "drillMembersGrouped": {
            "measures": [],
            "dimensions": []
          },
          "isVisible": true,
          "public": true
        },
        {
          "name": "Task.high_or_low",
          "title": "Task High or Low",
          "shortTitle": "High or Low",
          "cumulativeTotal": false,
          "cumulative": false,
          "type": "string",
          "aggType": "string",
          "drillMembers": [],
          "drillMembersGrouped": {
            "measures": [],
            "dimensions": []
          },
          "isVisible": true,
          "public": true
        }
      ],
      "dimensions": [],
      "segments": [],
      "hierarchies": []
    },
    {
      "name": "TaskView",
      "type": "view",
      "title": "Task View",
      "isVisible": true,
      "public": true,
      "description": "Task view",
      "measures": [
        {
          "name": "TaskView.count",
          "title": "Task View Count",
          "shortTitle": "Count",
          "cumulativeTotal": false,
          "cumulative": false,
          "type": "number",
          "aggType": "count",
          "drillMembers": [],
          "drillMembersGrouped": {
            "measures": [],
            "dimensions": []
          },
          "isVisible": true,
          "public": true
        },
        {
          "name": "TaskView.high_or_low",
          "title": "Task View High or Low",
          "shortTitle": "High or Low",
          "cumulativeTotal": false,
          "cumulative": false,
          "type": "string",
          "aggType": "string",
          "drillMembers": [],
          "drillMembersGrouped": {
            "measures": [],
            "dimensions": []
          },
          "isVisible": true,
          "public": true
        }
      ],
      "dimensions": [],
      "segments": [],
      "hierarchies": []
    }
  ]
}
```

And Playground also correctly sees that `TaskView.high_or_low` is of type `string`:

<img width="1392" alt="Screenshot 2024-10-09 at 01 28 05" src="https://github.com/user-attachments/assets/11cb7f49-9882-44c6-ac5d-fe4183fb6e65">
