### ISSUE TITLE
Missing Information on Dimension Filters In Docs

### ISSUE THREAD

**Issue by pmurraybne** [cube-js/cube#6363]
**Problem**

In the docs, Segments (https://cube.dev/docs/schema/reference/segments) mentions Dimension Filters and demonstrates an example of the 'filter' parameter (assuming against the Dimension although this is not clear)

However the 'filter' parameter is not listed in the Dimensions page (https://cube.dev/docs/schema/reference/dimensions) as a possible parameter on Dimension

**Solution**
Update the Dimensions page to include information on the 'filter' parameter

**Comment by igorlukanin** [comment]
@pmurraybne Thanks for the heads-up! Actually, the filtering on a dimension or a segment can be done by specifying a filter or a segment in a query. Please see https://cube.dev/docs/query-format#query-properties
