### ISSUE TITLE
DriverFactory doesn't work well dynamically

### ISSUE THREAD

**Issue by gmmeyer** [cube-js/cube#6374]
**Describe the bug**
I found a fairly serious bug in the latest version. I'm using the driver factory and trying to create the connection based off the security context, but the security context doesn't ever change even when I have sent a request with a different context. I can confirm it's different because while the driver factory doesn't see it as different, the query rewrite does. I set it up just like this is described here: https://cube.dev/docs/config/multitenancy#multiple-schema-and-drivers

**To Reproduce**

**Expected behavior**
I get the right results back, instead I get the same results back no matter the query parameters

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  UNION ALL
  select 2 as id, 200 as amount, 'new' status
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Version:**
[v0.32.17]

**Additional context**

**Comment by paveltiunov** [comment]
@gmmeyer Could you please share your `cube.js` file?

**Comment by ovr** [comment]
@gmmeyer

Did you define `contextToAppId` / `contextToOrchestratorId`? If you didnt define it, it's an expected behaivour because Cube caches connection per dataSource for each orchestrator.

https://cube.dev/docs/config/multitenancy


Thanks

**Comment by gmmeyer** [comment]
yea I figured it out that I had to define those! Thanks!

**Comment by sadath-12** [comment]
@gmmeyer , @ovr , @paveltiunov . for me there is issue here , user works fine (I get results when entering correct user and not when I dont). But whatever password I enter I get results . Provided I'm using sql api

Here's the cube.js file 

```yaml

module.exports = {
  checkSqlAuth: (req, user_name, password) => { 
          globalSecurityContext = {
                user: user_name,
                password:password
          }
    return {
      password,
      securityContext: globalSecurityContext
    };
  },

  queryRewrite: (query, { securityContext }) => {
    return query;
  },
        // contextToAppId is used as a caching key for various in-memory structures like data model compilation results, connection pool
contextToAppId: ({ securityContext }) => {
    return `${securityContext.user}//${securityContext.password}`;
  },
        // contextToOrchestratorId is used as a caching key for database connections, execution queues and pre-aggregation table caches
contextToOrchestratorId: ({ securityContext }) =>{
    return `${securityContext.user}//${securityContext.password}`
  },

 // preAggregationsSchema: ({ securityContext }) =>{ 
// return `pre_aggregations_${securityContext.user}_${securityContext.password}`
 //},

// scheduledRefreshContexts: async () => {
      //const users = ["admin"];

     // return users.map((id) => { 
      //  return { securityContext: { user: "admin",password:"123" } }
     // })
    //},

driverFactory: ({ securityContext,dataSource }) => {
  console.log("security at driver",securityContext)
  return {
    type: 'trino',
    host: 'host',
    user:securityContext.user,
    password:securityContext.password,
    database: dataSource
  };
}
          
  }
```

**Comment by igorlukanin** [comment]
@sadath-12 Please see the code example in the docs: https://cube.dev/docs/reference/configuration/config#check_sql_auth

I think you need to add an explicit password check there (i.e., `if ...`).
