### ISSUE TITLE
Issue when Joining Data from Multiple Databases

### ISSUE THREAD

**Issue by kpreeth** [cube-js/cube#6386]
We are using Superset as BI tool which connects to BigQuery and Postgres through self hosted Cube(SQL API).

User wants a report(Charts) in Superset that has 5 dimensions and 2 measures from a BigQuery table and another 5 dimensions and 2 measures from a Postgres table.

For this, we created Cubes for tables from BigQuery and Postgres and defined rollup pre-aggregations and rollupJoin pre-aggregation containing all 10 dimensions and 4 measures.

Since Superset supports only single dataset as source for reports, we created a View(view concept in Cube) with all 10 dimensions and 4 measures that was defined in rollupJoin pre-aggregation. We added this View as dataset in Superset and made it as source for report.

When we run this report only with dimensions added, the report executes without any issues. But when any measure is added, report throws error. Based on measure added(i.e. from which database the measure is from) we get one of the below errors

1. Error: Cannot set destination table in jobs with DDL statements

2. Error: To join across data sources use rollupJoin with Cube Store. If rollupJoin is defined, this error indicates it doesn't match the query. Please use Rollup Designer to verify it's definition. 

Please let me know how to resolve this issue.

**Comment by igorlukanin** [comment]
@kpreeth Thanks for filing this. have you tried creating a `rollupJoin` as suggested in the second error message?

**Comment by paveltiunov** [comment]
@kpreeth Your data model and query logs would be helpful here.
