### ISSUE TITLE
TypeCannot read properties of undefined (reading 'dimensions')

### ISSUE THREAD

**Issue by ezequielpozzotromzo** [cube-js/cube#6424]
**Describe the bug**
When doing query rewrite of a dimension to a dimension that is hidden and in a different model, I get a the error:

```
TypeCannot read properties of undefined (reading 'dimensions')

TypeError: Cannot read properties of undefined (reading 'dimensions')
    at /cube/node_modules/@cubejs-backend/api-gateway/src/helpers/prepareAnnotation.ts:36:49
    at Array.map (<anonymous>)
    at prepareAnnotation (/cube/node_modules/@cubejs-backend/api-gateway/src/helpers/prepareAnnotation.ts:70:10)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1521:47
    at Array.map (<anonymous>)
    at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1517:27)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:243:7
```

**To Reproduce**
1. Introduce query for dimension A.A1value
2. See error

**Expected behavior**
The query should return with A1.value instead.

**Minimally reproducible Cube Schema**

```javascript
cube('A', {
  sql: `SELECT 1 AS id, 1 AS a1_id UNION ALL SELECT 2, 1 UNION ALL SELECT 3, 2`,
  joins: {
    A1: {
      relationship: 'hasOne',
      sql: `${CUBE}.a1_id = ${A1}.id`,
    }
  },
  dimensions: {
    A1value: {
      sql: `${A1.value}`,
      type: `string`,
    },
    id: {
      sql: `id`,
      type: `number`,
      shown: false,
      primaryKey: true,
    }
  },
});

cube('A1', {
  sql: `SELECT 1 AS id, 1 AS user_id, 'value' AS value UNION ALL SELECT 2, 1, 'value' UNION ALL SELECT 3, 2, 'value'`,
  dimensions: {
    value: {
      sql: `value`,
      type: `string`,
      shown: false, // setting this to true fixes the issue
    }
  }
});
```

Query rewrite function:

```javascript
queryRewrite: (query, { securityContext }) => {
  if (query.dimensions.includes('A.A1value')) {
    query = {
      ...query,
      dimensions: query.dimensions.map(d => d === 'A.A1value' ? 'A1.value' : d),
    };
  }
  return query;
}
```

**Version:**
0.32.16

**Additional context**
Ideally, I would like this to work without a query rewrite. The problem is that, without doing that, [bug](https://github.com/cube-js/cube/issues/6390) gets triggered. This is the best workaround to that bug I could think of, but it triggers a different one.

**Comment by niravjprabtani** [comment]
I am also facing similar issue, any update here ?

**Comment by warren32** [comment]
I was facing a similar issue however the error was 
```
"TypeError: Cannot read properties of undefined (reading 'measures')\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/helpers/prepareAnnotation.ts:36:49"
```

I believe this error is caused when the cube backend attempts to read from the list of cubes (configMap) and the cube isn't there.  For me, the reason the cube wasn't there is because the `public` was set to false for that cube.  Also in your case the cube `A1` has a dimension that is set to `false`.  I also believe that when one or all members of a cube is set to `shown:false` then the entire cube is `shown:false`.  I would try to set the cube A1 `shown:true` and leave your dimension as `shown: false` and see if that works.

**Comment by igorlukanin** [comment]
I have just checked and it looks like the issue does not reproduce anymore on Cube v0.36.7. No `query_rewrite` is needed to query `A.A1value`:

<img width="1392" alt="Screenshot 2024-10-09 at 01 16 22" src="https://github.com/user-attachments/assets/bcf3b3cc-5b12-4a86-a00b-080869023e03">
