### ISSUE TITLE
Documentation bug: malformed gcp icon

### ISSUE THREAD

**Issue by jxperf** [cube-js/cube#6449]
**Describe the bug**
Malformed gcp icon at: https://cube.dev/docs/cloud/configuration/connecting-with-a-vpc

**Screenshots**

![image](https://user-images.githubusercontent.com/108638581/232652171-aacbc632-ad68-4f8f-9c94-c27e3aa1ec67.png)

**Comment by hassankhan** [comment]
Fixed now, thanks for reporting @jxperf 👍
