### ISSUE TITLE
pre-aggregation jobs endpoint

### ISSUE THREAD

**Issue by jxperf** [cube-js/cube#6457]
**Problem**
Hi, 
according to the REST API docs, there seems to be a `/cubejs-system/v1/pre-aggregations/jobs` endpoint however, querying this endpoint produces a `404 error`. Looking into the source code there seems to be a `/cubejs-api/v1/pre-aggregations/jobs` endpoint but that requires the `jobs` scope, since it raised this error `"error":"Permission is missed: jobs","stack":"Error: Permission is missed: jobs\n`
, and something seems to be overwriting the `CUBEJS_DEFAULT_API_SCOPES` environment variable such that changes to the environment variable does not get reflected.
is the CUBEJS_DEFAULT_API_SCOPES env variable deprecated? if so what is the updated way of accessing the `/v1/pre-aggregations/jobs` endpoint?

**Extra info**
- `CUBEJS_DEV_MODE=false`

**Comment by varunchillara27** [comment]
+1

**Comment by paveltiunov** [comment]
@hassankhan @buntarb

**Comment by jxperf** [comment]
Hi @buntarb, the issue I mentioned with `CUBEJS_DEFAULT_API_SCOPES` being overriden by default values seems to have been fixed with this PR: https://github.com/cube-js/cube/commit/b2da950509e48bdfcd5d6f282f81a00b3794d559

Thanks
