### ISSUE TITLE
How can I query session information from a database or API from within cube.js queryRewrite?

### ISSUE THREAD

**Issue by gblade** [cube-js/cube#6488]
**Problem**

How can I query session information from a database or API from within cube.js queryRewrite?

Our Authentication provider provides an ID token with a user ID. We would like to restrict cube queries by a user's department using the queryRewrite. Right now we are passing the ID token as the securityToken parameter of queryRewrite and adding a user filter to a user dimension of the schema. The downsides to this is the department schema has to be joined to a users schema which prevents pre-aggregations. Instead, I would like to get the users valid department at the time of querying through a database or API call to our backend.

Is this possible, or is there another strategy to achieve this?

**Comment by igorlukanin** [comment]
Hi @gblade 👋 Sorry for the late reply, is this issue still relevant?

> The downsides to this is the department schema has to be joined to a users schema which prevents pre-aggregations.
Why is that? You can definitely have measures and dimensions from different cubes in a single pre-aggregation.

> Instead, I would like to get the users valid department at the time of querying through a database or API call to our backend.
You can certainly do that. Depending on the data modeling language you use, you can just use the `requests` modeule in Python or the `fetch` function in JavaScript.

I hope it helps.
