### ISSUE TITLE
Security context is undefined in cube.js

### ISSUE THREAD

**Issue by webhelp-amorin** [cube-js/cube#6500]
**Describe the bug**
I am trying to access to security context in cube.js via driverFactory but I have the following compilation error : 
`Error: TypeError: Cannot read property 'schema' of undefined`

**To Reproduce**
1. Go to Playground and edit the security context : 
{
  "sub": "1",
  "user_id": "1",
  "schema": "public",
  "exp": 1682596546
}
2. Save and try to run the query

**Expected behavior**
Have access to secutiry context in cube.js to define on which database I want to access

**Screenshots**
I edit the security context via the Playground (screen below)
![image](https://user-images.githubusercontent.com/103027629/234567229-7d3853aa-c6ef-4f8c-ab67-97798d5baf98.png)

When I try to run the query, I have the following error : 
![image](https://user-images.githubusercontent.com/103027629/234567746-a36f6a36-7762-4f60-b6d2-6a88fcbebcb9.png)

I also try to follow this example : https://github.com/cube-js/cube/blob/master/examples/multitenancy-workshop/cube.js, but I have the same problem.

**Minimally reproducible Cube Schema**

```javascript
// cube.js

const host     = process.env.CUBEJS_DB_HOST;
const port     = process.env.CUBEJS_DB_PORT;
const database = process.env.CUBEJS_DB_NAME;
const user     = process.env.CUBEJS_DB_USER;
const password = process.env.CUBEJS_DB_PASS;

const PostgresDriver = require('@cubejs-backend/postgres-driver');

module.exports = {
  driverFactory: ({ securityContext }) => {
    if (!securityContext.schema) {
      throw new Error('No schema found in Security Context!');
    }

    if (securityContext.schema === 1) {
      return new PostgresDriver({
        database: 'multitenancy_workshop_aux',
        host,
        user,
        password,
        port,
      });
    } else {
      return new PostgresDriver({
        database,
        host,
        user,
        password,
        port,
      });
    }
  },
};

```

**Version:**
I'm using cube cloud and the cube version is 0.32.27

**Comment by buntarb** [comment]
@webhelp-amorin, try to pass your secure object under the `securityContext` property:
```javascript
{
"sub": "1",
"user_id": "1",
"securityContext": { "schema": "public" },
"exp": 1682596546
}
```

**Comment by paveltiunov** [comment]
@webhelp-amorin Please see warning message here https://cube.dev/docs/config/multitenancy#multiple-db-instances-with-same-data-model

**Comment by webhelp-amorin** [comment]
Development mode was set on "true", that's why I have no access to securityContext.
