### ISSUE TITLE
Export Logs to Datadog

### ISSUE THREAD

**Issue by emlim23** [cube-js/cube#6507]
**Problem**

I need examples of vector.toml on how I can connect/export your logs to our instance of Datadog. Your sample code here only covers exporting to Grafana (https://cube.dev/docs/cloud/workspace/logs). 

Btw, I wish to join your slack channel but the link is no longer working.

**Comment by igorlukanin** [comment]
Hey @emlim23 👋 

Sorry for getting back to you late. Here's a short guide on setting up Datadog with Cube Cloud: https://cube.dev/docs/monitoring/datadog

Also, please try signing in to Slack again, it should work.

Closing the issue—but please feel free to reopen or ping me on Slack.
