### ISSUE TITLE
Broken Slack Links

### ISSUE THREAD

**Issue by akvadrako** [cube-js/cube#6520]
**Describe the bug**

The links to Slack on your blog, README and docs do not work for me.

**To Reproduce**

On the blog, click [Join us on Slack](https://slack.cube.dev/), which gives the error page "This link is no longer active". Same with the link in the README.

In the [docs](https://cube.dev/docs), click [Slack](https://cubejs-community.herokuapp.com/) which gives an "Application error".

**Comment by hassankhan** [comment]
Hi @akvadrako :wave:

Thanks for reporting this, should be fixed now

**Comment by jayctran** [comment]
Hi, this is still not working

**Comment by igorlukanin** [comment]
@jayctran Sorry! Thanks for reporting! Should be fixed now.

**Comment by dcacaceshopfully** [comment]
Not working anymore

**Comment by SoozaV** [comment]
Still not working...
