### ISSUE TITLE
CubeCloud Slow Query using pre-aggregations

### ISSUE THREAD

**Issue by kaizendae** [cube-js/cube#6538]
**Problem**
I have a query that is accelerated by pre-aggregations and is served from CubeStore

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/17480866/235974662-4034e874-3073-4d81-88bd-df6d9c7f107b.png">
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/17480866/235974490-e0a3ced2-1991-404f-bf83-a5edaaa6c493.png">

Why is ~50% of the time is spent outside or performing the query? where is that time exactly spent?

Is it possible that using export bucket, would solve my problem?
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/17480866/235975701-9f90afcf-55f1-4ae3-84ef-53a4cd3bc7ee.png">

**Comment by kYann** [comment]
We have the same problem here.
Query on the database takes 30ms, query on cube takes 700ms.

Database and cube are on the same network with subms ping.

**Comment by igorlukanin** [comment]
@kYann Please feel free to start a new issue or a thread in slack.cube.dev. We'd need more details to give any advice on your issue. I believe the original question by @kaizendae was correctly addressed by @ovr.
