### ISSUE TITLE
Architecture relationships

### ISSUE THREAD

**Issue by cndev123** [cube-js/cube#6592]
The documentation on the deployment architecture was greatly improved in the last few weeks. I really appreciate that. But I still have a few nagging questions for clarification: 

We have a _cube cluster_ which can be composed of _API node_, _refresh node_ and _store cluster_.

Within one _cube cluster_, we can have multiple _API nodes_ behind a load balancer, but need at least one. 

**Question 1:** Not considering cube cloud, I assume, you can only have up to one _store cluster_ per _cube cluster_, correct?
**Question 2:** In any case, you can only have up to one _refresh node_ per _cube cluster_, correct?

A _store cluster_ must have one _router node_ which, in the minimal, config can act as a _worker node_ as well.
More than the minimal you only need, if you use pre-aggregations.
If you use pre-aggregations, you can run multiple _worker nodes_ with every _router node_. 

**Question 3:** I assume you have to explicitly form fixed sub-clusters between a _router node_ and all of its associated workers, correct?

It is also mentioned that you can use multiple _router nodes_ within one _store cluster_, but it is not clear to me how that should work, considering that you must tell your _api nodes_ which _router node_ to use. 

**Question 4:** Or would configure some _API nodes_ with _router node A_ and others with _router node B_? 

But then you still get a problem with the _refresh node_ which is also configured to be used with one _router node_.

It is also not clear to me how the _router nodes_ would know about each other in such a scenario.

**Comment by igorlukanin** [comment]
> Question 1: Not considering cube cloud, I assume, you can only have up to one store cluster per cube cluster, correct?

Yes.

> Question 2: In any case, you can only have up to one refresh node per cube cluster, correct?

Yes.

> A store cluster must have one router node which, in the minimal, config can act as a worker node as well.

Incorrect, Cube Store Router don't work as a Cube Store Worker. However, you can run a Cube Store Router only if you don't use pre-aggregations. In that case, your Cube Store Router will serve your query queue and cache only.

> Question 3: I assume you have to explicitly form fixed sub-clusters between a router node and all of its associated workers, correct?

You need to run one Cube Store Router and have multiple Cube Store Workers connected to is to build and query pre-aggregations.

> It is also mentioned that you can use multiple router nodes within one store cluster, but it is not clear to me how that should work, considering that you must tell your api nodes which router node to use.

It doesn't sound correct to me. Multiple Cube Store Routers in a Cube Store cluster can only be run in Cube Cloud.

> Question 4: Or would configure some API nodes with router node A and others with router node B?

In Cube Core, this is not a supported configuration.

@cndev123 I hope I addressed your questions—sorry for doing that quite late. Please feel free to reopen this issue if you'd like to follow up.
