### ISSUE TITLE
Download Content time from Cube server issue.

### ISSUE THREAD

**Issue by hawkEye-01** [cube-js/cube#6632]
Hi, I am using Cube JS (bigquery) as my backend for a Analytics React Application. I am concerned about the time it takes to down 
load query results from Cube Server (see attachment).

I have 50 Mb connection which is pretty stable as well.
My Cube JS server is deployed on Heroku.

**Is server is busy somewhere?** 
**Is there any to do profiling Cube server?**
Thanks for help. (BTW great Project. Love it. )

![image](https://github.com/cube-js/cube/assets/56556980/2904d043-2308-471e-8362-38c1b56d8512)

**Comment by igorlukanin** [comment]
Hey @hawkEye-01 It's quite hard to debug this without additional info about your setup. Please feel free to start a thread in slack.cube.dev or reopen this issue if it's still relevant, I'd be happy to try help you.
