### ISSUE TITLE
Do cubestore-worker expect persistent storage, or is ephemeral storage enough?

### ISSUE THREAD

**Issue by siamak-haschemi** [cube-js/cube#6654]
**Problem**

Do cubestore-worker expect persistent storage, or is ephemeral storage enough?

**Details**

I have a quick question regarding the self-hosting of cubestore-worker. Setup:
Running it in k8s
- 3 x cube-api
- 1 x cube-worker
- 1 x cubestore-router
- 3 x cubestore-worker

- BigQuery Data-Source (external=true)
- cloud-storage (Export-Bucket batch setup)

Do you recommend to have **persistent storage** for the 3 cubestore-workers, or is **ephemeral** storage (emptyDir) fine?

Thank you!

**Comment by igorlukanin** [comment]
I think this is [covered in docs](https://cube.dev/docs/product/caching/running-in-production#storage): Cube Store workers both need persistent and scratch storage.
