### ISSUE TITLE
Interval based refreshKey creates invalid SQL statement for ClickHouse DB

### ISSUE THREAD

**Issue by ralfbecher** [cube-js/cube#669]
**Describe the bug**
An interval based `refreshKey` defined as

```
  refreshKey: {
    every: '5 seconds'
  }
```
creates this PostgreSQL dialect SQL statement:

`SELECT FLOOR(EXTRACT(EPOCH FROM NOW()) / 5)`

This gets an `Syntax error: failed at position 28: FROM NOW()) / 5)` in ClickHouse.

The valid SQL statement for ClickHouse would be something like this:

`SELECT floor(toUInt64(now()) / 5)`

**Version:**
0.19.19

**Comment by paveltiunov** [comment]
@ralfbecher Thanks for posting this! Yep. Solution is to add `unixTimestamp()` method override in `ClickHouseQuery` similar to:
https://github.com/cube-js/cube.js/blob/be42298801fb8f3d7ce49e109538f3fa4d3391c6/packages/cubejs-schema-compiler/adapter/MysqlQuery.js#L71

**Comment by imrishabh18** [comment]
Can I take up this issue?

**Comment by paveltiunov** [comment]
Hey @imrishabh18 ! Yep. Sure!

**Comment by dmitrika** [comment]
Looks like it's done already within https://github.com/cube-js/cube.js/commit/6f40847f5e825bc92a8ee74b1ec40db911dd5513
