### ISSUE TITLE
Broken link in docs 

### ISSUE THREAD

**Issue by prochj51** [cube-js/cube#6699]
**Describe the bug**
On this page [Schema generation](https://cube.dev/docs/recipes/schema-generation) at the bottom there is broken link refering to export/import link.
The link works only when using scroll wheel.

![image](https://github.com/cube-js/cube/assets/40229516/451488ff-8a16-45c1-a05d-c07f07d15c71)

![image](https://github.com/cube-js/cube/assets/40229516/2fec30ed-a860-4be6-83f1-b881cf255385)

**Comment by igorlukanin** [comment]
@prochj51 Thanks for reporting this! The link is fixed now.
