### ISSUE TITLE
Schema generation on fly, auto recompile

### ISSUE THREAD

**Issue by prochj51** [cube-js/cube#6700]
Maybe there is some possibility of doing this, but I cannot find it.
Is there any API  for using the generate data feature similar to one in playground?
 
![image](https://github.com/cube-js/cube/assets/40229516/5d9ecd6b-c5c4-43bf-833e-2dff5d6781c9)

I know I can use dynamic schema creation via fetch API [Dynamic schema Cration](https://cube.dev/docs/schema/advanced/dynamic-schema-creation) but I cannot find a way how can I let the cube know it should recompile the schema model.

Use case is this.

In UI the user can choose certain segments for filtering data which should be added to schema model.

**Comment by igorlukanin** [comment]
Hi @prochj51 👋 

> but I cannot find a way how can I let the cube know it should recompile the schema model

There's the `schemaVersion` config option exactly for that purpose: https://cube.dev/docs/reference/configuration/config#schemaversion
