### ISSUE TITLE
Connection Test Failed while connecting with Oracle Database

### ISSUE THREAD

**Issue by achyutghosh** [cube-js/cube#6723]
I face the issue while connecting to the Oracle database through cube js. Whenever I've tried to communicate with Oracle it shows an error "Connection Test Failed." But I've double-checked the connection details and it is correct, moreover, all the IPs are whitelisted. Is Oracle not supported by Cube JS? 

Please refer to the image attached below.

![Screenshot 2023-06-14 132334](https://github.com/cube-js/cube/assets/35261444/b7efffe3-b852-4ce4-9dde-9578676a78a9)

**Comment by igorlukanin** [comment]
@achyutghosh Is this still relevant? Please feel free to reopen this issue if it is.
