### ISSUE TITLE
Can't see my view in the list of cubes

### ISSUE THREAD

**Issue by ALS2124** [cube-js/cube#6754]
Hello. I have the cube events_facts, and I created a view in the same file as the cube with this code:

```js
view(`test`, {
  description: 'view for test',
  includes: [
    events_facts.events
  ],
  dimensions: {
    id: {
      sql: `${events_facts.id}`,
      type: `number`
    }
  }
});
```

But after saving, my view is not shown in the list of cubes. There is no possibility for me to create a separate file for the view. Is it fine to have a view in the same file as a cube and why isn't my view showed up? Thank you.

**Comment by igorlukanin** [comment]
> Is it fine to have a view in the same file as a cube and why isn't my view showed up?

Yes, totally. It should work.

However, the following syntax for defining dimensions is deprecated. Please use `includes`, just like you did for `events_facts.events`.

```js
  dimensions: {
    id: {
      sql: `${events_facts.id}`,
      type: `number`
    }
  }
```
