### ISSUE TITLE
Executing an arbitrary callback on every query

### ISSUE THREAD

**Issue by hugoJuhel** [cube-js/cube#6757]
**Question**

Can we execute an arbitrary callback on every query run by Cube (on-prem) ? 
I basically want to log every query run against the cube SQL's interface to help me prioritize the next metric to be developed.

I was looking for something kind of like `queryRewrite`, accepting both the query and a securityContext.
If there is no hook / callback entry point, is there a function I could monkey-patch ?

**Comment by igorlukanin** [comment]
Hey @hugoJuhel 👋 `queryRewrite` is exactly the thing you're looking for. You can add logging or do a network call from it.
