### ISSUE TITLE
Cache not working?

### ISSUE THREAD

**Issue by PPBWoodBoy** [cube-js/cube#6758]
Hi,

I´m using Cube Core (Docker) in the version:  0.32.2 in dev mode.

I´m logging the querys and durations that cube is sending to my postgres db.

Now heres the question:
The Documentation for Cube says that the Devmode in Cube Core uses "in-memory" caching
but still Cube sends a query to my postgres db everytime I rerun the actual report (in developer playground).

Do I need to configure or activate the in-memory caching first?

Best regards.

**Comment by paveltiunov** [comment]
@PPBWoodBoy For Postgres by default, it refreshes every 10 seconds. Please see https://cube.dev/docs/schema/reference/cube#parameters-refresh-key.

**Comment by PPBWoodBoy** [comment]
> @PPBWoodBoy For Postgres by default, it refreshes every 10 seconds. Please see https://cube.dev/docs/schema/reference/cube#parameters-refresh-key.

Ok thank you, that means that I have to increase the refresh_key to a higher number like 10 minutes or something like that?

**Comment by PPBWoodBoy** [comment]
Is the cache active even if I dont have configured any refreshKey in my JS schema?

**Comment by igorlukanin** [comment]
> Ok thank you, that means that I have to increase the refresh_key to a higher number like 10 minutes or something like that?

Yes, you can do that. Alternatively, you can set up pre-aggregations and skip querying the database at all.

> Is the cache active even if I dont have configured any refreshKey in my JS schema?

If you skip the refresh key, the default value will be used.
