### ISSUE TITLE
preAggregations parquet files are never deleted from the local .cubestore folder of the cubestore-workers causing the disk to fill up 

### ISSUE THREAD

**Issue by scakkia** [cube-js/cube#6767]
**Describe the bug**
Parquet files are never deleted in the local directory .cubestore on workers.

**To Reproduce**
This is my configuration on docker:

cube_api:
  image: cubejs/cube:v0.33
  environment:
    - CUBEJS_DB_TYPE=redshift
    - CUBEJS_DB_HOST=xxx
    - CUBEJS_DB_PORT=5439
    - CUBEJS_DB_NAME=xxx
    - CUBEJS_DB_USER=xxx
    - CUBEJS_DB_PASS=xxx
    - CUBEJS_DB_QUERY_TIMEOUT=20m
    - CUBEJS_PRE_AGGREGATIONS_SCHEMA=xxx
    - CUBEJS_DB_EXPORT_BUCKET_REDSHIFT_ARN=xxxx
    - CUBEJS_DB_EXPORT_BUCKET_TYPE=s3
    - CUBEJS_DB_EXPORT_BUCKET=xxx
    - CUBEJS_DB_EXPORT_BUCKET_AWS_REGION=xx
    - CUBEJS_CUBESTORE_HOST=cubestore_router
    - CUBEJS_API_SECRET=xxx
    - CUBEJS_REFRESH_WORKER=false
    - CUBEJS_PRE_AGGREGATIONS_BUILDER=false
    - NODE_ENV=development
    - CUBEJS_DEV_MODE=true

cube_refresh_worker:
  image: cubejs/cube:v0.33
  environment:
    - CUBEJS_DB_TYPE=redshift
    - CUBEJS_DB_HOST=xxx
    - CUBEJS_DB_PORT=5439
    - CUBEJS_DB_NAME=xxx
    - CUBEJS_DB_USER=xxx
    - CUBEJS_DB_PASS=xxx
    - CUBEJS_DB_QUERY_TIMEOUT=20m
    - CUBEJS_PRE_AGGREGATIONS_SCHEMA=xxx
    - CUBEJS_DB_EXPORT_BUCKET_REDSHIFT_ARN=xxx
    - CUBEJS_DB_EXPORT_BUCKET_TYPE=s3
    - CUBEJS_DB_EXPORT_BUCKET=xxx
    - CUBEJS_DB_EXPORT_BUCKET_AWS_REGION=xxx
    - CUBEJS_API_SECRET=xxx
    - CUBEJS_CUBESTORE_HOST=cubestore_router
    - CUBEJS_REFRESH_WORKER=true
    - NODE_ENV=development
    - CUBEJS_DEV_MODE=true

cubestore_router:
  image: cubejs/cubestore:v0.33-arm64v8
  environment:
    - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
    - CUBESTORE_META_PORT=9999
    - CUBESTORE_SERVER_NAME=cubestore_router:9999
    - CUBESTORE_S3_BUCKET=xxx
    - CUBESTORE_S3_REGION=xxx
    - CUBESTORE_S3_SUB_PATH=xxx
    - DEBUG_LOG=true
    - CUBESTORE_LOG_LEVEL=trace

cubestore_worker_1:
  image: cubejs/cubestore:v0.33-arm64v8
  environment:
    - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
    - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
    - CUBESTORE_WORKER_PORT=10001
    - CUBESTORE_META_ADDR=cubestore_router:9999
    - CUBESTORE_S3_BUCKET=xxx
    - CUBESTORE_S3_REGION=xxx
    - CUBESTORE_S3_SUB_PATH=xxx
    - CUBESTORE_MAX_DISK_SPACE_PER_WORKER_GB=12
    - DEBUG_LOG=true
    - CUBESTORE_LOG_LEVEL=trace

cubestore_worker_2:
  image: cubejs/cubestore:v0.33-arm64v8
  environment:
    - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
    - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
    - CUBESTORE_WORKER_PORT=10002
    - CUBESTORE_META_ADDR=cubestore_router:9999
    - CUBESTORE_S3_BUCKET=xxx
    - CUBESTORE_S3_REGION=xxx
    - CUBESTORE_S3_SUB_PATH=xxx
    - CUBESTORE_MAX_DISK_SPACE_PER_WORKER_GB=12
    - DEBUG_LOG=true
    - CUBESTORE_LOG_LEVEL=trace

**Expected behavior**
The pre-aggr works like a charm. 
I've enabled TRACE log to see some useful information,
I see that after every refresh, router delete parquet file from S3, and the workers only download/upload from/to S3 but never delete them from the local dir .cubestore causing the disk to fill up.  

**Screenshots**
You can see the size of the folder on S3, 17G and 6400 object
and the size of .cubestore folder of 1 worker: 95G and 80000 files.

![image (24)](https://github.com/cube-js/cube/assets/1263089/669dfd00-0c11-4d07-ad97-6067fc769f11)
![image (23)](https://github.com/cube-js/cube/assets/1263089/232978a0-047a-40c9-83a4-9a35bcd5d43b)

**Minimally reproducible Cube Schema**
It happens with every schema with pre-aggr

**Version:**
0.33.29

**Additional context**
I tried adding the env_var CUBESTORE_MAX_DISK_SPACE_PER_WORKER_GB found in the code, but it does not work.
I'm missing somethings in configuration?
Should I implement some script on my part to clean the old parquet files?

Thanks a lot

**Comment by nitzien** [comment]
Do we have any suggestion on this?

**Comment by paveltiunov** [comment]
@scakkia could you please update to the latest version and see if it helps?

**Comment by scakkia** [comment]
Hi @paveltiunov , I updated to last version v0.33.33 2 days ago  (all refresh at 12 hour), I just checked and it seems to be working fine.

Thank you very much for your time

![image](https://github.com/cube-js/cube/assets/1263089/bf0d639f-07c0-4272-90b5-4b3a21196862)
![image](https://github.com/cube-js/cube/assets/1263089/cf85c7f2-383d-4408-bb4a-6fe8ce025512)

**Comment by siamak-haschemi** [comment]
https://github.com/cube-js/cube/pull/6688

**Comment by siamak-haschemi** [comment]
Might be related: https://github.com/cube-js/cube/pull/6796
