### ISSUE TITLE
MySQL Connection Runtime Error 

### ISSUE THREAD

**Issue by beatrizcm01** [cube-js/cube#6769]
I'm trying to set up a connection to a MySQL Database and it shows the following error message. I'm not sure what this is about since Cube IP should be allowed and I double-checked all my credentials. What could be the problem?

![image](https://github.com/cube-js/cube/assets/99352266/6a634a37-f492-4f47-b3d6-37a9c67e13b8)

**Comment by paveltiunov** [comment]
@beatrizcm01 Please reach out to our support team in intercom, and we'll help you to debug it.
