### ISSUE TITLE
is there a reason why `meta` fields are not also included in `cube`s and `view`s ?

### ISSUE THREAD

**Issue by jxperf** [cube-js/cube#6792]
**Problem**
as titled

**Comment by dodgex** [comment]
Hello @igorlukanin ,

while I am not the original poster of this question, i would like the same feature.

We are building a reporting fronted using cube as backend and having `meta` on cubes would allow to add stuff as descriptions and other metadata as groups. e.g we have multiple reporting areas in our cube schema and in our fronted they are seperated in stuff like "Human Resources", "Financial" and "Sales". right now we abuse the cube title and have like "AREA_NAME \ CUBE_NAME" to achieve that. having a dedicated meta field would be better in my opinion. :)

**Comment by dodgex** [comment]
there is another issue with the same request btw: https://github.com/cube-js/cube/issues/1539

**Comment by barakcoh** [comment]
same for us, we'd like to add metadata for the UI on how to display the cube (or hide it) in different parts of our app. 
More broadly, I think the same thinking that allowed for `meta` on members should apply here, without having to predict and evaluate the merits of specific use-cases, especially as this seems rather straightforward to implement.

**Comment by igorlukanin** [comment]
Now you can use `meta` on cubes and views:
- https://cube.dev/docs/reference/data-model/cube#meta
- https://cube.dev/docs/reference/data-model/view#meta
