### ISSUE TITLE
PowerBi does not support Unencrypted connection

### ISSUE THREAD

**Issue by jun-343** [cube-js/cube#6870]
I am self-hosting a CubeJs, and when I try using PowerBi to make a connection, it says
'We were unable to connect to the data source using an encrypted connection."

But if I use CubeCloud to make a connection with PowerBi, it does not show this error.

**Comment by paveltiunov** [comment]
@jun-343 Postgres encryption for SQL API is available only in Cube Cloud. For open source, you can use encrypting proxies instead.
