### ISSUE TITLE
Limit of 50k rows when connecting cube to excel

### ISSUE THREAD

**Issue by HassanAtWecrunch** [cube-js/cube#6883]
**Problem**

Hi, i am connecting cube via postgres connection to excel file to create pivot report. 
All works good except that the data I have is more than 50k and cube doesn't provide streaming data in this case. 
I read in your documentation of SQL API  (https://cube.dev/docs/backend/sql#querying-fundamentals-limit) something about it as: 

![image](https://github.com/cube-js/cube/assets/86463098/d80a32ef-85b9-4c25-b8e9-f52e12be86d6)

**will this help me in my problem?**
**Is this in pipeline?** 
Thanks.

**Comment by igorlukanin** [comment]
Hey @HassanAtWecrunch 👋 Sorry for a late reply.

I've just added a section in the docs (https://cube.dev/docs/product/data-modeling/queries#row-limit) that explains the row limit as well as the [`CUBEJS_DB_QUERY_LIMIT` environment variable](https://cube.dev/docs/reference/configuration/environment-variables#cubejs_db_query_limit) that you can use to bump it. Just be advised that bumping the row limit substantially may cause out-of-memory (OOM) crashes.

Please feel free to reopen the issue if this doesn't resolve it for you.
