### ISSUE TITLE
Configuration not working when switched to production environment

### ISSUE THREAD

**Issue by dcacaceshopfully** [cube-js/cube#6932]
**Describe the bug**
We are deploying Cube on AWS ECS, each container in a different cluster. During test in development mode everything it’s ok, but when we try to switch in production (changing the environment variable `CUBEJS_DEV_MODE = false` ) we are encountering some issues, the api calls return a 400.

**To Reproduce**
Everything works great using the dev mode `CUBEJS_DEV_MODE=true`

So we followed the [production checklist](https://cube.dev/docs/product/deployment/production-checklist) switching `CUBEJS_DEV_MODE=false`, we already had a separate environment for the cubestore (Is in a separate cluster), and from when we switched to production we are encountering this error doing API call:

```
Error: No pre-aggregation partitions were built yet for the pre-aggregation serving this query and this API instance wasn't set up to build pre-aggregations. Please make sure your refresh worker is configured correctly, running, pre-aggregation tables are built and all pre-aggregation refresh settings like timezone match. Expected table name patterns: sa_pre_aggregations_dev_cubejs.campaigns_main_*_lvh0i2o_*
```

In the workers logs we see just

```
ERROR [cubestore::cluster] <pid:1> Network error: Connection closed unexpectedly. Please check your worker and meta connection environment variables.
```

and in the router

```
ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
```

**Expected behavior**
In production environment same as development environment

**Minimally reproducible Cube Schema**
We deployed all the infrastructure in 5 ECS Clusters:
- 1 API 
- 1 Router
- 1 Refresh
- 2 Workers

Using redshift as DB and S3 storage for the `.paerquet` files 

**Version:**
v0.33

**Comment by mfclarke-cnx** [comment]
I'm seeing the same issue here, but without those logs in the worker. We're running on Azure AKS with a minimal test deployment of 1 API, 1 Refresh, 1 Router and 1 Worker. Using MS SQL Server as DB and Azure Files for storage via a persistent volume.

**Comment by mfclarke-cnx** [comment]
Just a note to say that this issue went away for us when we did the following:
* Updated to latest version
* Defined a partition granularity for each pre-aggregation

We can now see things working correctly.

**Comment by vasishtt** [comment]
which version did you upgrade to? I am facing similar issue on 0.34.52

**Comment by peterklingelhofer** [comment]
Tagging in here to say I was seeing this issue on v35.52-v35.67, increasing the granularity from hour to day, _even though we're querying for hourly data_ fixed this for us. Hope this helps someone.

**Comment by jlloyd-widen** [comment]
Thought I also might provide some context. I had a deployment in AWS EKS. I have a super minimal instance with only 1 cube with 1 measure, 3 dimensions, and 0 pre-aggs on a custom version of 35.22 and I still got this same error. I had remove all cubestore workers to resolve these errors.

**Comment by PaulStryck** [comment]
As I was also chasing the cause of these log entries, I'll post this here for anyone searching for the error log entry.

`ERROR [cubestore::cluster] <pid:1> Network error: Connection closed unexpectedly. Please check your worker and meta connection environment variables.`

In our case this was caused by a container health check probing TCP connectivity to `CUBESTORE_HTTP_BIND_ADDR` and `CUBESTORE_META_BIND_ADDR`.
The correct endpoint for health checks seems to be [`CUBESTORE_STATUS_BIND_ADDR`](https://github.com/cube-js/cube/blob/f395432ea7db963da345db32d3ede7bbd38d9c68/rust/cubestore/cubestore/src/config/mod.rs#L1380). Defaulting to 0.0.0.0:3031
