### ISSUE TITLE
Many Docs links are going to a 404 page

### ISSUE THREAD

**Issue by cassioscabral** [cube-js/cube#6933]
Reading this doc https://cube.dev/docs/product/apis-integrations/javascript-sdk/react#cube-javascript-client
I see that a lot of links are going to a 404 page.

I believe this URL: https://cube.dev/docs/@cubejs-client-core is the one failing.

**Comment by igorlukanin** [comment]
@cassioscabral Thanks for reporting this! I think @hassankhan can take a look and make sure it's fixed.
