### ISSUE TITLE
Question: user defined functions 

### ISSUE THREAD

**Issue by universalmind303** [cube-js/cube#6934]
**Problem**

Does Cube support user defined functions? or have plans to support UDFs

I'd like to create measures that require custom logic not supported by SQL.

```javascript
cube(`users`, {
  measures: {
    capitalize: {
      type: `udf`,
      source: {
        sql: `name`,
      },
      language: "python",
      return_type: "string",
      code: `
          def apply(self, name): 
            return name.capitalize()
        `
    },
  },
  // ...
});
```

**Comment by igorlukanin** [comment]
Hey @universalmind303 👋 

This is a very interesting question. I'd like to learn more about the use cases for this.

In the example that you provided, SQL would work just fine, right? `UPPER(column)` or something like that, depending on the database. You probably have a different use case in mind. Could you please share?

**Comment by universalmind303** [comment]
> In the example that you provided, SQL would work just fine, right? UPPER(column) or something like that, depending on the database. You probably have a different use case in mind. Could you please share?

yeah this is just meant to be a trivial example. The use case I had in mind is for transformations that are too complex to reasonably express them via sql. Such as ML inferences.

**Comment by paveltiunov** [comment]
@universalmind303 You can define your UDF with a script and then use it inside `sql` of a measure.
