### ISSUE TITLE
Query History Issue

### ISSUE THREAD

**Issue by ANDGagan** [cube-js/cube#6936]
**Problem**

When we call the CUBE.js API we are not getting the Query History but cube.js query is executed successfully.
we are facing this issue after upgrading the version(stable(0.33.25)) of Cube.

**Comment by igorlukanin** [comment]
Hey @ANDGagan 👋 

There's slight delay (usually, a few seconds) between a query is run and its appearance in Query History in Cube Cloud.

Is this issue still the case? If so, could you please share a link to your Cube Cloud deployment so we can research?
