### ISSUE TITLE
USER_CONTEXT is not populated by refresh scheduler

### ISSUE THREAD

**Issue by cd-romulus** [cube-js/cube#694]
**Describe the bug**
Values passed to CubeServerCore.runScheduledRefresh in context.authInfo.u are not propagated to USER_CONTEXT in cubes. When variables are accessed by USER_CONTEXT.variable.unsafeValue() they are undefined.

**To Reproduce**
1. Create a cube that uses USER_CONTEXT unsafeValue() and preaggregations with scheduled refresh, e.g.:

```js
cube(`MyCube`, {
    sql: `SELECT '${USER_CONTEXT.schema.unsafeValue()}' as schem`,

    measures:{
        one:{
            sql: '1',
            type: 'number'
        }
    },
    dimensions:{
        schema:{
            sql: 'schem',
            type: 'string'
        }
    },
    preAggregations:{
        dummy: {
            type: 'originalSql',
            refreshKey: {
                every: `1 second`
              },
            scheduledRefresh: true
        }
    }
})
```
2. Load a query and make sure `authInfo.u.schema` gets set (for example in the chechAuthMiddleware). In my example I set it to 'ws6'. The logs show that cube js will load the preAggregation *as expected* like so:

```sql
  CREATE TABLE ws6_pre_aggregations.my_cube_dummy_5kvbemve_e3c20eu1_1591446361750 AS 
  SELECT 'ws6' as schem
```

3. Now invoke the refresh scheduler with the context parameter

```js
cubeJsServer.runScheduledRefresh({authInfo: {u:{schema: 'ws6'}}})
```

The logs show that the USER_CONTEXT.schema.unsafeValue() resulted in 'undefined':

```sql
   CREATE TABLE ws6_pre_aggregations.my_cube_dummy_x5rkmay0_0rndfll4_1591446362780 AS
   SELECT 'undefined' as schem
```
(Note that I use `authInfo.u.schema` in `preAggregationsSchema` to get per tenant pre aggregations and the pre aggregation schema is correctly generated in both cases)

The behavior is the same if the scheduled refresh is triggered via the REST api.

**Expected behavior**
USER_CONTEXT should be populated regardless if the query is invoked by the refresh scheduler or from a user loaded query.

**Version:**
@cubejs-backend/postgres-driver: 0.19.20,
@cubejs-backend/server: 0.19.23

**Comment by Levhav** [comment]
Hi, 
I suppose in your case will work this configuration

```js
cube(`MyCube`, {
  sql: `SELECT '${COMPILE_CONTEXT.authInfo.u.schema}' as schem`,

  measures:{
      one:{
          sql: '1',
          type: 'number'
      }
  },
  dimensions:{
      schema:{
          sql: 'schem',
          type: 'string'
      }
  },
  preAggregations:{
      dummy: {
          type: 'originalSql',
          refreshKey: {
              every: `1 second`
            },
          scheduledRefresh: true
      }
  }
})
```

**Comment by hassankhan** [comment]
Hi @cd-romulus, we have a [`scheduledRefreshContexts`](https://cube.dev/docs/config#options-reference-scheduled-refresh-contexts) option in the `cube.js` configuration file, could you check and see if that works for you? Thanks in advance :raised_hands:

**Comment by paveltiunov** [comment]
Reworked in the latest version.
