### ISSUE TITLE
Rolling window pre-aggregation query throws "Error during planning: No field named..." since upgrade

### ISSUE THREAD

**Issue by antonzy** [cube-js/cube#6951]
**Describe the bug**
Since upgrading from `0.30.62` to `0.33.38`, I'm encountering an error when running a previously working query. The error message is as follows:

```
{
    "error": "Error: Internal: Error during planning: No field named 'order.created_at'. Valid fields are 'order__created_at_day', 'order__rolling_count'."
}

```

**To Reproduce**
1. Run the following query:

```
{
  "measures": [
    "Order.rollingCount"
  ],
  "timeDimensions": [
    {
      "dimension": "Order.createdAt",
      "dateRange": [
        "2023-07-11",
        "2023-07-18"
      ]
    }
  ]
}

```

**Expected behavior**
The query should run successfully without an error about a non-existent 'order.created_at' field, as it did on the previous version.

**Minimally reproducible Cube Schema**
Below is the Cube.js schema where the error occurs:

```javascript
cube(`Order`, {
  sql: `SELECT * FROM public.orders`,
  measures: {
    rollingCount: {
      sql: `id`,
      type: `count`,
      rollingWindow: {
        trailing: `unbounded`,
      },
    },
  },

  dimensions: {
      createdAt: {
        sql: `created_at`,
        type: `time`
      },
  },

  preAggregations: {
    totalByDay: {
      measures: [
        Order.rollingCount
      ],
      timeDimension: Order.createdAt,
      granularity: `day`,
      refreshKey: {
        every: `1 minute`,
      },
    },
  }
})
```

**Version:**
0.33.38

**Additional context**
This error was not present in Cube.js version 0.30.62, but started appearing after upgrading to 0.33.38. The issue is related to the 'Order.createdAt' field in the query and schema.

**Comment by antonzy** [comment]
It may be worth noting that this issue is preventing us from transitioning to the hosted version, so any assistance would be greatly appreciated 🙏

**Comment by igorlukanin** [comment]
Hey @antonzy 👋 

Could you please try updating Cube? I've tried exactly your data model with Cube v0.33.41 and it worked as expected. Not sure what the issue was but upgrading should probably help.

<img width="722" alt="Screenshot 2023-08-01 at 13 53 55" src="https://github.com/cube-js/cube/assets/3852894/0f86750a-0feb-4059-8c7a-50d82dd13793">

<img width="1076" alt="Screenshot 2023-08-01 at 13 54 14" src="https://github.com/cube-js/cube/assets/3852894/3a171693-a3a5-4386-970d-00e04ace5171">

**Comment by antonzy** [comment]
@igorlukanin thanks for checking this. I still get the same error on `0.33.41`.

In your query, you haven't added the date range filter - just tried to remove it and the error dissapears, but I need the filter applied in my case :) 

Can you please try adding the date range filter based on the `Order.createdAt` dimension and test it on your end?

**Comment by igorlukanin** [comment]
I have discovered that the original error is not raised anymore, the pre-aggregation builds, and using the `day` granularity allows to get a correct result. So it looks like it's time to close this issue.

However, I've also discovered another bug, see the linked issue for details.
