### ISSUE TITLE
AWS Athena preaggregation files format

### ISSUE THREAD

**Issue by svdimchenko** [cube-js/cube#6967]
**Problem**

I have a cube's dimension with type string and it unfortunately contains '\n' symbols. Because of that, preaggregation flow generates 2 rows for such cases and finally I get the following error which is expected:

```
2023-08-01 10:14:20,384 ERROR [cubestore::cluster] <pid:1> Error while running job 93055: Can't parse '19.586212' column value for 'backoffice_as_of_date_day' column: Can't parse timestamp: 19.586212
```

Current preaggregation flow is following (If I understand it correctly):
1. Cube exports query results as TEXT CSV files
2. Cubestore downloads them and transforms to parquet
3. Cubestore uses these parquet files as a source to serve queries when it's possible

The question is: can we skip this CSV-TO-PARQUET transformation and use parquet format directly in UNLOAD query ? 
This can fix many possible problems when dealing with CSV files.

**Comment by npopovic1** [comment]
This is also an issue when there is a comma inside of the dimension string, the CSV export does not wrap the text in quotes.

**Comment by npopovic1** [comment]
Using the most recent athena-driver (33.42), I am now not seeing any commas in the CSV from the UNLOAD. I see the UNLOAD statement now ends in `WITH ( format = 'TEXTFILE', compression='GZIP' )`

**Comment by svdimchenko** [comment]
@npopovic1 it's correct unload query. However the problem occurs on `cubestore` side when it tries to create table based on exported data.

**Comment by npopovic1** [comment]
@svdimchenko I guess I'm not sure then how it can differentiate columns without a delimiter when it reads from the CSV when it builds the preagg tables internally.

**Comment by igorlukanin** [comment]
I guess this is technically duplicate of #7071, despite being created earlier. There's a more complete discussion in that issue, and a possible workaround provided, so let me close this one in favor of that one.
