### ISSUE TITLE
Problem with some measures calculation

### ISSUE THREAD

**Issue by mariiaamatiukh** [cube-js/cube#7008]
In js config for my cube I have defined the following metrics:

```
sub_metric1: {
                sql: `sub_metric1`,
                type: `sum`
            },
sub_metric2: {
                sql: `sub_metric2`,
                type: `sum`
            },
metric1: {
                sql: `id`,
                type: `countDistinct`
            },
metric2: {
                sql: `${sub_metric1} + ${sub_metric2}`,
                type: `number`
            },
metric3: {
                sql: `${metric2} / NULLIF(${metric1}, 0)`,
                type: `number`
            }
```

and when I used metric3 (for example, in Cube Playground) as result I received such sql -> incorrect values:

`sum("cube".sub_metric1) + sum("cube".sub_metric2) / NULLIF(
    count(
      distinct "cube".id
    ),
    0
  ) "metric3"
`

Correct sql should looks like:

`(sum("cube".sub_metric1) + sum("cube".sub_metric2)) / NULLIF(
    count(
      distinct "cube".id
    ),
    0
  ) "metric3"
`

**Comment by igorlukanin** [comment]
@mariiaamatiukh Think for posting this! I think it's related to #6373
