### ISSUE TITLE
Langchain IndexError: list index out of range

### ISSUE THREAD

**Issue by muhammadsr** [cube-js/cube#7028]
**Problem**

When I run `python ingest.py`, I get this error: 

```
Traceback (most recent call last):
  File "/Users/malraddadi/Downloads/cube-master/examples/langchain/ingest.py", line 32, in <module>
    ingest_cube_meta()
  File "/Users/malraddadi/Downloads/cube-master/examples/langchain/ingest.py", line 24, in ingest_cube_meta
    vectorstore = FAISS.from_documents(documents, embeddings)
  File "/Users/malraddadi/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/base.py", line 420, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/Users/malraddadi/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/faiss.py", line 608, in from_texts
    return cls.__from(
  File "/Users/malraddadi/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/faiss.py", line 552, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range
```

The issue triggers when this line executes:
`vectorstore = FAISS.from_documents(documents, embeddings)`. 

Also, my `documents` seem to be empty `[]`. I have connected my cube to MySQL and I can run queries just fine in my `cubecloud.dev` 

*My `ingest.py` file*
```
import pickle
import jwt
import os

from dotenv import load_dotenv
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores.faiss import FAISS

from langchain.document_loaders import CubeSemanticLoader

load_dotenv()


def ingest_cube_meta():
    api_url = os.environ["CUBE_API_URL"]
    cubejs_api_secret = os.environ["CUBE_API_SECRET"]
    security_context = {}
    api_token = jwt.encode(security_context, cubejs_api_secret, algorithm="HS256")
    loader = CubeSemanticLoader(api_url, api_token)
    documents = loader.load()
    print('documents: ', documents);

    embeddings = OpenAIEmbeddings()
    vectorstore = FAISS.from_documents(documents, embeddings)

    # Save vectorstore
    # with open("vectorstore.pkl", "wb") as f:
        # pickle.dump(vectorstore, f)


if __name__ == "__main__":
    ingest_cube_meta()

```

Thoughts?

**Comment by MikeNitsenko** [comment]
@muhammadsr 
could you please check the following:
- Langchain version should be `>=` 0.0.242
- if the `/meta` endpoint is accessible with the `api_url` and `api_token` you're getting in `ingest.py` code

**Comment by muhammadsr** [comment]
@MikeNitsenko 
<img width="554" alt="Screen Shot 2023-08-14 at 7 25 06 PM" src="https://github.com/cube-js/cube/assets/1937488/828cb294-ca5b-4dbc-9c57-56b0f1a40b5c">

<img width="658" alt="Screen Shot 2023-08-14 at 7 24 51 PM" src="https://github.com/cube-js/cube/assets/1937488/72cb455a-6a32-4a54-ada7-ee3221126a32">

**Comment by MikeNitsenko** [comment]
@muhammadsr oh, I see.
CubeSemanticLoader processes views only, and you have only one cube in your data model.
And nothing in docs tells that the loader uses views and omits cubes :man_facepalming:  
Thanks for noticing, I'll submit a pr to langchain fixing this behavior.

**Comment by igorlukanin** [comment]
@muhammadsr Please see if the updated LangChain integration works for you.
