### ISSUE TITLE
Incorrect result when dividing preaggregated measures

### ISSUE THREAD

**Issue by JacoBrits88** [cube-js/cube#7080]
The following query results in either 100.0% or 0.0% for all records when the query is accelerated by preaggregations:

`{"measures":["Cube1.Measure3"],"dimensions":["Cube1.Dimension1"]}`

This is the measure in question:

```js
    Measure3: {
      type: 'number',
      sql: 'CAST(${Measure1} AS FLOAT)*100.0 / CAST(${Measure2}*1.0 AS FLOAT)', 
      format: 'percent', 
      filters: [{ sql: 'CAST(${Measure2}*1.0 AS FLOAT) > 0.0' }],
    },
```

When removing this measure from the preaggregations the result is as expect, ie. 13.65%, etc.

**Comment by igorlukanin** [comment]
@JacoBrits88 May I ask what led to adding `CAST(... AS FLOAT)`s to the SQL expression here? I guess measures are numbers anyway, aren't they? Could you please check when happens if you define the measure as follows?

```js
    Measure3: {
      type: 'number',
      sql: '${Measure1} / ${Measure2}', 
      format: 'percent', 
      filters: [{ sql: '${Measure2} > 0.0' }],
    },
```

Tagging @paveltiunov for visibility.

**Comment by JacoBrits88** [comment]
Hi @igorlukanin,

I build the measure as you have it here initially but came to this issue. I then tried to force the measures to a float to see if that would solve the issue. I have changed the measure as you requested and still getting the 100.0% / 0.0%

**Comment by igorlukanin** [comment]
May you please provide a full yet minimal data model file that I can use to test this?

**Comment by JacoBrits88** [comment]
@igorlukanin I found that this issue only occurs with a specific dimension only. Will run some more tests to see if I can find the issue. Thanks
