### ISSUE TITLE
Not able to search using & (ampersand) using filters in cube core

### ISSUE THREAD

**Issue by niravjprabtani** [cube-js/cube#7085]
**Describe the bug**
The entire cube core instance is getting broken if I am passing & (ampersand) character while filtering the data

**To Reproduce**
1. Select measures or dimensions from the playground
2. Add filter by selecting an appropriate column and add values with & (ampersand) i.e. "E&D Vending Ltd"
3. Observe the Cube core response

**Expected behavior**
It should filter out the results on the basis of the applied filter even if the values contain & (ampersand) character

**Screenshots**
![image](https://github.com/cube-js/cube/assets/49067519/eebf2c51-b69b-40d7-8e9b-b2a16b23f7e2)

**Minimally reproducible Cube Schema**
I am sharing a sample cube request here

```javascript
{
    "dimensions": ["cubename.columnname"],
    "order": {
        "cubename.columnname": "asc"
    },
    "filters": [{
        "member": "cubename.columnname",
        "operator": "contains",
        "values": ["E&D Vending Ltd"]
    }]
}
```

**Version:**
0.33.47

**Additional context**
I have tried out the below things as escape characters to see if it starts working but no luck, Any suggestions or solutions would be highly appreciated.
``` 
&amp;
%26
```

**Comment by igorlukanin** [comment]
Hi @niravjprabtani 👋 Thanks for reporting this! It looks like a bug in Playground.

Could you please run the same query against any of Cube's APIs. Do you any error in that case?

**Comment by niravjprabtani** [comment]
> Hi @niravjprabtani 👋 Thanks for reporting this! It looks like a bug in Playground.
> 
> Could you please run the same query against any of Cube's APIs. Do you any error in that case?

Yes, I have tried it and it works fine with API as I am taking care it by implementing escape character for the same.

**Comment by zafaralam** [comment]
I have a similar issue when using `contains` operator in the filters section. In my case the character causing the issue is `_`. I'm using the **duckdb** data connector.

Any help would be greatly appreciated.

Example JSON Query.

```json
{
  "measures": [
    "employees.COUNT"
  ],
  "filters": [
    {
      "member": "employees.ALL_SPLITS",
      "operator": "contains",
      "values": [
        "transfer_only",
        "fixed_only"
      ]
    }
  ]
}
```

**Comment by igorlukanin** [comment]
Since v0.36.x, the UI for composing queries and adding filters has been updated. Please see https://cube.dev/docs/product/workspace/playground#composing-queries

Using ampersand characters is now working just fine:
<img width="886" alt="Screenshot 2024-09-30 at 15 53 37" src="https://github.com/user-attachments/assets/5d7b109f-3541-4891-9956-d131b8e7b310">
