### ISSUE TITLE
How to refresh pre-aggregations?

### ISSUE THREAD

**Issue by dtslvr** [cube-js/cube#7088]
What is the best practice to refresh / reset all pre-aggregations manually?

I expected `/v1/run-scheduled-refresh` to be the approach, but it does not seem to work in my setup with _Cube_ `v0.33.36`.

In `dev` mode, I get `{ "finished": true }` (where the documentation promises an [empty object response if scheduled successfully](https://cube.dev/docs/reference/rest-api#v1run-scheduled-refresh)), but the (outdated) data is still available.

In `production` mode, I get the following error:
```
Invalid configuration - when externalRefresh is true, it will not perform a renew, therefore you cannot wait for it using waitForRenew.
```

Can you give me a hint? Thank you very much in advance.

**Comment by igorlukanin** [comment]
Hi @dtslvr 👋 

1. One way to refresh pre-aggregations when the upstream data changes is to define custom refresh keys. See this recipe for details: https://cube.dev/docs/guides/recipes/query-acceleration/refreshing-select-partitions
2. Another way is to use the Orchestration API: https://cube.dev/docs/product/apis-integrations/orchestration-api

I believe that the second approach is closest to what you've already tried.

**Comment by dtslvr** [comment]
Thank you very much the explanations @igorlukanin. The documentation of the _Orchestration API_ (2) describes exactly what we are looking for: Building pre-aggregations to invalidate and rebuild pre-aggregations on demand.

We are using `POST /v1/pre-aggregations/jobs` now and it works as expected.
