### ISSUE TITLE
Cubestore miss decimal point precision if calculated measures are set through pre-aggregations

### ISSUE THREAD

**Issue by yinkaihsu** [cube-js/cube#7106]
**Describe the bug**

Cubestore will miss decimal point precision by returning as `integer` if calculated measures are set through pre-aggregations.
Instead, it should return as `decimal` of `string` if the value has decimal point.
For example, if the calculated measure is equals to `"1" / "3"`, API should return as `"0.333333"` instead of `"0"` through Cubestore.

**To Reproduce**

1. `cube.js` file
```javascript
cube(`orders`, {
  // ...
 
  measures: {
    purchases_ratio: {
      sql: `${purchases} / ${count}`,
      type: `number`,
    },
  },

  preAggregations: {
    mainPreAgg: {
      measures: [CUBE.purchases, CUBE.count],
    },
  },
});
```
2. REST API request
```json
{
    "query": {
        "measures": [
            "orders.purchases_ratio",
            "orders.purchases",
            "orders.count"
        ]
    }
}
```

3. REST API response
```json
{
    "data": [
        {
            "orders.purchases_ratio": "0",
            "orders.count": "3",
            "orders.purchases": "1"
        }
    ]
}
```

**Expected behavior**

REST API response
```json
{
    "data": [
        {
            "orders.purchases_ratio": "0.333333",
            "orders.count": "3",
            "orders.purchases": "1"
        }
    ]
}
```

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, true as is_purchase
  UNION ALL
  select 2 as id, NULL as is_purchase
  UNION ALL
  select 3 as id, NULL as is_purchase
  `,
  measures: {
    count: {
      type: `count`,
    },
    purchases: {
      sql: `is_purchase`,
      type: `count`,
    },
    purchases_ratio: {
      sql: `${purchases} / ${count}`,
      type: `number`,
    },
  },

  dimensions: {
  },

  preAggregations: {
    mainPreAgg: {
      measures: [CUBE.purchases, CUBE.count],
    },
  },
});
```

**Version:**
v0.33.35

**Additional context**

**Comment by igorlukanin** [comment]
@yinkaihsu Does updating `purchases_ratio` as follows resolve the issue?

```js
    purchases_ratio: {
      sql: `1.0 * ${purchases} / ${count}`,
      type: `number`,
    },
```

**Comment by yinkaihsu** [comment]
Hi @igorlukanin ,
it works well as the solution you mentioned above.
Thanks a lot!
