### ISSUE TITLE
Is there a way to programmatically retrieve the graph QL schema

### ISSUE THREAD

**Issue by syte** [cube-js/cube#7179]
We'd like to add cube to our federated graph. The deployment process that we typically use for our other repos is as follows

1. Validate the graphQL schema
2. Publish it to hive

In the case of cube, we don't have access to the graph QL schema without having a running instance of cube. It would be nice if there was a way to generate the graph QL schema programmatically. Right now if we want to publish cube to our federated graph, we'd have to do the following.

1. Deploy cube
2. Make sure it's been updated
3. Dump the schema from the running instance
4. Validate the schema
5. Publish the schema

As you can see this process is a bit more cumbersome.

**Comment by vasilev-alex** [comment]
Hey @syte!

I don't think it would be possible because the GraphQL schema is generated based on metadata, which, in turn, is handled by the compiler API. Therefore, you need to run the Cube instance to fetch it.

**Comment by syte** [comment]
Thanks @vasilev-alex. Just wanted to confirm this was the easiest way. Thank you!
