### ISSUE TITLE
duckdb can't read parquet files on mac m2

### ISSUE THREAD

**Issue by carlinhop** [cube-js/cube#7194]
**Describe the bug**
Trying to use duckdb in a container shows the following error several times in the console.

🚀 Cube API server (0.34.0) is listening on 4000
{"message":"Compiling schema error","version":"default_schema_version","requestId":"487b86c5-d11b-413a-8c43-372d2b6f2512-span-1","error":"Error: /cube/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory\n    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Module.require (node:internal/modules/cjs/loader:1100:19)\n    at require (node:internal/modules/cjs/helpers:119:18)\n    at Object.<anonymous> (/cube/node_modules/duckdb/lib/duckdb-binding.js:4:15)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Module.require (node:internal/modules/cjs/loader:1100:19)\n    at require (node:internal/modules/cjs/helpers:119:18)\n    at Object.<anonymous> (/cube/node_modules/duckdb/lib/duckdb.js:6:14)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)\n    at Module.load (node:internal/modules/cjs/loader:1076:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:911:12)\n    at Module.require (node:internal/modules/cjs/loader:1100:19)\n    at require (node:internal/modules/cjs/helpers:119:18)\n    at Object.<anonymous> (/cube/node_modules/@cubejs-backend/duckdb-driver/src/DuckDBDriver.ts:11:1)\n    at Module._compile (node:internal/modules/cjs/loader:1198:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)"} 

**To Reproduce**
Start a container with duckdb to read parquet files on s3 and make a query to the underlying data files. Querying the meta endpoint does not fail so the problem is interacting with duckdb.

**Expected behavior**
Querying the endpoint should show data like it usually does.

**Minimally reproducible Cube Schema**
In case your bug report is data modeling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```cubes:
  - name: series
    sql: >
      SELECT * FROM read_parquet('s3://xx/xx/xx/xx/**/*.parquet', hive_partitioning=true)
    data_source: default

    joins: []

    dimensions:

      - name: entity
        sql: entity_id
        type: number

      - name: value
        sql: value
        type: number

      - name: year
        sql: year
        type: number

      - name: month
        sql: month
        type: number

      - name: business_size
        sql: business_size[1]||'-'||business_size[2]
        type: string

      - name: legal_form_of_organization
        sql: legal_form_of_organization
        type: string

      - name: industry_code
        sql: industry_code
        type: string

      - name: sic07_subclass
        sql: sic07_subclass
        type: string

    measures:
      - name: count
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

```

**Version:**
0.34.0

**Additional context**
I'm running containers using docker/podman on a mac m2 (macos: ventura 13.2.1 (22D68))
If I log inside the container and run nodejs, I can't import duckdb. The error is:

```Uncaught:
Error: /cube/node_modules/duckdb/lib/binding/duckdb.node: cannot open shared object file: No such file or directory```

**Comment by ovr** [comment]
Hello @carlinhop ,

There was an issue on the DuckDB side:

`duckdb.node` was x86 library for arm64 instead of arm64.

Could you give it a try with the latest release?

Thanks
