### ISSUE TITLE
Unexpected join directionality between 2 cubes with a many-to-one relationship

### ISSUE THREAD

**Issue by pranav-loops** [cube-js/cube#7281]
**Problem**

I have 2 cubes Ticket and TicketComments where 1 ticket can have multiple comments. I want to query the comment count for all tickets using the query: 
```
{"dimensions":["Ticket.id"],"measures":["TicketComment.count"]}
```
However, I see that the sql it generates starts from the TicketComment cube and left joins on the Ticket cube. Isn't this supposed to be the other way round (ticket left joins with ticket comments) given how the cubes are related. Note that both cubes have the join defined, one with `hasMany` and the other with `belongsTo` which is the precondition for this issue. Having exactly one join defined with `hasMany` solves the purpose, but that's not the scenario in consideration.

**Related Cube.js generated SQL**

```sql
SELECT
      `ticket`.id `ticket__id`, count(`ticket_comment`.id) `ticket_comment__count`
    FROM
      ticket_comments AS `ticket_comment`
LEFT JOIN tickets AS `ticket` ON `ticket_comment`.ticketId = `ticket`.id  GROUP BY 1 ORDER BY 2 DESC
```

**Related Cube.js schema**
```javascript
cube(`Ticket`, {
    sql: `SELECT * FROM tickets`,
    joins: {
        TicketComment: {
            sql: `${Ticket}.id = ${TicketComment}.ticketId`,
            relationship: `hasMany`
        },
    },
    dimensions: {
        id: {
            sql: `id`,
            type: `number`,
            primaryKey: true,
            shown: true
        }
    }
});

cube(`TicketComment`, {
    sql: `SELECT * FROM ticket_comments`,
    joins: {
        // This join is required because there are other cubes in the overall schema 
        // which TicketComment would join to
        // Removing this, gives the right join path, as expected. However it cannot be removed in our case.
        Ticket: {
            sql: `${TicketComment}.ticketId = ${Ticket}.id`,
            relationship: `belongsTo`
        },
    },
    measures: {
        count: {
            sql: `id`,
            type: `count`
        },
    },
    dimensions: {
        id: {
            sql: `id`,
            type: `number`,
            primaryKey: true,
            shown: false
        }
    }
});
```

**Comment by paveltiunov** [comment]
@pranav-loops Please use https://cube.dev/docs/reference/data-model/view to control join paths.

**Comment by pranav-loops** [comment]
Hi @paveltiunov I am aware of views to control join paths. Our code base currently doesn't use views. For now, my concern is more from an understanding point of view for a scenario involving 2 cubes only. 

When a many-to-one and a one-to-many relationship is defined between the same 2 cubes, I was expecting the SQL to start from the "one" side and left join with the "many" side, which is fair for a relational structure.
1. Just curious if there's any rationale of the implementation and why it prefers the other way around.
2. Also, is there any way to influence this join selection without using views?

**Comment by paveltiunov** [comment]
@pranav-loops 
1. It'll build a join tree first for measures cubes and then for dimensions.
2. There's currently no way to influence the join path at the query level. We have an issue for that #438.
