### ISSUE TITLE
Issue with Refreshing Cube.js Measures and Dimensions

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7282]
In the Cube development mode, I noticed that when I modify the cube.js file under the schema, newly added measures or dimensions can be queried immediately. However, in the production mode, modifying the cube.js file does not trigger a refresh. I would like to know if there is a configuration option available to achieve hot reloading, or if there are any other possible solutions.

**Comment by paveltiunov** [comment]
@w1992wishes Please see https://cube.dev/docs/product/data-modeling/dynamic/javascript#usage-with-schemaversion

**Comment by w1992wishes** [comment]
i see. tks
