### ISSUE TITLE
Docs "getting started": users.USER_ID vs. users.ID

### ISSUE THREAD

**Issue by bbrewington** [cube-js/cube#7286]
Glad to submit a PR for this to close out this issue, but just wanted to submit problem details I just discovered while walking through the tutorial here: https://cube.dev/docs/product/getting-started/cloud/create-data-model

## Problem Details

USER_ID is used in the `CREATE TABLE` statement, but not in `COPY INTO` (see lines 80 & 94)

https://github.com/cube-js/cube/blob/7aaffd565199e41c15851336acfcb1fc2fba76dd/docs/docs-new/pages/product/getting-started/cloud/load-data.mdx#L77-L89

https://github.com/cube-js/cube/blob/7aaffd565199e41c15851336acfcb1fc2fba76dd/docs/docs-new/pages/product/getting-started/cloud/load-data.mdx#L94

YAML should reference `{users}.ID` instead of `{users}.USER_ID` (lines 66 & 140)

https://github.com/cube-js/cube/blob/7aaffd565199e41c15851336acfcb1fc2fba76dd/docs/docs-new/pages/product/getting-started/cloud/create-data-model.mdx#L60-L67

https://github.com/cube-js/cube/blob/7aaffd565199e41c15851336acfcb1fc2fba76dd/docs/docs-new/pages/product/getting-started/cloud/create-data-model.mdx#L134-L141

## Additional Info

Ran this query after importing data from AWS S3 bucket as laid out in the tutorial:

```sql
SELECT
    'JOIN ON USERS.ID' as LABEL,
    SUM(IFF("users".ID IS NULL, 1, 0)) as NUM_NULL,
    COUNT(*) as NUM_RECORDS
FROM CUBE_DEMO_ECOM.ORDERS AS "orders"
LEFT JOIN CUBE_DEMO_ECOM.USERS AS "users"
    ON "orders".USER_ID = "users".ID

UNION ALL

SELECT
    'JOIN ON USERS.USER_ID' as LABEL,
    SUM(IFF("users".USER_ID IS NULL, 1, 0)) as NUM_NULL,
    COUNT(*) as NUM_RECORDS
FROM CUBE_DEMO_ECOM.ORDERS AS "orders"
LEFT JOIN CUBE_DEMO_ECOM.USERS AS "users"
    ON "orders".USER_ID = "users".USER_ID
```

Results:

| LABEL | NUM_NOT_NULL | NUM_RECORDS |
|---|---|---|
|JOIN ON USERS.ID|10000|10000|
|JOIN ON USERS.USER_ID|0|10000|

**Comment by igorlukanin** [comment]
Thanks for reporting this @bbrewington 🙌
