### ISSUE TITLE
Cubestore Round Issues

### ISSUE THREAD

**Issue by ranjeetranjan** [cube-js/cube#7288]
Tried couple of option but did not worked
**Option-1**

`ROUND((${CUBE.spend}) / CAST(${CUBE.clicks} AS FLOAT64), 2)`

**Code**

```
`cpc: {
  sql: ROUND((${CUBE.spend}) / CAST(${CUBE.clicks} AS FLOAT), 2),
  type: `number`,
  title: `CPC`
}`    
```
 
   **Error**
    
`    Internal: This feature is not implemented: Unsupported SQL type Custom(ObjectName([Ident { value: "FLOAT64", quote_style: None }]))`
    

 **Option-2**
    
```
 `cpc: {
  sql: `ROUND((${CUBE.spend}) / CAST(${CUBE.clicks} AS FLOAT), 2)`,
  type: `number`,
  title: `CPC`
}`
```

**Error**
`Internal: Error during planning: Coercion from [Float64, Int64] to the signature Uniform(1, [Float64, Float32]) failed. `

**Comment by ovr** [comment]
Hello @ranjeetranjan ,

The `ROUND` function in Cube Store receives only one argument and always rounds to an integer. 

Thanks

**Comment by ranjeetranjan** [comment]
@ovr You mean to say its not possible round from 0.373134328358209 to 0.37?

**Comment by paveltiunov** [comment]
Duplicate of #6179
