### ISSUE TITLE
Adding CUBEJS_DB_PASSWORD alias for CUBEJS_DB_PASS

### ISSUE THREAD

**Issue by gokulanv** [cube-js/cube#733]
**Describe the bug**
Error: ER_ACCESS_DENIED_ERROR: Access denied for user '<X>'@'<Remote IP Address>' (using password: NO)

**To Reproduce**

Used these keys -
CUBEJS_DB_HOST
CUBEJS_DB_NAME
CUBEJS_DB_PORT
CUBEJS_DB_PASSWORD
CUBEJS_DB_USER
CUBEJS_DB_TYPE
CUBEJS_API_SECRET

Server - 
CubejsServerCore.create({
  dbType: 'mysql',
  schemaPath: path.join('src', 'schema')
}).initApp(app);

When I run a query, I get this error -
Error: ER_ACCESS_DENIED_ERROR: Access denied for user '<X>'@'<Remote IP Address>' (using password: NO)
So, I am not able to connect to remote MySQL DB.

**Comment by vasilev-alex** [comment]
Hi @gokulanv!

This error is most likely caused by wrong credentials/host etc. `Cube.js` does not restrict you from using a remote DB.

Could you try connecting to the DB directly and see if the error persists?
`mysql -u username -pMyPassoword -h example.com`

**Comment by gokulanv** [comment]
@vasilev-alex 
I am able to connect to the DB directly and I am able to connect from a node js app with 'mysql' npm too. But not able to connect with cube.js

Is this config right?

CUBEJS_DB_HOST
CUBEJS_DB_NAME
CUBEJS_DB_PORT
CUBEJS_DB_PASSWORD
CUBEJS_DB_USER
CUBEJS_DB_TYPE
CUBEJS_API_SECRET

Server -
CubejsServerCore.create({
dbType: 'mysql',
schemaPath: path.join('src', 'schema')
}).initApp(app);

**Comment by vasilev-alex** [comment]
ok, looks like you should use `CUBEJS_DB_PASS` over `CUBEJS_DB_PASSWORD`

**Comment by gokulanv** [comment]
Yes, I just saw that from the documentation and changed it. Thanks, works now

**Comment by gokulanv** [comment]
@vasilev-alex Would love to start contributing to CubeJs starting with this issue. Can I make a PR for the same?

**Comment by vasilev-alex** [comment]
@gokulanv yes, would be great!

**Comment by gokulanv** [comment]
@vasilev-alex I have updated all the driver js files to read CUBEJS_DB_PASSWORD as well. Can you please direct me to the instructions to test the changes?

**Comment by vasilev-alex** [comment]
@gokulanv I don't think we have tests for that. You can just run it and see if that works. I'll also take a look at the PR.
