### ISSUE TITLE
duckdb: Add support for more s3 configuration options

### ISSUE THREAD

**Issue by josh-hoiland** [cube-js/cube#7368]
**Is your feature request related to a problem? Please describe.**
I'm working on setting up cube to use duckdb to query parquet files in an s3 bucket. I was hoping to use localstack s3 for testing during development, but am unable to because it's neither SSL nor a vhost url. When I realized localstack wasn't going to work, I set up a real s3 bucket to test against, but I can't authenticate because my organization does not currently allow creating IAM users with long-lived credentials. 
Additionally, we run our production cube cluster in EKS and would love to use IRSA for connecting cube+duckdb to s3.

**Describe the solution you'd like**
- Expose all of the httpfs/duckdb s3 configuration options as environment variables. (e.g. s3_use_ssl, s3_url_style, and s3_session_token)
- Use duckdb's new aws extension to enable using IRSA

**Describe alternatives you've considered**
Looking at the source code, it seems there's an `initSql` field that is run when connecting duckdb, but I couldn't figure out if there was a way to hook into that to set the options I need.

**Additional context**
https://duckdb.org/docs/extensions/httpfs#configuration
https://duckdb.org/docs/extensions/aws

**Comment by joybh98** [comment]
I would like to take this issue.

**Comment by igorlukanin** [comment]
@joybh98 Sure! Please see the contribution guidelines (https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md) and join the `#contributing-to-cube` channel at https://slack.cube.dev

**Comment by igorlukanin** [comment]
I think this one is resolved now. Here are available configuration options: https://cube.dev/docs/product/configuration/data-sources/duckdb#environment-variables
