### ISSUE TITLE
feature: Add InfluxDB support

### ISSUE THREAD

**Issue by wolvever** [cube-js/cube#7376]
**Is your feature request related to a problem? Please describe.**
cube-js supports QuestDB, Materialize, etc. that are capable of running streaming SQL of some kind.  And InfluxDB is a very popular choice in the TSDB space, hope to see cube-js support InfluxDB.

**Describe the solution you'd like**

Support InfluxDB 3.0 using InfluxQL as query language.  I think this would be easier as it's backed by DataFusion.

**Comment by igorlukanin** [comment]
Closing in favor of #7551.
