### ISSUE TITLE
Is there a way to enable simple metric calculations in the Cube.js REST API without requiring them to be pre-defined in the cube?

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7384]
**Problem**

the query json

```json
{
  "query": {
    "measures": [
      "A",
      "B",
     "A+B"
    ]
  }
}
```

Indeed, this approach conflicts with the schema code.  But Perform the calculation of "A+B" solely through the REST API without the need for pre-defined calculations in the cube, can do it?

**Comment by ifokeev** [comment]
Not possible. Why do you need it? you can just do raw queries into your database

**Comment by paveltiunov** [comment]
@w1992wishes You can do it through SQL API.

**Comment by w1992wishes** [comment]
> Not possible. Why do you need it? you can just do raw queries into your database
You are correct, but I want to use semantic isolation and connect to the database.


> @w1992wishes You can do it through SQL API.
ok,i will try. tks

**Comment by w1992wishes** [comment]
sorry. 

Is it possible to implement metric calculations, such as addition, subtraction, multiplication, division, formatting, etc., in the REST API similar to the capabilities provided by the SQL API? Are there convenient hooks for extension, and are there any plans to support this in the future?
