### ISSUE TITLE
Ngx library not comaptible with angular 16 - Missing ivy support

### ISSUE THREAD

**Issue by IvoHohl** [cube-js/cube#7389]
The cube.dev ngx library needs to support ivy because viewEngine rendering ist not supported anymore.

<img width="1709" alt="image" src="https://github.com/cube-js/cube/assets/52882693/30fff5d6-1ae7-46c9-9f46-4cd647dade46">

Other than that, it seems that a type definition in the cube core lib is incorrect 
<img width="1709" alt="image" src="https://github.com/cube-js/cube/assets/52882693/bd51fb8a-a129-4efe-ad11-86f8001eeee3">

**Comment by krabouilleur** [comment]
If the library is not compatible with Ivy, recent Angular projects cannot use it. Is there an update planned?
