### ISSUE TITLE
query concurrency not work

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7397]
When using the v1/load API, I noticed that there are only two connections to the underlying database. I want to increase this value, so I tried the following configuration, but it doesn't seem to have any effect. What am I doing wrong? Is there any other way to achieve this?

```json
orchestratorOptions: {
  queryCacheOptions: {
    queueOptions: {
      concurrency: 25
    }
    externalQueueOptions: {
      concurrency: 25
    }
  }
```

**Comment by w1992wishes** [comment]
CUBEJS_CONCURRENCY is not effective.

**Comment by foolish0** [comment]
Has your configuration taken effect? How is it done?
