### ISSUE TITLE
Clarification of CUBEJS_CONCURRENCY and CUBEJS_DB_MAX_POOL

### ISSUE THREAD

**Issue by schneefux** [cube-js/cube#7413]
I read https://cube.dev/docs/product/faqs/general#what-is-the-difference-between-cubejs_concurrency-and-cubejs_db_max_pool but the relationship between the two variables is still unclear to me.
The example says:
> For example, if your database has a hard concurrency limit of 10 that cannot be changed, but you wish to raise the concurrency limit to 50 you would first set CUBEJS_CONCURRENCY=50 and CUBEJS_DB_MAX_POOL=5 or higher.

  * Above in the FAQ it says that `CUBEJS_CONCURRENCY` should reflect the limitation of my database. Why is it not 10 in the example?
  * When I run multiple API instances, is `CUBEJS_CONCURRENCY` a per instance limit or a global limit? From reading the code, I understand that the connection pool created with `CUBEJS_DB_MAX_POOL` is per instance.

**Comment by igorlukanin** [comment]
Hey @schneefux 👋 

The fragment that you quote is indeed quite confusing—I went ahead and removed it from docs. Thanks for pointing it out, my appreciated! 🙌 

We do have a much better explanation here: https://cube.dev/docs/product/configuration/data-sources#concurrency-and-pooling

Please feel free to follow up and reopen this one if it's still not clear.
