### ISSUE TITLE
Non-external preaggregations do not function when using ClickHouse Cloud

### ISSUE THREAD

**Issue by maxehmookau** [cube-js/cube#7438]
**Describe the bug**

When creating a pre-aggregation and _not using cubestore_, but using ClickHouse Cloud (ClickHouse's IaaS platform) to store the pre-aggregation **the creation fails.**

As a result, it is impossible to define internal preaggregations using ClickHouse when using ClickHouse Cloud.

**To Reproduce**

1. Use ClickHouse Cloud to store _some data_ and create a simple Cube schema to model that data.
2. Define a preaggregation _but do not use cubestore_. Define `external: false` so that the pre-aggregation is stored in ClickHouse.
3. Notice that the creation fails because `CREATE AS SELECT` statements are not supported in ClickHouse Cloud. (See [Compatibility Guide](https://clickhouse.com/docs/en/whats-new/cloud-compatibility#ddl-syntax))

**Expected behavior**
The pre-aggregation should be created in the ClickHouse Cloud database as expected.

**Possible fixes**
* [This line](https://github.com/cube-js/cube/blob/master/packages/cubejs-schema-compiler/src/adapter/ClickHouseQuery.js#L237) will need to be changed. The `CREATE AS SELECT` statement can be replaced with two statements, one to create the table and another to populate it. However, this method only accepts a single query.
* Because it inherits from `BaseQuery`, it may require a more extensive refactor.

**Comment by igorlukanin** [comment]
It is recommended to use Cube Store for storing pre-aggregations: https://cube.dev/docs/product/caching/using-pre-aggregations#pre-aggregations-storage
