### ISSUE TITLE
Is there a way to disable Cube.js query caching?

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7441]
**Problem**

Is there a way to disable Cube.js query caching? I tried setting `refreshKey` to `select now()`, but it didn't completely disable the cache.

**Comment by igorlukanin** [comment]
Hi @w1992wishes 👋 

> Is there a way to disable Cube.js query caching?
Not really, caching is a fundamental part of Cube's architecture. In-memory caching of query results can't be disabled.

> I tried setting refreshKey to select now(), but it didn't completely disable the cache.
Setting refresh keys to relatively low values is something that can get you where you want.

Please also check `queryCacheOptions.refreshKeyRenewalThreshold` from `orchestrator_options`. However, please be advised that tinkering with these parameters are not recommended and would probably lead to a misconfiguration and/or instability of your Cube deployments: https://cube.dev/docs/reference/configuration/config#orchestrator_options
