### ISSUE TITLE
ECDSA SSL keys are not supported

### ISSUE THREAD

**Issue by wasd171** [cube-js/cube#7452]
**Describe the bug**
Trying to use cubejs with a valid ECDSA key throws an error

**To Reproduce**
1) Try to connect cube to a PostgreSQL source with a `CUBEJS_DB_SSL_KEY` that points to a ECDSA key
2) Experience an error `Error: Content of the file from CUBEJS_DB_SSL_KEY is not a valid SSL key`

**Expected behavior**
Cube can connect to the source database

**Version:**
`0.34.24`

**Additional context**
This happens because [source code](https://github.com/cube-js/cube/blob/7826780cb993e6ebf56d9cd69c7ab156a0b63859/packages/cubejs-backend-shared/src/package.ts#L72-L74) specifically checks for a `-----BEGIN RSA PRIVATE KEY-----` string, while ECDSA keys begin with `-----BEGIN EC PRIVATE KEY-----`

**Comment by ovr** [comment]
Hello @wasd171 ,

> This happens because [source code](https://github.com/cube-js/cube/blob/7826780cb993e6ebf56d9cd69c7ab156a0b63859/packages/cubejs-backend-shared/src/package.ts#L72-L74) specifically checks for a -----BEGIN RSA PRIVATE KEY----- string, while ECDSA keys begin with -----BEGIN EC PRIVATE KEY-----

Correct. Would you like to prepare a PR to fix the issue?

Thanks

**Comment by wasd171** [comment]
Hi @ovr, sure, I will prepare it

**Comment by wasd171** [comment]
I have prepared a PR: https://github.com/cube-js/cube/pull/7453
