### ISSUE TITLE
MDX (Multi – Dimensional eXpressions) support

### ISSUE THREAD

**Issue by redpin-pankaj** [cube-js/cube#7457]
**Is your feature request related to a problem? Please describe.**
Our organisation uses Excel with SSAS MDX heavily. It would be great if it supported on cube.dev.

**Describe the solution you'd like**
It would be nice if apart from SQL, REST and GraphQL, the MDX (Multi – Dimensional eXpressions) is also supported. It would allow the cube.dev to better integrate with Microsoft BI tools(like excel, PowerBI etc). Additionally tableau also support MDX(https://help.tableau.com/current/pro/desktop/en-us/cubes.htm) 

FYI, Apache Kylin has support for MDX (https://kylin.apache.org/docs/tutorial/quick_start_for_mdx.html)

**Describe alternatives you've considered**
I have not tried the devart postgres driver for excel, but I am not sure if it is well maintained. I tried to install the driver but it is being blocked by MacOS. 

**Additional context**
NA

**Comment by igorlukanin** [comment]
@gh-pankaj Yep, it would be great to have that!
