### ISSUE TITLE
Grouping by expressions of type GEOGRAPHY is not allowed

### ISSUE THREAD

**Issue by dsoeiro** [cube-js/cube#7463]
How can I use the 'geometry' field in my dataset through both REST and GraphQL, considering the error related to grouping by expressions of type 'GEOGRAPHY'? Are there specific configurations or syntax adjustments needed for both REST and GraphQL to properly handle the 'geometry' field? "Grouping by expressions of type GEOGRAPHY is not allowed"

**Comment by igorlukanin** [comment]
Hi @dsoeiro 👋

Let me copy my reply from Slack: https://cube-js.slack.com/archives/C04NYBJP7RQ/p1701264831878469?thread_ts=1700829976.710859&cid=C04NYBJP7RQ

> This is actually an error on the BigQuery side, not on the Cube side
>
> The error is caused by the fact that Cube generates SQL with “group by” containing all dimensions in your query. So, your geometry dimension appears in the “group by” part of the query, and this is not something that BigQuery can process
>
> Since you defined the geometry dimension as string in the data model, let’s make sure it’s actually a string. Consider re-defining it with a sql expression like `ST_ASGEOJSON(geometry)` — or just any SQL expression that evaluates to string
