### ISSUE TITLE
View doesnt inherit attributes from cubes

### ISSUE THREAD

**Issue by abdel-87** [cube-js/cube#7475]
**Describe the bug**
Views arent inheriting properties from cubes such as titles, and probably also other properties

**To Reproduce**
1. Create a cube with 1 dimension, with a “title” attribute
2. Create a view on top of this cube.
3. Go to playground and search for this dimension. You will see that the “title” is the auto-generated one and not the “title” you put on the cube attribute

**Expected behavior**
The title of the dimension defined in the cube, should be inherited by the view.

**Minimally reproducible Cube Schema**

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  `,
  dimensions: {
    status: {
      sql: `status`,
      title: ‘order status’,
      type: `string`,
    },
  },
});
```

**Version:**
0.34.0

**Comment by igorlukanin** [comment]
I can confirm that titles don't indeed propagate to views. However, I'd like to add that the correct way to check that would be to use the `/meta` endpoint of the REST API.

**Comment by igorlukanin** [comment]
Hey @abdel-87 👋 Please feel free to upgrade to the latest version. This issue was fixed in the PR mentioned above.
