### ISSUE TITLE
Is it possible to implement metric calculations, such as addition, subtraction, multiplication, division, formatting, etc., in the REST API 

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7511]
Apologies, I've asked a similar question in issue #7384. We are considering extensions and would appreciate some assistance. Can you help answer this question?

I noticed that the SQL API, like the REST API, first calls sqlApiLoad and then performs specific metric or dimension calculations on the SQL query results in the code. Therefore, I assume that the REST API can reuse this logic. Is there a way to achieve this?

```sql
SELECT
   char_length(name), floor(count(tc))* 2
FROM
  Orders
  group by name
```

sqlApiLoad param
```json
{
  "measures": [
    "Orders.tc"
  ],
  "dimensions": [
    "Orders.name"
  ],
  "segments": [],
  "limit": 50000
}
```

**Comment by igorlukanin** [comment]
Hi @w1992wishes 👋 

This kind of post-processing is only possible in the SQL API and there’s no way to replicate it in the REST API, other than just writing some code on your side after getting the data from it.

However, what you can also do is to define new dimensions and measures with corresponding [SQL expressions](https://cube.dev/docs/product/data-modeling/syntax#sql-expressions) (e.g., a dimension for char_length(name) and a measures for floor(count(tc))* 2) and then query these new dimensions from the REST API.

Please feel free to continue this conversation on the Slack thread that you've started: https://cube-js.slack.com/archives/C04NYBJP7RQ/p1702433060073009

**Comment by w1992wishes** [comment]
> Hi @w1992wishes 👋
> 
> This kind of post-processing is only possible in the SQL API and there’s no way to replicate it in the REST API, other than just writing some code on your side after getting the data from it.
> 
> However, what you can also do is to define new dimensions and measures with corresponding [SQL expressions](https://cube.dev/docs/product/data-modeling/syntax#sql-expressions) (e.g., a dimension for `char_length(name)` and a measures for `floor(count(tc))* 2)` and then query these new dimensions from the REST API.
> 
> Please feel free to continue this conversation on the Slack thread that you've started: https://cube-js.slack.com/archives/C04NYBJP7RQ/p1702433060073009

Sure, thanks. I'll close this issue for now and continue the discussion on Slack. Please help clarify there.
