### ISSUE TITLE
Symmetric aggregation support in Cube

### ISSUE THREAD

**Issue by MadhusudanN** [cube-js/cube#7512]
I was investigating cube core's semantic layer capability.
As part of this wanted to know how can we model Cubes to take care of Symmetric aggregation.
Details about Symmetric aggregation can be found here ::
https://cloud.google.com/looker/docs/best-practices/understanding-symmetric-aggregates

Also noticed that this has been handled in BI tools like looker. Reference link here :: https://cloud.google.com/looker/docs/reference/param-explore-symmetric-aggregates

Can you please let me know how we can handle Symmetric aggregation in Cube.

**Comment by paveltiunov** [comment]
@MadhusudanN Symmetric aggregates is the solution to chasm and fan trap problem. Cube doesn't implement symmetric aggregates however uses distinct key queries to solve this problem. https://cube.dev/docs/reference/data-model/joins#setting-a-primary-key.
