### ISSUE TITLE
Client Core: Add meta to TS types for cubes and views

### ISSUE THREAD

**Issue by hannosgit** [cube-js/cube#7523]
**Is your feature request related to a problem? Please describe.**
MR https://github.com/cube-js/cube/pull/7327 added a `meta` property to views and cubes, but this change is not yet reflected in the TypeScript types of the Core Client.

**Describe the solution you'd like**
Add the `meta` property to views and cubes in the TypeScript types of the Core Client.

**Comment by igorlukanin** [comment]
Good call @hannosgit! Is it something that you might be willing to contribute?

**Comment by hannosgit** [comment]
I was about to create a mini Pull Request for this, but it seems that @mharrisb1 was faster than me. 😄 
Thank you @mharrisb1 for this and the original Pull Request!

**Comment by mharrisb1** [comment]
@hannosgit np 👍 I should have thought about this in the original PR so thanks for catching
