### ISSUE TITLE
Changing the order of dimensions in a query causes it to produce an error 

### ISSUE THREAD

**Issue by HrisIord** [cube-js/cube#7530]
**Describe the bug**
Changing the order of dimensions in a query produces a the following error: `Error: missing FROM-clause entry for table \"task\"`. Also more generally, when there are multiple join hints for a Cube, sometimes that Cube's table is joined out of order in SQL.

**To Reproduce**
Query:

```js
{
  dimensions: [
    "Application.name",
    "Task.title",
    "Task.updated"
  ],
}
```

Produces the following SQL:

```sql
SELECT
    "application".name "application__name", "library_task".title "task__title", "task".updated "task__updated"
FROM
  public.application AS "application"
  LEFT JOIN public.project AS "project" ON "application".id = "project".application_id
  LEFT JOIN public.library_task AS "library_task" ON "task".standard_id = "library_task".id
  LEFT JOIN public.task AS "task" ON "project".id = "task".project_id
GROUP BY 1, 2, 3 ORDER BY 1 ASC LIMIT 10000
```

Which when executed produces the following error from PostgreSQL: `Error: missing FROM-clause entry for table \"task\"`

**Expected behaviour**
The join to `library_task` in the above SQL should be after the join to `task`.

Also the following query:

```js
{
  dimensions: [
    "Application.name",
    "Task.updated"
    "Task.title",
  ],
}
```

Does actually work and produce data. This poses a problem for our larger system as we can't always predict when the order of dimensions is going to fix an issue like this and when it won't. Also if `Task.updated` is remove from the query the query also fails for the same reason as the "To Reproduce" behaviour.

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Application`, {
  sql: `SELECT * FROM public.application`,
  joins: {
    Project: {
      relationship: `hasMany`,
      sql: `${CUBE}.id = ${Project.applicationId}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    name: {
      sql: `name`,
      type: `string`,
      meta: {
        link: "url",
      },
    },
  },
});

cube(`Project`, {
  sql: `SELECT * FROM public.project`,
  joins: {
    Task: {
      relationship: `hasMany`,
      sql: `${CUBE}.id = ${Task.projectId}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    applicationId: {
      sql: `application_id`,
      type: `number`,
      shown: false,
    },
  },
});

cube(`Task`, {
  sql: `select * from public.task`,
  joins: {
    LibraryTask: {
      relationship: `belongsTo`,
      sql: `${CUBE}.standard_id = ${LibraryTask.id}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    projectId: {
      sql: `project_id`,
      type: `number`,
      shown: false,
    },
    updated: {
      sql: `updated`,
      type: `time`,
    },
    title: {
      sql: `${CUBE.LibraryTask.title}`,
      type: `string`,
    },
  },
});

cube(`LibraryTask`, {
  sql: `select * from public.library_task`,
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    title: {
      sql: `title`,
      type: `string`,
    },
  },
});
```

**Version:**
@cubejs-backend/postgres-driver: ^0.34.33
@cubejs-backend/server: ^0.34.33

**Additional context**
This is I think the same issue at it's core as one I opened in November 2022: https://github.com/cube-js/cube/issues/5580. Apologies for losing track of that one. I also think that difference in behaviour that happens when the dimensions are re-ordered was introduced by the fix for this issue: https://github.com/cube-js/cube/issues/3278. I think before this fix both orders would cause an error.

**Comment by HrisIord** [comment]
Hi @igorlukanin, just sending out a ping on this since I think it might have gotten lost and I'm really hoping someone might have a moment to look at it. My apologies if you're the wrong person to ping, please feel free to redirect.

**Comment by alexindelicato-github** [comment]
Hello @igorlukanin just to provide additional context, this is a blocker and preventing us from upgrading. Any idea how we can move forward would be greatly appreciated. Thanks.

**Comment by igorlukanin** [comment]
Hi @HrisIord @alexindelicato-github 👋 Thanks for a very detailed question—really appreciate it! Also, sorry for a late reply.

I've tried to reproduce this issue with the following data model. This is exactly the one you provided, I just replaced table names with some dummy data:

```js
cube(`Application`, {
  sql: `
    SELECT 1 AS id, 'app_1' AS name
  `,
  joins: {
    Project: {
      relationship: `hasMany`,
      sql: `${CUBE}.id = ${Project.applicationId}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    name: {
      sql: `name`,
      type: `string`,
      meta: {
        link: "url",
      },
    },
  },
});

cube(`Project`, {
  sql: `
    SELECT 11 AS id, 1 AS application_id
  `,
  joins: {
    Task: {
      relationship: `hasMany`,
      sql: `${CUBE}.id = ${Task.projectId}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    applicationId: {
      sql: `application_id`,
      type: `number`,
      shown: false,
    },
  },
});

cube(`Task`, {
  sql: `
    SELECT 101 AS id, 1001 AS standard_id, 11 AS project_id, '2024-01-01'::TIMESTAMP AS updated
  `,
  joins: {
    LibraryTask: {
      relationship: `belongsTo`,
      sql: `${CUBE}.standard_id = ${LibraryTask.id}`,
    },
  },
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
    projectId: {
      sql: `project_id`,
      type: `number`,
      shown: false,
    },
    updated: {
      sql: `updated`,
      type: `time`,
    },
    title: {
      sql: `${CUBE.LibraryTask.title}`,
      type: `string`,
    },
  },
});

cube(`LibraryTask`, {
  sql: `
    SELECT 1001 AS id, 'lib_task_1001' AS title
  `,
  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
      shown: true,
    },
    title: {
      sql: `title`,
      type: `string`,
    },
  },
});
```

When I run it in Cube Cloud, using Postgres as the data source, I get no errors and a correct order of joins regardless of the dimension order in the query.

<img width="1818" alt="Screenshot 2024-01-29 at 14 38 10" src="https://github.com/cube-js/cube/assets/3852894/c7a89f49-144f-43b6-aac4-d70620fcb863">

<img width="1818" alt="Screenshot 2024-01-29 at 14 38 14" src="https://github.com/cube-js/cube/assets/3852894/67cca96c-c22c-4986-8444-160b0b4a4f92">

<img width="1818" alt="Screenshot 2024-01-29 at 14 38 38" src="https://github.com/cube-js/cube/assets/3852894/3c79c656-2844-4840-976e-f1bcb125e76c">

<img width="1818" alt="Screenshot 2024-01-29 at 14 38 34" src="https://github.com/cube-js/cube/assets/3852894/fc3ea47c-fe70-4b51-8d5c-65014a50bd7a">


Also, here's the generated SQL (matches the "correct" one from the first message):

```sql
SELECT
  "application".name "application__name",
  "task".updated "task__updated",
  "library_task".title "task__title"
FROM
  (
    SELECT
      1 AS id,
      'app_1' AS name
  ) AS "application"
  LEFT JOIN (
    SELECT
      11 AS id,
      1 AS application_id
  ) AS "project" ON "application".id = "project".application_id
  LEFT JOIN (
    SELECT
      101 AS id,
      1001 AS standard_id,
      11 AS project_id,
      '2024-01-01' :: TIMESTAMP AS updated
  ) AS "task" ON "project".id = "task".project_id
  LEFT JOIN (
    SELECT
      1001 AS id,
      'lib_task_1001' AS title
  ) AS "library_task" ON "task".standard_id = "library_task".id
GROUP BY
  1,
  2,
  3
ORDER BY
  1 ASC
LIMIT
  5000
```

The only difference in our setup that I see is that I', using Cube 0.34.49 in Cube Cloud. Could you please try the latest version and see if the issue reproduces? Also, if it somehow does, could you please create a free account in Cube Cloud and try reproducing it there? It would greatly help to debug.

**Comment by HrisIord** [comment]
Hi @igorlukanin, thank you for taking the time check this and reply. I tried upgrading to the latest version locally and couldn't reproduce the issue either. Did a quick check in the revision history and I'm fairly sure the fix for https://github.com/cube-js/cube/issues/7663 also fixes this issue. Happy to close this, thanks again!

**Comment by igorlukanin** [comment]
Amazing! Thanks for collaborating on this one 😄
