### ISSUE TITLE
Pre-agg combination of config not sufficiently explained

### ISSUE THREAD

**Issue by jlloyd-widen** [cube-js/cube#7532]
https://github.com/cube-js/cube/blob/cc4092e66d6963be7ceae6dafafd6bdedd2ee40b/docs/pages/reference/data-model/pre-aggregations.mdx#L961

In this section of the docs, it would helpful if it stated that you cannot use the `incremental` key when you are using the `sql` key. 

For that matter, it would significantly help this particular page if some regular attention was made to what combinations of config can/should be used together and what cannot as it related, at least, to pre-aggs.

**Comment by igorlukanin** [comment]
@jlloyd-widen Great suggestion, thank you!
