### ISSUE TITLE
Security Context And Timezone specific Pre aggregations

### ISSUE THREAD

**Issue by pranav-loops** [cube-js/cube#7533]
We can build pre aggregations for specific time zones using https://cube.dev/docs/reference/rest-api#triggering-jobs but this is not possible with the refresh worker.

Say i have `SecurityContext1` which i want to use with `Timezone1` and `SecurityContext2` with `Timezone2`, the only way to ensure the preaggregations are built by the refresh worker is to provide 
```
scheduledRefreshTimeZones: ['timezone1', 'timezone2'],
```
This solves the use case but creates additional pre aggregations which are never used - ie. `SecurityContext1, Timezone2` and `SecurityContext2, Timezone1`

In our case certain security contexts only need to work with specific timezones, but as of now the current configuration provided from the refresh worker, all time zones apply to all security contexts which seems like an overhead too. Is there a way to control this?

Maybe `allowedTimezones` or `defaultTimezone` could be a property within the `securityContext`? Is there any other way to configure different security contexts with different timezones from the refresh worker?

**Comment by igorlukanin** [comment]
Hi @pranav-loops 👋 

I think that making `scheduledRefreshTimeZones` aware of the security context would be the right move here. That way, you would be able to configure specific time zones for specific security contexts—and build only necessary pre-aggregations.

**Comment by igorlukanin** [comment]
Let me close this one in favor of #5015—but please feel free to follow that issue.
