### ISSUE TITLE
Expired slack invite

### ISSUE THREAD

**Issue by rhishikeshj** [cube-js/cube#7559]
Hey,
I want to join the cube slack community but https://slack.cube.dev does not seem to work.
It redirects to https://cube-js.slack.com/join/shared_invite/zt-26280pt2a-7s9n3OcipY~PlbebaJAusA#/shared-invite/error which is expired apparently.

Can you please help me with an invite into the Cube community?

**Comment by ovr** [comment]
Hello @rhishikeshj, Thank you!

cC @igorlukanin

**Comment by rhishikeshj** [comment]
this seems to be fixed now
