### ISSUE TITLE
@cubejs-client/ngx points to module that does not exists

### ISSUE THREAD

**Issue by loremaps** [cube-js/cube#7570]
**Describe the bug**

@cubejs-client/ngx uses `ng-packagr`, which no longer supports ESM5 and FESM5 format (see https://github.com/ng-packagr/ng-packagr/issues/1732). 

@cubejs-client/ngx package.json has `"module": "dist/fesm5/cubejs-client-ngx.js",` which does not exist. We are testing angular's esbuild and this cause the following compile error:

```
An unhandled exception occurred: Failed to resolve entry for package "@cubejs-client/ngx". The package may have incorrect main/module/exports specified in its package.json.
```

**To Reproduce**
1.  run `yarn run build` for @cubejs-client/ngx
2. notice under the `dist` folder, there is no `fesm5`

```
➜ tree -L 2 dist
dist
├── LICENSE
├── README.md
├── bundles
│   ├── cubejs-client-ngx.umd.js
│   └── cubejs-client-ngx.umd.js.map
├── cubejs-client-ngx.d.ts
├── esm2015
│   ├── cubejs-client-ngx.js
│   ├── index.js
│   └── src
├── fesm2015
│   ├── cubejs-client-ngx.js
│   └── cubejs-client-ngx.js.map
├── index.d.ts
└── src
    ├── client.d.ts
    ├── module.d.ts
    ├── public_api.d.ts
    └── query-builder
```

**Expected behavior**

The `module` should point to a valid build

**Version:**
0.34.27

**Comment by HaidarZ** [comment]
The issue appears again in Angular v19
```
An unhandled exception occurred: Failed to resolve entry for package "@cubejs-client/ngx". The package may have incorrect main/module/exports specified in its package.json.
```

The APF is targeting `.js` files which does not exist anymore in the compiled version.
