### ISSUE TITLE
 How to Retrieve Request Information for the SQL API?

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7578]
**Problem**

For the REST API, Cube.js can obtain and report request-related information through initApp. Is there a similar method for the SQL API? How can one retrieve request information related to the SQL API?

**Comment by igorlukanin** [comment]
Hi @w1992wishes 👋 

I believe `initApp` (which is deprecated and not recommended for use) has no relation to this question. However, you can use `extend_context` (https://cube.dev/docs/reference/configuration/config#extend_context) to access some of the request context values. Please try printing them out and see.

> How can one retrieve request information related to the SQL API?

I wonder what exactly you're trying to retrieve—and what is your use case?
