### ISSUE TITLE
Multiple Data Sources Not effective 

### ISSUE THREAD

**Issue by 1043038630** [cube-js/cube#7579]
**Describe the bug**
I tried to configure according to the document, but it didn't take effect  document link: https://cube.dev/docs/product/configuration/advanced/multiple-data-sources#decorated-environment-variables
**To Reproduce**

1.Set the. env file to the following configuration, and then open the schema page to view the tables. It can be found that there is still only one source table
![image](https://github.com/cube-js/cube/assets/45682184/a9813c66-0dd0-45dc-91f3-506c3cdee7f9)
![image](https://github.com/cube-js/cube/assets/45682184/4e3f975b-0f6f-47c9-99f2-65ac004d1f13)

**Expected behavior**

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  UNION ALL
  select 2 as id, 200 as amount, 'new' status
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Version:**
[e.g. 0.29.8]

**Additional context**

**Comment by igorlukanin** [comment]
Hi @1043038630 👋 

> then open the schema page to view the tables. It can be found that there is still only one source table

In Cube Core, the list of tables only shows tables from the default data source. However, you can still define cubes for any data source and query them. I hope it helps clarify what is happening here.
