### ISSUE TITLE
Feedback for “Subquery dimensions”

### ISSUE THREAD

**Issue by leopeng1995** [cube-js/cube#7580]
<img src="https://uploads.linear.app/d9fe61f1-e3d2-4e4f-9912-881c34d5ce24/fd5597e2-15ec-4573-9f97-73ab70668a85/9b83012d-7dc0-476b-a0f1-bcdb24fa969a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Q5ZmU2MWYxLWUzZDItNGU0Zi05OTEyLTg4MWMzNGQ1Y2UyNC9mZDU1OTdlMi0xNWVjLTQ1NzMtOWY5Ny03M2FiNzA2NjhhODUvOWI4MzAxMmQtN2RjMC00NzZiLWEwZjEtYmNkYjI0ZmE5NjlhIiwiaWF0IjoxNzA0MzgyMDIwLCJleHAiOjMzMjc0OTQyMDIwfQ.LtrRHmn3qazEcQ1YLHV0vWBzm_Lp3RvAbwuRSR7M0PI " alt="Screenshot 2024-01-02 at 12.53.40.png" width="884" height="641" />

- [X] Fix
- [ ] Reply on GitHub

**Comment by igorlukanin** [comment]
@leopeng1995 Thanks for reporting this! I'll make sure it's fixed.

**Comment by igorlukanin** [comment]
@leopeng1995 These images are fixed now, thanks again!
