### ISSUE TITLE
How does SQL API handle monitoring?

### ISSUE THREAD

**Issue by tiger-feng** [cube-js/cube#7583]
**Failed SQL**
Search for `Failed SQL` log message.

**Logical Plan**
Search for `Can't rewrite plan` log message.

**Version:**
[e.g. 0.4.5]

**Additional context**

**Comment by igorlukanin** [comment]
Hi @zhoufeng215207 👋 I\m not sure I fully understand your question. Could you please elaborate? What are you trying to achieve?

**Comment by zhoufeng215207** [comment]
> 你好@zhoufeng215207👋我不确定我完全理解你的问题。您能详细说明一下吗？你想达到什么目的？

In the REST API, it can be configured via initApp to handle monitoring or observability solutions, how does it handle in the SQL API

**Comment by igorlukanin** [comment]
I don't think I fully understand the question here. What exactly would you like to monitor? Please elaborate.

**Comment by igorlukanin** [comment]
Please feel free to reopen if you have more context.
