### ISSUE TITLE
Feedback for “Working with Joins”

### ISSUE THREAD

**Issue by thePermission** [cube-js/cube#7607]
![image](https://github.com/cube-js/cube/assets/40363242/6dee14b4-1717-4af8-97f8-b4274ac3f79c)

In a junction table the relationship is exactly the opposit of whats shown on the diagramm, isn't it?
One post ist found in many lines of posts_topics.
One topic is found in many lines of posts_topics
One posts_topic only belongs to one posts line.
One posts_topic only belongs to one topic line.
If i am wrong let me know, but i dont get the example this way. All relationships are wrong in my opinions.

Shouldn't it look more like this?
![image](https://github.com/cube-js/cube/assets/40363242/afd524be-7516-491e-845a-3f969aa4c336)

Greetings

Sascha

**Comment by igorlukanin** [comment]
Hey Sascha @thePermission 👋 I think you're 100% right. It looks like a bug in docs, I'll make sure it's fixed. Thanks for reporting!

**Comment by thePermission** [comment]
I guess thats the same issue here?
https://cube.dev/docs/product/data-modeling/concepts/working-with-joins#directions-of-joins

thx for your answer

**Comment by igorlukanin** [comment]
@thePermission Re: same issue. Could you please point to where exactly? There's no diagram by the link—or I'm just looking not too thoroughly.

**Comment by thePermission** [comment]
![image](https://github.com/cube-js/cube/assets/40363242/24385556-9ffa-4869-88ce-5cc71e15487e)
https://cube.dev/docs/product/data-modeling/concepts/working-with-joins#using-virtual-associative-cube

**Comment by igorlukanin** [comment]
The diagram in question has been fixed some time ago.
