### ISSUE TITLE
[DuckDB] Add support for duckdb connection via database file

### ISSUE THREAD

**Issue by tehunter** [cube-js/cube#7653]
**Is your feature request related to a problem? Please describe.**
I am working with cube in a local docker environment. I'd like to use duckdb as my database engine, but there is only support for using duckdb `:memory:` connections against an S3 endpoint. In my setup, I have connected duckdb to a local database file.

**Describe the solution you'd like**
Add an environment variable like `CUBEJS_DB_DUCKDB_CONNECTION` which could take the value of `:memory:`, a string to a database file connection, or other type of connection (e.g., `md:`).

**Describe alternatives you've considered**
I've tried using PostgreSQL over duckdb, but the performance and features were lacking as PostgreSQL isn't optimized as an analytics database.

**Additional context**
Here are the relevant lines:
https://github.com/cube-js/cube/blob/377260653026401b36aab45f0dad9ec93e0c524d/packages/cubejs-duckdb-driver/src/DuckDBDriver.ts#L58-L63

**Comment by JichaoS** [comment]
+1 here's a PR that does it: https://github.com/luabase/cube/commit/37f56fe8833a6ee1836de2cd1bbdb4d44a96fbd0

**Comment by igorlukanin** [comment]
Thanks for your [contribution](https://cube.dev/blog/cube-core-v0-35-updates-to-data-modeling-and-data-sources#local-database-path-for-duckdb), @JichaoS 🙌
