### ISSUE TITLE
Wrong join order

### ISSUE THREAD

**Issue by KroneCorylus** [cube-js/cube#7663]
**Describe the bug**

Cubejs query generator seems to ignore the join path defined in the view generating a invalid query with joins in the wrong order.
I made a simple example to show the problem.

**To Reproduce**
1. Clone the [bug-example-repo](https://github.com/KroneCorylus/cubejs-bug-report)
2. run `docker compose up`
3. In the playground or API make the following query:
```
{
  "measures": [
    "Product_Stock.quantity"
  ],
  "dimensions": [
    "Product_Stock.sub_category",
    "Product_Stock.brand"
  ],
  "order": {
    "Product_Stock.quantity": "desc"
  }
}
```
![image](https://github.com/cube-js/cube/assets/26716702/53f7a758-f27e-44a9-b17f-ae4d71f93c1a)
That produces the following sql query
```
SELECT
  "sub_category".description "product__stock__sub_category",
  "brand".description "product__stock__brand",
  sum("fact".quantity) "product__stock__quantity"
FROM
  fact AS "fact"
  LEFT JOIN product AS "product" ON "fact".id_product = "product".id_product
  LEFT JOIN sub_category AS "sub_category" ON "product".id_sub_category = "sub_category".id_sub_category
  LEFT JOIN brand AS "brand" ON "model".id_brand = "brand".id_brand
  LEFT JOIN model AS "model" ON "product".id_model = "model".id_model
GROUP BY
  1,
  2
ORDER BY
  3 DESC
LIMIT
  10000
```
**Expected behavior**
As you can see the table brand is joined before model. should be the inverse like this
```
SELECT
  "sub_category".description "product__stock__sub_category",
  "brand".description "product__stock__brand",
  sum("fact".quantity) "product__stock__quantity"
FROM
  fact AS "fact"
  LEFT JOIN product AS "product" ON "fact".id_product = "product".id_product
  LEFT JOIN sub_category AS "sub_category" ON "product".id_sub_category = "sub_category".id_sub_category
  LEFT JOIN model AS "model" ON "product".id_model = "model".id_model
  LEFT JOIN brand AS "brand" ON "model".id_brand = "brand".id_brand
GROUP BY
  1,
  2
ORDER BY
  3 DESC
LIMIT
  10000
```

**Minimally reproducible Cube Schema**
[Cubes](https://github.com/KroneCorylus/cubejs-bug-report/blob/main/schema/cubes.js)
[View](https://github.com/KroneCorylus/cubejs-bug-report/blob/main/schema/views.js)

**Version:**
latest docker version (0.34.43 as today)

**Additional context**
I encounter this problem after updating to 0.34.43, but working fine on 0.34.11.
Also if you add the model dimension before the brand it works.

**Comment by paveltiunov** [comment]
@KroneCorylus Thanks for thorough test case!
