### ISSUE TITLE
When using Cubestore with a remote dir that is backed by Azure Blob Storage, an extremely high number of List operations are executed per day

### ISSUE THREAD

**Issue by mfclarke-cnx** [cube-js/cube#7669]
**Describe the bug**
When configuring Cubestore to use a remote dir for storage, and that remote dir is Azure Blob Storage mounted via BlobFuse, an extremely high number of List operations are performed per day (millions). The cost of this is very high (hundreds of $ per day), with a single Cubestore cluster with 2 workers.

**To Reproduce**
1. Deploy Cube and Cubestore, with a Cube schema containing pre-aggregations, with Cubestore configured to use a remote dir connected to Azure Blob Storage via BlobFuse
2. Wait a day
3. Observe millions of List operations have been performed

**Expected behavior**
Much lower number of List operations are performed.

**Version:**
0.34.23

**Additional Context:**
I think it's to do with this functionality: https://github.com/cube-js/cube/pull/4093/files

If I understand correctly, after each file is uploaded it is checked in case the consistency of the underlying FS isn't strongly consistent. It does this by using a list operation to check that the file exists. This list operation recurses through the entire directory, which on Azure Blob Storage would use many List calls, depending on how many parquet files are in the folder already.

Rather than checking the underlying FS is strongly consistent with a full scan of the directory on every single file upload, it would be better to check it once on mount / start up.

**Comment by paveltiunov** [comment]
@mfclarke-cnx I feel this one is a consequence of using BlobFuse. There's no support for Azure Blob Storage in Cube Core. In Cube Cloud this place is implemented differently for Azure.
