### ISSUE TITLE
Feedback for “Deploying Cube Core with Docker”

### ISSUE THREAD

**Issue by spljs** [cube-js/cube#7678]
Hello, i just have noticed a bad template placeholder in your documentation. Check the `%CURRENT_VERSION` . I think it should display the last version of cube instead of this ? 
See for example : https://cube.dev/docs/product/deployment/core#update-to-the-latest-version

Regards,

**Comment by igorlukanin** [comment]
Thanks for reporting, @spljs! Fixed in 2e89e2b5af9355362608f65125655166f21c4b3d.
