### ISSUE TITLE
Trigger pre-aggregation build jobs via /v1/pre-aggregations/jobs REST API no more working from version 0.34.44.

### ISSUE THREAD

**Issue by scakkia** [cube-js/cube#7726]
**Bud description:**
We use to trigger some pre-aggregations from an external scheduler that performs a POST on /v1/pre-aggregations/jobs with the cubes that need to be built.

Since version 0.34.44 the default renewalThreshold value of 300 seconds is no longer respected and the build is never launched.
I see different behavior in versions with LOG_LEVEL=trace on the API instance.

Probably the issue was introduced in this commit https://github.com/cube-js/cube/pull/7646

cc @ovr @paveltiunov 

**Version:**
0.34.44+

**Comment by ovr** [comment]
Hello @scakkia ,

Thank you for submitting the issue! Fixed & released in [v0.34.62](https://github.com/cube-js/cube/releases/tag/v0.34.62). Could you give it a try?

Thanks

**Comment by scakkia** [comment]
Hi @ovr 

works fine now

Thanks
