### ISSUE TITLE
What tools and indicators (metrics) does cube -js have for monitoring and tracking cube-js performance?

### ISSUE THREAD

**Issue by MuravevAV** [cube-js/cube#7732]
What tools and indicators (metrics) does cube-js have to monitor and track the performance of cube-js? For example, we want to track how a Cube-js instance is using CPU and memory based on the number of user sessions, the number of active models, the number of concurrent database queries, etc. How to implement such a "Cube-JS performance monitor"? Are there any ready-made Cube-js metrics?

**Comment by paveltiunov** [comment]
Duplicate of #2920
