### ISSUE TITLE
Playground 2.0

### ISSUE THREAD

**Issue by Namec999** [cube-js/cube#7733]
Hello All,

any schedule for the release of cube playground 2.0.

i want to add some features, that are already existing in v 2.0.

if the release date, i'll be forced to do same things

such a waste of time

best and let the force be with you

**Comment by igorlukanin** [comment]
Hi @Namec999 👋 

Please see this blog post: https://cube.dev/blog/introducing-playground-2#try-playground-20-today

Basically:
- Playground 2.0 is already available to all Cube Cloud users on all plans.
- Now, we're hunting bugs, adding features that were present in 1.0, and polishing Playground 2.0.
- We plan to move Playground 2.0 to Cube Core and make it open source after we're sure it's polished enough.

That being said, there's no exact timeline that I can share. Please stay tuned for the updates in the blog.
