### ISSUE TITLE
REST API method to get cubes meta doesn't returns custom metadata

### ISSUE THREAD

**Issue by aaa-user** [cube-js/cube#7740]
**Is your feature request related to a problem? Please describe.**
I want to use [`meta` parameter](https://cube.dev/docs/reference/data-model/cube#meta) of cubes to customize frontend visualisation for this cubes. But I can't get field `meta` using method [/v1/meta](https://cube.dev/docs/reference/rest-api#v1meta). Is there another ways to read custom metadata?

**Describe the solution you'd like**
I find it logical to add field [`meta`](https://cube.dev/docs/reference/data-model/cube#meta) into response of method [/v1/meta](https://cube.dev/docs/reference/rest-api#v1meta)

**Comment by hannosgit** [comment]
Hi @aaa-user ,
[/v1/meta](https://cube.dev/docs/reference/rest-api#v1meta) does return `meta` of the cube.
However this feature is only available since version https://github.com/cube-js/cube/releases/tag/v0.34.35.
Which version did you use?
The documentation(https://cube.dev/docs/reference/rest-api#v1meta) is missing `meta`  by mistake.

**Comment by paveltiunov** [comment]
@hannosgit Could you please provide PR to the Cube repo? Thanks!

**Comment by hannosgit** [comment]
@paveltiunov done, see https://github.com/cube-js/cube/pull/7748

**Comment by aaa-user** [comment]
Thanks a lot. I see changes in docs. But I face with error in playground, when paste example meta from [docs](https://cube.dev/docs/reference/data-model/cube#meta) in my cube:
```
Compile errors:
CubeName cube: (meta = [object Object]) is not allowed
```
Example is:
```
  meta: {
    any: `value`
  }
```
What I do wrong? Sorry for silly question.

**Comment by hannosgit** [comment]
@aaa-user Which cube version do you use?

**Comment by aaa-user** [comment]
Local version was 0.33.47, I've updated it to 0.34.55 and error have dissapeared. Thank you!

**Comment by hannosgit** [comment]
@aaa-user so this can be closed?

**Comment by aaa-user** [comment]
Yes, question is solved.
