### ISSUE TITLE
Adding date after filter in pre aggregation 

### ISSUE THREAD

**Issue by pujak8542** [cube-js/cube#7741]
I was trying to create a pre aggregation with a date filter have dateAfter "same date". But adding the field in dimension of pre aggregation is not working. How can I add this in the pre aggregation? Also I have the same field as normal dimension and again I am applying that dimension into the filter to get the afterDate

**Comment by igorlukanin** [comment]
Hi @pujak8542 👋 

I'm sorry, I don't think I fully follow your question.

> I was trying to create a pre aggregation with a date filter have dateAfter "same date"

Could you please explain again, with as much detail as you can?

**Comment by igorlukanin** [comment]
Please feel free to reopen if this is still an issue.
