### ISSUE TITLE
Cube.js Refresh Worker Crashes Due to JavaScript Heap Out of Memory Error

### ISSUE THREAD

**Issue by kaizendae** [cube-js/cube#7762]
**Problem**
Cube refresh worker deployment keeps restarting.
Following are the logs
```
🚀 Cube API server (0.34.41) is listening on 4000
{"message":"Refresh Scheduler Interval","warning":"Previous interval #1 was not finished with 30000 interval"}
...
<--- Last few GCs --->

[1:0x64df540]   849230 ms: Mark-sweep (reduce) 1900.3 (2083.1) -> 1897.4 (2083.1) MB, 3190.8 / 0.2 ms  (average mu = 0.271, current mu = 0.202) allocation failure scavenge might not succeed
[1:0x64df540]   852508 ms: Mark-sweep (reduce) 1898.5 (2083.1) -> 1897.4 (2083.1) MB, 2745.7 / 0.3 ms  (average mu = 0.225, current mu = 0.162) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb090e0 node::Abort() [node]
 2: 0xa1b70e  [node]
 3: 0xce1a20 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce1dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe99435  [node]
 6: 0xe99f16  [node]
 7: 0xea843e  [node]
 8: 0xea8e80 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeabdfe v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe6d33a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11e61e6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15d9e59  [node]
```
**Cube Refresh Worker Deployment**
```apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cube-refresh-worker
  name: cube-refresh-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      service: cube-refresh-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: cube-refresh-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env: # Refer to https://cube.dev/docs/reference/environment-variables for more options
            - name: CUBEJS_CUBESTORE_HOST
              value: "cubestore"
            - name: CUBEJS_REFRESH_WORKER
              value: "true"
            - name: CUBEJS_LOG_LEVEL
              value: "warn"
            - name: CUBEJS_PRE_AGGREGATIONS_BUILDER
              value: "true"
          envFrom:
            - secretRef:
                name: cube-api-secrets
          image: MY_IMAGE
          name: cube-refresh-worker
          resources:
            requests:
              memory: 4Gi
              cpu: 1000m
            limits:
              memory: 6Gi
              cpu: 1500m
      restartPolicy: Always
```

**Memory Utilization**

I'm considering increasing the memory requests, is cube refresh worker supposed to be memory hungry and what might be causing this much consumption?

<img width="707" alt="image" src="https://github.com/cube-js/cube/assets/17480866/199add39-8ee1-4d3e-877a-e9300fbaeb35">

**Comment by yashodhan271** [comment]
The Cube.js Refresh Worker can indeed become memory-intensive, especially when handling large datasets or complex pre-aggregations. The error logs and deployment configuration you provided indicate that the Node.js process is running out of memory despite the allocated 4-6Gi, suggesting significant memory demand from your operations.

### Reasons for High Memory Consumption

1. **Complex Pre-aggregations**: If your pre-aggregations are very complex or involve large datasets, building these can consume a lot of memory. This is particularly true if multiple pre-aggregations are being built simultaneously.

2. **High Data Volume**: Processing high volumes of data, especially when performing operations that require holding significant portions of this data in memory, can quickly exhaust available resources.

3. **Inefficient Queries**: Some queries might be inefficiently written, causing more data to be loaded and processed than necessary.

4. **Memory Leaks**: Less likely in a mature framework like Cube.js, but custom code or certain usage patterns could introduce memory leaks.

### Solutions and Optimizations

1. **Increase Memory Limits**: Increasing the memory limit is a straightforward solution but might only be a temporary fix if underlying issues of efficiency are not addressed.

2. **Optimize Pre-aggregations**: Review your pre-aggregation strategy. Ensure that you're only pre-aggregating what's necessary and doing so in the most efficient manner possible. Sometimes, splitting a large pre-aggregation into smaller, more focused ones can help.

3. **Parallelization and Scaling**: Cube.js supports horizontal scaling. You could deploy more instances of the refresh worker to distribute the load, but this requires coordination and efficient distribution of tasks to be effective.

4. **Query Optimization**: Review the queries that trigger pre-aggregations or any custom logic that runs during the refresh. Optimize these to reduce memory consumption.

5. **Monitoring and Profiling**: Utilize monitoring tools to identify when and where the memory spikes occur. Profiling the Node.js application can help identify memory leaks or inefficient memory usage patterns.

6. **Adjust Refresh Schedules**: If possible, adjust the schedules of pre-aggregations to ensure that not too many heavy operations are running simultaneously.

### Configuration Adjustments

Given your current setup, consider these immediate adjustments:

- **Incrementally Increase Memory Allocation**: While you've considered increasing memory requests, also review and adjust the limits based on actual usage patterns and after implementing any possible optimizations.
  
- **Environment Variable Tuning**: Experiment with Node.js and Cube.js environment variables that could influence performance and memory usage. For example, increasing the `--max-old-space-size` as mentioned previously or adjusting Cube.js settings that control concurrency and batch sizes.

- **Review Kubernetes Limits**: Ensure that your Kubernetes cluster has enough resources to handle the increased requests and limits. Kubernetes will restart pods that exceed their limits, but it also needs to have enough resources to schedule the pods with higher requests.

**Comment by igorlukanin** [comment]
Hi @kaizendae 👋 

I see `replicas: 4` in your config file. Does that mean that you run four instances of Refresh Worker? If so, please run only one instance. Anything above one is not a supported nor recommended configuration.

Please also see the docs: https://cube.dev/docs/product/deployment/production-checklist#memory-and-cpu

Indeed, Refresh Worker is memory hungry.

> Refresh workers tend to be much more CPU and memory intensive, so at least 6GB of RAM is recommended. Please note that to take advantage of all available RAM, the Node.js heap size should be adjusted accordingly by using the --max-old-space-size option:
> `NODE_OPTIONS="--max-old-space-size=6144"`

I would probably try both increasing the available memory to the Refresh Worker and reviewing the configuration of pre-aggregations. Maybe splitting them into smaller partitions or running them on a different schedule would help reduce the load on the Refresh Worker.

**Comment by kaizendae** [comment]
Thank you @igorlukanin very helpful comment
