### ISSUE TITLE
what's track.cube.dev and why my project is downloading from track.cube.dev with thousands of times everyday

### ISSUE THREAD

**Issue by Alice0000001111111** [cube-js/cube#7800]
**Problem**

A clear and concise description of what the problem is. Ex. How can I do X with Cube.js? [...]

I am using cubejs and made a web application with it. Recently security team find a security vulnerability, they said my project is downloading from track.cube.dev with thousands of times everyday. 

My project setting: 

**Related Cube.js node server code**

```javascript
import CubejsServerCore from '@cubejs-backend/server-core';

app.use(logger('dev'));

const queueOptions = {
  concurrency: 8,
};
CubejsServerCore.create({
  orchestratorOptions: {
    queryCacheOptions: {
      // refreshKeyRenewalThreshold: 200,
      backgroundRenew: true,
      queueOptions,
    },
    preAggregationsOptions: { queueOptions },
  },
}).initApp(app);
```

**Comment by Alice0000001111111** [comment]
```javascript 
    "@cubejs-backend/mysql-driver": "^0.13.12",
    "@cubejs-backend/prestodb-driver": "^0.19.61",
    "@cubejs-backend/server": "^0.29.28",
    "@cubejs-backend/server-core": "^0.20.0",
    "@cubejs-client/react": "^0.29.24",
```

**Comment by Alice0000001111111** [comment]
@igorlukanin  can you please help urgently as this is security related, or I will need to close the project

**Comment by ovr** [comment]
Hello @Alice0000001111111 ,

Cube collects high-level anonymous usage statistics for servers started in development mode. It doesn't track any credentials, data model contents, or queries issued. This statistic is used solely for the purpose of constant Cube improvement.

You can disable it by passing: `telemetry: false`

https://cube.dev/docs/reference/configuration/config#telemetry

Thanks
