### ISSUE TITLE
CUBESTORE Not Working in Production Mode. 

### ISSUE THREAD

**Issue by seatunneltrailuser** [cube-js/cube#7886]
In the Router we get 
ERROR [cubestore::cluster] <pid:1> Network error: Corrupted message received. Please check your worker and meta connection environment variables.
In the Refresh Worker, we get 
{"message":"Refresh Scheduler Error","error":"Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)","securityContext":{},"requestId":"scheduler-31fc6136-2e40-4ab5-9a4d-aed48676800a"}

We even stopped the Refresh worker, and this error stopped on both Router and Refresh worker, but when we executed any query from CubeJS the Router got the same error and the Worker 1 received Socket closed exception

We have the following configuration 

**Router**
docker run -d -p 9999:9999 -p 3030:3030 -p 3306:3306 --network='bridge' --rm --name router \
  -e CUBESTORE_JOB_RUNNERS=4 \
  -e CUBESTORE_QUERY_TIMEOUT=180 \
  -e CUBESTORE_SELECT_WORKERS=4 \
  -e CUBESTORE_WORKERS=10.x.x.82:10001,10.x.x.83:10002 \
  -e CUBESTORE_SERVER_NAME=10.x.x.80:9999 \
  -e CUBESTORE_BIND_ADDR=0.0.0.0:3306 \
  -e CUBESTORE_META_PORT=9999 \
  -e CUBESTORE_HTTP_BIND_ADDR=0.0.0.0:3030 \
  -e CUBESTORE_REMOTE_DIR=/cube/remote \
  -e CUBESTORE_DATA_DIR=/cube/data \
  -e CUBEJS_API_SECRET=<our_secret_key> \
  -e CUBEJS_JWT_ALGS=HS256 \
  -e CUBEJS_JWT_KEY=<our_secret_key> \
  -v /<shared_volume_mounted_on_host>/meta_N_cache:/cube/data:z \
  -v /<shared_volume_mounted_on_host>/remote_dir:/cube/remote:z \
 cubejs/cubestore:latest

**Worker 1**
docker run -d -p 10001:10001 --network='bridge' --rm --name worker1 \
  -e CUBESTORE_JOB_RUNNERS=4 \
  -e CUBESTORE_QUERY_TIMEOUT=180 \
  -e CUBESTORE_SELECT_WORKERS=4 \
  -e CUBESTORE_SERVER_NAME=10.x.x.82:10001 \
  -e CUBESTORE_WORKERS=10.x.x.82:10001 \
  -e CUBESTORE_WORKER_PORT=10001 \
  -e CUBESTORE_META_ADDR=10.x.x.80:9999 \
  -e CUBESTORE_DATA_DIR=/cube/data \
  -e CUBESTORE_REMOTE_DIR=/cube/remote \
  -e CUBEJS_API_SECRET=<our_secret_key> \
  -e CUBEJS_JWT_ALGS=HS256 \
  -e CUBEJS_JWT_KEY=<our_secret_key> \
   -v /<shared_volume_mounted_on_host>/meta_N_cache:/cube/data:z \
   -v /<shared_volume_mounted_on_host>/remote_dir:/cube/remote:z \
   cubejs/cubestore:latest

**Worker 2**
docker run -d -p 10001:10001 --network='bridge' --rm --name worker2 \
  -e CUBESTORE_JOB_RUNNERS=4 \
  -e CUBESTORE_QUERY_TIMEOUT=180 \
  -e CUBESTORE_SELECT_WORKERS=4 \
  -e CUBESTORE_SERVER_NAME=10.x.x.83:10002 \
  -e CUBESTORE_WORKERS=10.x.x.83:10002 \
  -e CUBESTORE_WORKER_PORT=10002 \
  -e CUBESTORE_META_ADDR=10.x.x.80:9999 \
  -e CUBESTORE_DATA_DIR=/cube/data \
  -e CUBESTORE_REMOTE_DIR=/cube/remote \
  -e CUBEJS_API_SECRET=<our_secret_key> \
  -e CUBEJS_JWT_ALGS=HS256 \
  -e CUBEJS_JWT_KEY=<our_secret_key> \
   -v /<shared_volume_mounted_on_host>/meta_N_cache:/cube/data:z \
   -v /<shared_volume_mounted_on_host>/remote_dir:/cube/remote:z \
   cubejs/cubestore:latest

**Cube**
docker run -d -p 3000:3000 -p 4000:4000 --network='bridge' --rm --name cube \
  -e CUBEJS_DEV_MODE=false \
  -e CUBEJS_DB_HOST=10.x.x.81 \
  -e CUBEJS_DB_PORT=8123 \
  -e CUBEJS_DB_NAME=<dbname> \
  -e CUBEJS_DB_USER=<db_user> \
  -e CUBEJS_DB_PASS=<password> \
  -e CUBEJS_DB_TYPE=clickhouse \
  -e CUBEJS_CUBESTORE_HOST=10.x.x.80 \
  -e CUBEJS_CUBESTORE_PORT=9999 \
  -e CUBEJS_API_SECRET=<our_secret_key> \
  -e CUBEJS_JWT_ALGS=HS256 \
  -e CUBEJS_JWT_KEY=<our_secret_key> \
  -v /<shared_volume_mounted_on_host>:/cube/conf:z \
  cubejs/cube:latest  

**Refresh Worker**
docker run -d  --network='bridge' --rm --name refreshworker \
  -e CUBEJS_DEV_MODE=false \
  -e CUBEJS_DB_HOST=10.x.x.81 \
  -e CUBEJS_DB_PORT=8123 \
  -e CUBEJS_DB_NAME=<dbname> \
  -e CUBEJS_DB_USER=<db_user> \
  -e CUBEJS_DB_PASS=<password> \
  -e CUBEJS_DB_TYPE=clickhouse \
  -e CUBEJS_CUBESTORE_HOST=10.x.x.82 \
  -e CUBEJS_CUBESTORE_PORT=9999 \
  -e CUBEJS_API_SECRET=<our_secret_key> \
  -e CUBEJS_JWT_ALGS=HS256 \
  -e CUBEJS_JWT_KEY=<our_secret_key> \
  -v /<shared_volume_mounted_on_host>:/cube/conf:z \
  cubejs/cube:latest  

**Version:**
[e.g. 0.4.5]

**Additional context**

**Comment by seatunneltrailuser** [comment]
**RefreshWorker**
additionally we set the following in for the refresh worker
-e CUBEJS_REFRESH_WORKER=true \

**Version**
Docker latest version for  cube & Cubestore.

**Comment by ovr** [comment]
Hello @seatunneltrailuser ,

You have a misconfiguration. `CUBEJS_CUBESTORE_PORT` for Cube/RS must point to `CUBESTORE_HTTP_BIND_ADDR` which is  `3030`, not `9999` (it's meta store port).

Thanks

**Comment by seatunneltrailuser** [comment]
ah!! Good catch.  After modifying the CUBEJS_CUBESTORE_PORT to 3030, it started to work like charm!!  Thank you @ovr for the right pointer, you saved my time.
