### ISSUE TITLE
update /revalidate query on onUpdate

### ISSUE THREAD

**Issue by Namec999** [cube-js/cube#7888]
Hello All,

curently stuck getting my chart to render my new updated query after using this : 

await onUpdate({ limit: parseInt(newLimit) });

but when using other updatemembers props everything works great

is there any solution to revalidate the query programaticaly 

best

**Comment by igorlukanin** [comment]
Hi @Namec999 👋 

I'm sorry but I can't parse your question. Could you please provide more context?
