### ISSUE TITLE
Facing problems using the securityContext in Python

### ISSUE THREAD

**Issue by carlosabreuhdata** [cube-js/cube#7910]
**Describe the bug**
Getting error trying to use securityContext on cube.cloud. Running locally works fine.

**To Reproduce**

docker-compose
<img width="396" alt="image" src="https://github.com/cube-js/cube/assets/156125028/ef5dd056-3a92-48e5-9165-d77ffdb9170a">

cube.py

<img width="836" alt="image" src="https://github.com/cube-js/cube/assets/156125028/73fd7a61-1a2c-4445-941e-0511308b0f1e">

globals.py

<img width="833" alt="image" src="https://github.com/cube-js/cube/assets/156125028/90c0836d-e5ca-4462-b7e1-d3b3001c2351">

When I load the playground I receive a warning because it’s correct, I’m not sending the schema_name on the securityContext yet….

<img width="854" alt="image" src="https://github.com/cube-js/cube/assets/156125028/25a1d84d-b8fc-42af-9b2c-26ad56576450">

After I inform the schema_name as follows…

<img width="855" alt="image" src="https://github.com/cube-js/cube/assets/156125028/fe46e70c-a142-4a35-a878-e0f64e7acb1c">

Works perfectly fine locally...

In my data cube is where I use this parameter

<img width="855" alt="image" src="https://github.com/cube-js/cube/assets/156125028/356729fe-8c9d-4ed1-9f31-07cefbcbdc58">

Now, when I try to run the same structure on cube cloud the securityContext shows "None" and breaks the application.

<img width="842" alt="image" src="https://github.com/cube-js/cube/assets/156125028/15e3a5d4-b093-4512-94a2-fe3e7b47ad19">

**Expected behavior**

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  UNION ALL
  select 2 as id, 200 as amount, 'new' status
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Version:**
[e.g. 0.4.5]

**Additional context**

**Comment by allekai** [comment]
In my case I unknowingly used an expired JWT in a development mode cube. That resulted in the behavior described above. Once I changed the "exp" value of the JWT, it started working again.
