### ISSUE TITLE
first query extremely slow

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#7912]
**Problem**
In production mode, I set the parameter CUBEJS_CACHE_AND_QUEUE_DRIVER to 'memory', and I did not set CUBEJS_CUBESTORE_HOST. Why is the first query extremely slow, taking over 100s, but subsequent queries are normal? What could be the issue with this usage?

**Comment by igorlukanin** [comment]
Hi @w1992wishes 👋 

Why do you think the query duration is connected to `CUBEJS_CACHE_AND_QUEUE_DRIVER` or `CUBEJS_CUBESTORE_HOST`?

What is the data source that you use? Which query do you run? How much data is there in the tables that are used to run the query? If you run the same query directly against the data source without Cube, how long would it take?

Additional context is really needed here.

**Comment by w1992wishes** [comment]
> Hi @w1992wishes 👋
> 
> Why do you think the query duration is connected to `CUBEJS_CACHE_AND_QUEUE_DRIVER` or `CUBEJS_CUBESTORE_HOST`?

When I use CUBEJS_CUBESTORE_HOST without setting CUBEJS_CACHE_AND_QUEUE_DRIVER, the first query takes 3-4 seconds. However, when I set CUBEJS_CACHE_AND_QUEUE_DRIVER = memory without setting CUBEJS_CUBESTORE_HOST, the first query takes over 120 seconds. The only difference lies here. Additionally, when I set 'backgroundRenew': True, the first query also takes 3-4 seconds, but using this parameter leads to a higher error rate during stress testing.

> 
> What is the data source that you use? Which query do you run? How much data is there in the tables that are used to run the query? If you run the same query directly against the data source without Cube, how long would it take?

What is the data source that you use?                                                                                       --mysq
Which query do you run?                                                                                                           --without group query
How much data is there in the tables that are used to run the query?                                     --1600000 rows
 the same query directly against the data source without Cube, how long would it take?       -- 3-4ms

**Comment by igorlukanin** [comment]
> Which query do you run? --without group query

@w1992wishes Sorry, I did not get that. Could you please copy and paste the SQL that Cube generates?

I also assume that you use pre-aggregations. Could you please show how the cube is defined, including the relevant pre-aggregation?

**Comment by w1992wishes** [comment]
> @w1992wishes Sorry, I did not get that. Could you please copy and paste the SQL that Cube generates?

like: select a, b, c from t where a='x' limit 10;

> I also assume that you use pre-aggregations. Could you please show how the cube is defined, including the relevant pre-aggregation?

no, I am not using pre-aggregation.  the Cube only has metrics and dimensions.

Adding a note: We are using the Docker image version 0.34.

**Comment by igorlukanin** [comment]
Thanks for details, @w1992wishes!

> Which query do you run? --without group query
> like: select a, b, c from t where a='x' limit 10;

Do I get it correctly that you're running a REST API query with [`ungrouped`](https://cube.dev/docs/product/apis-integrations/rest-api/query-format#query-properties) to set to `true`? Why?

**Comment by w1992wishes** [comment]
> Do I get it correctly that you're running a REST API query with [`ungrouped`](https://cube.dev/docs/product/apis-integrations/rest-api/query-format#query-properties) to set to `true`? Why?

Yes, I am using ungrouped as true, but the slow initial query phenomenon is unrelated to this parameter. Even when ungrouped is not set, the same issue persists.

As for why we use ungrouped = true, it's simply because we have this scenario, but it's not very common.

**Comment by igorlukanin** [comment]
OK, I get that it's not related to `ungrouped`.

Frankly, it's quite hard to guess what is going wrong in the case that you describe. I feel like we'll need some kind of reproduction to move forward. It would be great if you can provide a runnable `docker-compose.yml` file that I can run on my machine to observe described effects. Alternatively, you can also try reproducing this in Cube Cloud (however, I don't expect Cube Cloud deployments to behave in that way).

**Comment by w1992wishes** [comment]
Thank you, I'll disable it for now since there are no issues with the router mode.
