### ISSUE TITLE
What to use instead of initApp?

### ISSUE THREAD

**Issue by vladvasyuk** [cube-js/cube#7982]
**Problem**

Hi, 

in our app we integrate Cube with Sentry using the `initApp` hook:

```js
const CubejsServer = require('@cubejs-backend/server');
const Sentry = require('@sentry/node');
const cubeConf = require('./conf/cube');

const options = {
  ...cubeConf.options,
  initApp: (app) => {
    app.use(Sentry.Handlers.requestHandler());
  },
};

const server = new CubejsServer(options);

server.listen().then(({ app, version, port }) => {
  app.use(Sentry.Handlers.errorHandler());
});

```

In the latest version the hook [was removed](https://github.com/cube-js/cube/commit/014c9a582903eb140e0d964718aa5532e3a142cf), and I didn't find a way to add Sentry middleware at the top of the stack after upgrade. So I had to implement a workaround, which is kinda hacky and may break in the future versions: 
```js
const server = new CubejsServer(cubeConf.options);
const originalInitApp = server.core.initApp;

server.core.initApp = async function initApp(app) {
  app.use(Sentry.Handlers.requestHandler());
  originalInitApp.call(this, app);
}.bind(server.core);
```

Could you please recommend a proper way to solve the issue? Here is the Sentry docs on integrating Express apps: [link](https://docs.sentry.io/platforms/node/guides/express/), and it states that the request handler must be the first middleware on the app.

**Comment by paveltiunov** [comment]
@vladvasyuk Unfortunately, there will be no direct replacement. Express will be replaced with a Rust web server for performance reasons.

**Comment by vladvasyuk** [comment]
Got it, thanks!
