### ISSUE TITLE
 With the increase of data models ，http_reqs  decreases

### ISSUE THREAD

**Issue by dutianmin9** [cube-js/cube#7996]
**Problem**

 With the increase of data models ，http_reqs  decreases. How can I optimize it? Thank you!
** k6 script **
```
import http from 'k6/http';

export const options = {
  vus: 10,
  duration: '30s',
  summaryTrendStats: [ 'min', 'med', 'p(95)', 'max' ],
  summaryTimeUnit: 'ms'
};

export default function() {
  const url = 'http://localhost:4000/cubejs-api/v1/load';

  const params = {
    headers: {
      'Authorization': 'token',
      'Content-Type': 'application/json'
    },
  };

  const payload = {
    query: {
      measures: [
        'Orders.count'
      ]
    }
  };
	
  http.post(url, JSON.stringify(payload), params);
}
```
**case 1:  4 datamodes**
```
     http_reqs......................: 12733  424.208446/s
     iteration_duration.............: min=6.94ms med=22.00ms p(95)=34.83ms max=733.43ms
     iterations.....................: 12733  424.208446/s
     vus............................: 10     min=10       max=10 
     vus_max........................: 10     min=10       max=10 
```
**case 2:  127 datamodes**
```
     http_reqs......................: 3269   108.846395/s
     iteration_duration.............: min=18.41ms med=89.66ms p(95)=147.41ms max=275.50ms
     iterations.....................: 3269   108.846395/s
     vus............................: 10     min=10       max=10
     vus_max........................: 10     min=10       max=10
```

running (0m30.0s), 00/10 VUs, 3269 complete and 0 interrupted iterations

**Comment by igorlukanin** [comment]
Hi @dutianmin9 👋 

How many data models (cubes and views) do you have in the first and in the second case?

Naturally, with the growth of the number of cubes and views, the data model compilation time would grow. However, the compilation only happens once for every `schema_version` (https://cube.dev/docs/reference/configuration/config#schema_version) and tenant (https://cube.dev/docs/reference/configuration/config#context_to_app_id).

This makes me question what is in your `cube.js` or `cube.py` file. If your data model recompiles often, it would affect the performance. You can optimize by making recompilations less frequent, compiling the data model in advance, and distributing the load over a few clusters.

**Comment by dutianmin9** [comment]
Hi @igorlukanin 
     I have 4 cubes and 127 cubes in the first and in the second case。
     The content of cube.js is as follows
`module.exports = {
    contextToAppId: ({ securityContext }) => {
        console.log('appID:',JSON.stringify(securityContext))
        return `CUBE_APP_${securityContext.tenant_id}`;
      },
   scheduledRefreshContexts: () => [
    {
      securityContext: {
        tenant_id: 123,
        bucket: 'demo'
      }
    },
    {
      securityContext: {
        tenant_id: 456,
        bucket: 'demo_2'
      }
    }
  ]
 }
  
`
But I made a new discovery in gateway.ts（@cubejs-backend/api-gateway）
     `private filterVisibleItemsInMeta(context: RequestContext, cubes: any[]) {
    function visibilityFilter(item) {
      return getEnv('devMode') || context.signedWithPlaygroundAuthSecret || item.isVisible;
    }

    return cubes
      .map((cube) => ({
        config: {
          ...cube.config,
         // measures: cube.config.measures?.filter(visibilityFilter),
         // dimensions: cube.config.dimensions?.filter(visibilityFilter),
          //segments: cube.config.segments?.filter(visibilityFilter),
        },
      })).filter(cube => cube.config.measures?.length || cube.config.dimensions?.length || cube.config.segments?.length);
  }`
 I I made a new discovery in gateway.ts. Commenting on the lines of measures, dimensions, and segments, http_reqs will be improved. From my understanding, we currently don’t need the logic of these lines of code, but are there any others? Linkage risk? Thanks

**Comment by ifokeev** [comment]
That's true, I tested same scenario with generic data models: the cubejs is not suitable to serve thousands of metric in the cube [(baseline benchmark)](https://github.com/mlcraft-io/examples/tree/main/benchmarks). Basically it's because of going through the AST tree. If the tree is too deep – it will take so much time to find a specific measure or dimension

**Comment by igorlukanin** [comment]
> I I made a new discovery in gateway.ts（@cubejs-backend/api-gateway）. Commenting on the lines of measures, dimensions, and segments, http_reqs will be improved

@dutianmin9 This essentially breaks the contract of the [`public` parameter](https://cube.dev/docs/reference/data-model/measures#public). If you'd like to hack on Cube's code, it's certainly up to you, but generally I would not recommend that.

> I have 4 cubes and 127 cubes in the first and in the second case
> The content of cube.js is as follows

Great, thanks you so much for sharing this. I see two security contexts in `scheduledRefreshContexts`.

How many security contexts do you use in your benchmark? Which ones?

**Comment by dutianmin9** [comment]
Thanks @igorlukanin. In my  benchmark,I use one security context.  As follows:
{
    "name": "John",
    "admin": true,
    "tenant_id": "dm",
    "exp": 1956412800
}

**Comment by dutianmin9** [comment]
> That's true, I tested same scenario with generic data models: the cubejs is not suitable to serve thousands of metric in the cube [(baseline benchmark)](https://github.com/mlcraft-io/examples/tree/main/benchmarks). Basically it's because of going through the AST tree. If the tree is too deep – it will take so much time to find a specific measure or dimension

Hi @ifokeev ， How did you solve this problem?

**Comment by igorlukanin** [comment]
@dutianmin9 It's great that you've used just a single security context. It means that the data model had to be compiled just once for the whole batch of queries.

If you'd like to get more RPS from a Cube cluster, my general recommendation would be to use the architecture similar to the [production multi-cluster](https://cube.dev/docs/product/deployment/cloud/deployment-types#production-multi-cluster) in Cube Cloud, where each cluster serves the load for a subset of tenants, and there are multiple API instances in each cluster. This kind of architecture would allow to scale your workload vertically with a good level of flexibility.

**Comment by dutianmin9** [comment]
@igorlukanin  thank you very much ！

**Comment by ifokeev** [comment]
@Dutianmin9, the singular solution that currently presents itself involves augmenting the quantity of tenants, as stated by Igor. There is an evident need to enhance the performance of the cube schema compiler, particularly regarding dimension and measure indexing. At present, traversing the Abstract Syntax Tree consumes a considerable amount of time.
