### ISSUE TITLE
Cubestore AWS Credentials required

### ISSUE THREAD

**Issue by goncaloacteixeira** [cube-js/cube#8197]
**Describe the bug**
Since version 0.35.17, AWS credentials seem to be required as environment variables, which caused the upgrade to fail for anyone using implicit AWS authentication.

**To Reproduce**
1. Don't define `CUBESTORE_AWS_ACCESS_KEY_ID` or `CUBESTORE_AWS_SECRET_ACCESS_KEY`
2. Use implicit AWS authentication such as a ServiceAccount in K8s or Token authentication locally
3. Cubestore outputs an error and fails.

**Expected behavior**
From the [docs](https://cube.dev/docs/product/caching/running-in-production#aws), Cubestore should be able to authenticate to AWS without having to explicitly define these env vars.

**Version:**
\>=0.35.17

**Comment by ChrisLahaye** [comment]
I think this is the same issue as being reported here https://github.com/cube-js/cube/issues/8163#event-12622040708. The fix has recently been merged and released as 0.35.24, although the Docker image isn't released yet due to a failing pipeline.

**Comment by goncaloacteixeira** [comment]
Thanks! Going to close this as dupplicate then
