### ISSUE TITLE
What is difference between Apache pinot vs cube?

### ISSUE THREAD

**Issue by vikingcodes** [cube-js/cube#8234]
I am exploring tools for multi tenant app. 

Can anyone explain difference between Apache pinot vs cube?

For me both looking same.

**Comment by igorlukanin** [comment]
Cube and Oinot are similar in a way that they both provide access to upstream data sources via a SQL API. However, I would say that Pinot is a slightly lower level solution than Cube.

Cube has the [data modeling](https://cube.dev/docs/product/data-modeling/overview) layer that allows to abstract metrics definitions. Cube also provides access control and natively supports multitenancy. Finally, Cube provides not only the SQL API but also REST API for front-end applications.

I hope this helps.
