### ISSUE TITLE
[Data Source Connectivity Request] for Apache Doris

### ISSUE THREAD

**Issue by ZiggiZagga** [cube-js/cube#8302]
Hi,

we would like to request the addition of a data source connectivity option for  [Apache Doris](https://doris.apache.org/), a Real-Time Data Warehouse.  [Apache Doris](https://doris.apache.org/) appears very promising for our needs, particularly in terms of performance. According to [Data source connectivity docs](https://doris.apache.org/docs/db-connect/database-connect)  [Apache Doris](https://doris.apache.org/) adopts the MySQL network connection protocol and is compatible with command-line tools, JDBC/ODBC drivers.

Thank you for considering this request.

Kind regards,

**Comment by ZiggiZagga** [comment]
Apache doris is already supported by cube-js through mysql datasource connection

**Comment by igorlukanin** [comment]
@ZiggiZagga How complete is that support? If you could describe your experience for other community members' reference, that would be precious! (Also, I think it might be great if anyone volunteers to contribute a driver—might be a wrapper around MySQL, just like Trino driver wraps Presto driver—and a documentation page.)

**Comment by ZiggiZagga** [comment]
Hallo @igorlukanin,

because Apache Doris adopts the MySQL network connection protocol, it is compatible with command-line tools and JDBC/ODBC drivers. Doris support is fully integrated with Cube's MySQL datasource connectivity. To set this up, simply follow the instructions provided in the following link: https://cube.dev/docs/product/configuration/data-sources/mysql.

In my experience, adding extra code for a specific wrapper would create additional maintenance overhead without significant benefits. Instead, I recommend explicitly documenting Apache Doris connectivity using MySQL in Cube's official documentation. 

I have used Cube's SQL API to query Doris, and nearly everything worked as expected. The integration has been seamless, demonstrating that the current MySQL datasource connectivity sufficiently supports Apache Doris.

At the moment, I am waiting for some improvements in the SQL API to continue my experiments.

Kind regards.
