### ISSUE TITLE
Bigquery timestamps with 6 digits now break pre-aggregations

### ISSUE THREAD

**Issue by lvauvillier** [cube-js/cube#8320]
**Describe the bug**
In the latest version (v0.35.43), the BigQuery driver now retrieves timestamps with 6 digits (#8308). This breaks the preaggregation rule that only accepts 3 digits.

**To Reproduce**
Use the latest version, and add a `buildRangeStart` and a `buildRangeEnd` in the preaggregation definition:

```
buildRangeStart: {
  sql: `SELECT DATETIME_SUB(CURRENT_DATETIME(), INTERVAL 60 DAY)`,
},
buildRangeEnd: {
  sql: `SELECT DATETIME_SUB(DATETIME_ADD(DATETIME_TRUNC(CURRENT_DATETIME(), DAY), INTERVAL 1 DAY), INTERVAL 1 MICROSECOND)`,
},
```

We get the error:

`Error: Date range expected to be in YYYY-MM-DDTHH:mm:ss.SSS format but 2024-05-04T00:00:00.000000,2024-06-03T23:59:59.999999 found`

**Comment by ovr** [comment]
Hello @lvauvillier,

Thank you for submitting the issue! I've prepared a fix, it will be released in the next version.

Thank you
