### ISSUE TITLE
Is Semantic Layer Sync (going to be) supported in core?

### ISSUE THREAD

**Issue by mlazowik** [cube-js/cube#8355]
We are evaluating Cube for a use case where we need all of the infrastructure to be hosted in specific countries (that do not have any public cloud regions) for regulatory reasons. Semantic Layer Sync would be great to have. Am I correctly assuming that it's only available in the cloud version now?

**Comment by mlazowik** [comment]
Ack, thanks

**Comment by igorlukanin** [comment]
@mlazowik I see. Out of curiosity, which countries are you referring to?

**Comment by mlazowik** [comment]
Kenya, Malawi, Namibia, Cameroon etc.
