### ISSUE TITLE
[useCubeQuery /  React] How change to HTTP Method Post ?

### ISSUE THREAD

**Issue by mayconline** [cube-js/cube#8386]
**Problem**

Using `useCubeQuery`,   how change to HTTP Method Post ?

`import { useCubeQuery } from "@cubejs-client/react";`

`const result = useCubeQuery(query, options);`

this docs [https://cube.dev/docs/reference/rest-api#v1load](https://cube.dev/docs/reference/rest-api#v1load), 
`"# Use POST to fix problem with query length limits"`

It said to change the post method to fix this error, but I didn't find where it is possible to change the method.

**Comment by igorlukanin** [comment]
Hi @mayconline 👋 

I've checked the [source code](https://github.com/cube-js/cube/blob/master/packages/cubejs-client-core/src/HttpTransport.js#L23-L27) and I can confirm that the `useCubeQuery` hook as well as other utilities from Cube's JavaScript SDK will automatically switch from GET to POST when needed, no manual action is required.

Did you face any issues yourself?

**Comment by mayconline** [comment]
Hi, Morning, I was trying to do this manually, trying to pass some prop to it to become a POST.

Is there any way to do it?

I was having a problem with my query, but I don't know if it reached the 2000 character limit, because it wasn't always going as GET.

Anyway, I changed the way it is being done, and it stopped giving errors, but it would be nice to have this option to change the manual GET to POST, for future problems that may arise.

**Comment by igorlukanin** [comment]
If you have a code example that can help reproduce errors, I'd be happy to take a look.
