### ISSUE TITLE
SQL Timestamp WHERE condition

### ISSUE THREAD

**Issue by itestyoy** [cube-js/cube#8415]
When we use the SQL API and the WHERE condition, the cube changes the sign.

SQL API query with >= and <:

```  
(
    "public"."monetization_view"."user_first_touch_date" >= timestamp '2024-06-07 00:00:00.000'
   AND 
    "public"."monetization_view"."user_first_touch_date" < timestamp '2024-06-08 00:00:00.000'
)
```

However, Cube generates a BigQuery query with >= and <=:

```
(
    CAST(`monetization_metrics`.user_first_touch_date as TIMESTAMP) >= TIMESTAMP(?) 
  AND 
   CAST(`monetization_metrics`.user_first_touch_date as TIMESTAMP) <= TIMESTAMP(?)
)
```

**Comment by paveltiunov** [comment]
@itestyoy It's correct behavior. You should check actual timestamp values. It'd differ by one millisecond. There's a known issue for BigQuery of a 1ms gap as it's microsecond-based.
