### ISSUE TITLE
SQL-API: Column concatenation failing

### ISSUE THREAD

**Issue by ZiggiZagga** [cube-js/cube#8430]
**Failed SQL**
`select 'Some Prefix'||some_column from some_cube`

**Error**
Error during rewrite: Can't detect Cube query and it may be not supported yet.

**Logical Plan**
Error during planning

**Version:**
v0.35.54

**Additional context**
This query works:
`select some_column||'Some Suffix' from some_cube`

**Comment by igorlukanin** [comment]
Hi @ZiggiZagga 👋 

I see that you have `CUBESQL_SQL_PUSH_DOWN` set to `false` (or not set at all). It means that Cube can only use post-processing (and push-down queries are not enabled). You can read more about this terminology on the docs: https://cube.dev/docs/product/apis-integrations/sql-api#fundamentals, https://cube.dev/docs/product/apis-integrations/sql-api/query-format#post-processing-and-pushdown

To make this query work with post-processing, you can rewrite is as follows:

<img width="776" alt="Screenshot 2024-07-05 at 17 05 40" src="https://github.com/cube-js/cube/assets/3852894/b00cf0b2-c3c8-43f8-8f2a-68f536b26134">

Alternatively, you can set `CUBESQL_SQL_PUSH_DOWN` to `true` and run a query like this:

<img width="1079" alt="Screenshot 2024-07-05 at 17 02 15" src="https://github.com/cube-js/cube/assets/3852894/4e3cd435-cf46-4c19-a584-dc59e48ab9d2">

There are slight differences in query semantics between these two variants, you can read more in the blog: https://cube.dev/blog/query-push-down-in-cubes-semantic-layer

**Comment by ZiggiZagga** [comment]
Hi @igorlukanin,

Thank you! I set `CUBESQL_SQL_PUSH_DOWN` to `true`, and the query now works. Unfortunately, I can't use the Cube SQL API for now because I am having problems with CTEs in `LEFT JOIN` or `IN` conditions. Issues have already been filed (#8422 and #8413). I will keep an eye on the progress of these issues and hopefully consider using the SQL API again in the near future.

**Comment by ZiggiZagga** [comment]
Works when `CUBESQL_SQL_PUSH_DOWN` is set to `true`
