### ISSUE TITLE
Release Playground 2.0 in Cube Core

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#8484]
In January 2024, [Playground 2.0](https://cube.dev/blog/introducing-playground-2) has been released in Cube Cloud. We would like to bring it to Cube Core as well.

It's currently planned for September 2024.

**Comment by igorlukanin** [comment]
The following issues will be resolved once Playground 2.0 is brought to Cube Core:
- https://github.com/cube-js/cube/issues/2244
- https://github.com/cube-js/cube/issues/2582
- https://github.com/cube-js/cube/issues/3238
- https://github.com/cube-js/cube/issues/3588
- https://github.com/cube-js/cube/issues/4377
- https://github.com/cube-js/cube/issues/7085

**Comment by zda** [comment]
@igorlukanin Happy to learn about this. The current playground is good, but I have run into a couple issues like the ones you listed. Look forward to trying it out.

**Comment by igorlukanin** [comment]
Documentation:
- [Playground](https://cube.dev/docs/product/workspace/playground) in Workspace.
- [Chart Prototyping](https://cube.dev/docs/product/workspace/vizard) in Workspace.

Announcement in the blog: https://cube.dev/blog/introducing-playground-2-0-and-chart-prototyping-in-cube-core
