### ISSUE TITLE
Cube.js Response Slow Despite Fast BigQuery Performance

### ISSUE THREAD

**Issue by HassanAtWecrunch** [cube-js/cube#8526]
**Overview**
Cube Version :0.33.50
I am using Cube.js (connected to BigQuery) as the backend for my React project via a REST API. 
Cube.js is deployed on a Node server, managed through PM2 and served with Nginx.
Docker is not involved.
Memory is being used as cache for now

Enviroment Variables are: 

```
CUBEJS_DB_BQ_PROJECT_ID=336107
CUBEJS_DB_BQ_KEY_FILE=big-query-key.json
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=bigquery
CUBEJS_API_SECRET=aaaa
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_PG_SQL_PORT=5439
CUBEJS_SQL_USER=myusername
CUBEJS_SQL_PASSWORD=password  
CUBEJS_DB_QUERY_LIMIT=150000
CUBEJS_CACHE_AND_QUEUE_DRIVER=memory
```

Schema Attached below.

![image](https://github.com/user-attachments/assets/070dd3e1-012a-411e-bbeb-9758b4c085c7)

**Problem**

**Related to Cube Store:**

When i try to use cubestore by doing this ' CUBEJS_CACHE_AND_QUEUE_DRIVER=cubestore', it gives a hike to my Memory and CPU and process gets killed. (tested on 1vCPU and 2GB RAM )
 

**_Without Cache:_**

- **tested on: dedicated resource 2vCPU and 8GB RAM**

-  When executing a query that returns 28MB of data, BigQuery processes the query in 1 second, as shown in the attached screenshot. 
- However, Cube.js takes 12 seconds to complete the execution on the first run when nothing is cached in the Cube store.
- In my browser, as shown in the screenshot, the server response time is 12 seconds, and the download time is 2 seconds, which includes compression (enabled in Nginx).
![image](https://github.com/user-attachments/assets/fb51a64a-0bcf-4b42-846c-b0d492317049)

![image](https://github.com/user-attachments/assets/a0bcece8-ba43-4c49-a5ad-8a7579b0c477)
![image](https://github.com/user-attachments/assets/23911d3a-f852-4201-bc7f-a0aa7e5d3fda)

```
0|Cube Ser | Performing query completed: a3710b05-d689-43cd-8dcc-b0f1fb2d097b-span-1 (10899ms)
0|Cube Ser | Load Request Success: a3710b05-d689-43cd-8dcc-b0f1fb2d097b-span-2 (12376ms)
0|Cube Ser | --
0|Cube Ser | [
0|Cube Ser |   {
0|Cube Ser |     "timezone": "UTC",
0|Cube Ser |     "timeDimensions": [
0|Cube Ser |       {
0|Cube Ser |         "dimension": "Fact.reporteddate",
0|Cube Ser |         "granularity": "month",
0|Cube Ser |         "dateRange": [
0|Cube Ser |           "2024-04-01",
0|Cube Ser |           "2024-06-01"
0|Cube Ser |         ]
0|Cube Ser |       }
0|Cube Ser |     ],
0|Cube Ser |     "limit": 100000,
0|Cube Ser |     "total": true,
0|Cube Ser |     "filters": [
0|Cube Ser |       {
0|Cube Ser |         "member": "Fact.data_type_id",
0|Cube Ser |         "operator": "equals",
0|Cube Ser |         "values": [
0|Cube Ser |           100
0|Cube Ser |         ]
0|Cube Ser |       },
0|Cube Ser |       {
0|Cube Ser |         "member": "DimTimePeriod.period",
0|Cube Ser |         "operator": "equals",
0|Cube Ser |         "values": [
0|Cube Ser |           "Monthly"
0|Cube Ser |         ]
0|Cube Ser |       }
0|Cube Ser |     ],
0|Cube Ser |     "measures": [
0|Cube Ser |       "Fact.valuesSum",
0|Cube Ser |       "Fact.valuesLySum",
0|Cube Ser |       "Fact.valuesPPSum"
0|Cube Ser |     ],
0|Cube Ser |     "dimensions": [
0|Cube Ser |       "DimProduct.ph_3",
0|Cube Ser |       "DimGeography.h1_6",
0|Cube Ser |       "DimProduct.ph_9",
0|Cube Ser |       "DimGeography.h1_4",
0|Cube Ser |       "DimGeography.h1_3",
0|Cube Ser |       "DimGeography.h1_9",
0|Cube Ser |       "DimGeography.h1_7",
0|Cube Ser |       "DimMeasure.label",
0|Cube Ser |       "DimGeography.h1_5",
0|Cube Ser |       "DimProduct.ph_5",
0|Cube Ser |       "DimProduct.ph_8",
0|Cube Ser |       "DimProduct.ph_2",
0|Cube Ser |       "DimProduct.ph_4"
0|Cube Ser |     ],
0|Cube Ser |     "order": {
0|Cube Ser |       "DimProduct.ph_3": "asc",
0|Cube Ser |       "DimGeography.h1_6": "asc",
0|Cube Ser |       "DimProduct.ph_9": "asc",
0|Cube Ser |       "DimGeography.h1_4": "asc",
0|Cube Ser |       "DimGeography.h1_3": "asc",
0|Cube Ser |       "DimGeography.h1_9": "asc",
0|Cube Ser |       "DimGeography.h1_7": "asc",
0|Cube Ser |       "DimMeasure.label": "asc",
0|Cube Ser |       "DimGeography.h1_5": "asc",
0|Cube Ser |       "DimProduct.ph_5": "asc",
0|Cube Ser |       "DimProduct.ph_8": "asc",
0|Cube Ser |       "DimProduct.ph_2": "asc",
0|Cube Ser |       "DimProduct.ph_4": "asc"
0|Cube Ser |     }
0|Cube Ser |   }
0|Cube Ser | ]
```

**_Without Cache:_**

- **tested on: dedicated resource 2vCPU and 8GB RAM**

-  On the second run of the same query, it still takes 6.5 seconds to finish execution using the Cube store's cached results.
 ```
0|Cube Server  | Load Request Success: 7b14de15-958c-4521-ac05-a05d9636f32e-span-1 (6260ms)
0|Cube Server  | --
0|Cube Server  | [
0|Cube Server  |   {
0|Cube Server  |     "timezone": "UTC",
0|Cube Server  |     "timeDimensions": [
0|Cube Server  |       {
0|Cube Server  |         "dimension": "Fact.reporteddate",
0|Cube Server  |         "granularity": "month",
0|Cube Server  |         "dateRange": [
0|Cube Server  |           "2024-04-01",
0|Cube Server  |           "2024-06-01"
0|Cube Server  |         ]
0|Cube Server  |       }
0|Cube Server  |     ],
0|Cube Server  |     "limit": 100000,
0|Cube Server  |     "total": true,
0|Cube Server  |     "filters": [
0|Cube Server  |       {
0|Cube Server  |         "member": "Fact.data_type_id",
0|Cube Server  |         "operator": "equals",
0|Cube Server  |         "values": [
0|Cube Server  |           100
0|Cube Server  |         ]
0|Cube Server  |       },
... same as above
```

**Question**

How can I reduce the overall execution time for queries in Cube.js, both for the initial run and subsequent runs using cached results?
Will using Cubestore instead of memory will improve performance?
How much memory and CPU required for Cubestore?

**Comment by HassanAtWecrunch** [comment]
Update: I tried docker setup with 0.35.0 version of cube. But the speed remains the same

**Comment by igorlukanin** [comment]
Hi @HassanAtWecrunch 👋 

> How can I reduce the overall execution time for queries
First of all, I think it's best to decide whether your use case really involves loading 30,000 rows in a single query. While it's not something outstanding, I just wonder what kind of a "fully interactive dashboard" you're building that somehow is able to display 30,000 rows of data to users. Maybe, you might want to run multiple queries that bring bite-sized portions of data instead of loading everything in a one chunk and crunching it on the front-end.

Then, I would definitely consider using Cube Store and building pre-aggregations. That might reduce the time spend querying BigQuery and loading data from BigQuery to Cube. I assume that Cube Store would be located closer to Cube in terms of network and it'll also have enough resources.

For cluster sizing recommendations, please check the docs: https://cube.dev/docs/product/deployment/production-checklist#appropriate-cluster-sizing

**Comment by HassanAtWecrunch** [comment]
Hello @igorlukanin ,

Thank you for your attention. Let me clarify my scenario a bit more.

My "Interactive Dashboard" consists of various charts representing sales data (top 20 rows) across different dimensions. These charts are fully interactive, allowing users to filter the data displayed on other charts by clicking anywhere within them. This interactivity is powered by crossfilter.js. While I could query Cube for each interaction or filtration, I need something that provides instant speed, which is why I chose crossfilter.js (https://github.com/square/crossfilter).

Please let me know if further clarification is required. 
Thanks

**Comment by igorlukanin** [comment]
> This interactivity is powered by crossfilter.js. While I could query Cube for each interaction or filtration, I need something that provides instant speed, which is why I chose crossfilter.js (https://github.com/square/crossfilter).

Usually, with pre-aggregations and queries that return reasonably-sized datasets, you can expect the latency to be within 50-300 ms range. For many use cases it would qualify as "almost instant". While I don't have anything against using Crossfilter, by doing so you you shift the burden of data crunching from Cube to your front-end code. I wonder if Cube delivers enough value here and if it would be better just to query BigQuery directly.

> Should I look into pre aggregations too?
IMO, definitely. But if the plan is to steam 30,000 res to the front-end, it's hard to predict what the improvement would be.

**Comment by HassanAtWecrunch** [comment]
Thanks.
I will look into pre-aggregations first and let you know

**Comment by HassanAtWecrunch** [comment]
Hi @igorlukanin ,

I attempted to implement pre-aggregations in my project, but I've encountered an unexpected error during the pre-aggregation build process. I tried using Cube.js versions 0.35.0 and 0.35.69 with the standard docker-compose.yml.

The error message I'm receiving is as follows:
error is as follows: 

> Error: Access Denied: BigQuery BigQuery: Permission denied while writing data. sheetsapi@plexus-336107.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist). Please make sure gs://cubestore/dev_pre_aggregations.fact_sales_dashboard20180101_uerhisj2_3v5wingb_1jbmob9-000000000000.csv.gz is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.
> plexuscube-cube_api-1             |     at BigQueryDriver.awaitForJobStatus (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:367:15)
> plexuscube-cube_api-1             |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> plexuscube-cube_api-1             |     at BigQueryDriver.waitForJobResult (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:394:22)
> plexuscube-cube_api-1             |     at BigQueryDriver.unload (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:327:5)
> plexuscube-cube_api-1             |     at PreAggregationLoader.getTableDataWithTempTable (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1245:19)
> plexuscube-cube_api-1             |     at PreAggregationLoader.downloadExternalPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1218:21)
> plexuscube-cube_api-1             |     at PreAggregationLoader.runWriteStrategy (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1025:25)
> plexuscube-cube_api-1             |     at Object.query (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:602:26)
> plexuscube-cube_api-1             |     at QueryQueue.processQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:842:25)
> plexuscube-cube_api-1             | Downloading external pre-aggregation error: scheduler-0f33ae2c-67e4-4efa-80b5-02ec5803c36b
> plexuscube-cube_api-1             | --

>   Error: Access Denied: BigQuery BigQuery: Permission denied while writing data. sheetsapi@plexus-336107.iam.gserviceaccount.com does not have storage.objects.create access to the Google Cloud Storage object. Permission 'storage.objects.create' denied on resource (or it may not exist). Please make sure gs://cubestore/dev_pre_aggregations.fact_sales_dashboard20170101_tocjcqmg_1upe2wfb_1jbmob9-000000000000.csv.gz is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.
plexuscube-cube_api-1             |     at BigQueryDriver.awaitForJobStatus (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:367:15)
plexuscube-cube_api-1             |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
plexuscube-cube_api-1             |     at BigQueryDriver.waitForJobResult (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:394:22)
plexuscube-cube_api-1             |     at BigQueryDriver.unload (/cube/node_modules/@cubejs-backend/bigquery-driver/src/BigQueryDriver.ts:327:5)
plexuscube-cube_api-1             |     at PreAggregationLoader.getTableDataWithTempTable (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1245:19)
plexuscube-cube_api-1             |     at PreAggregationLoader.downloadExternalPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1218:21)
plexuscube-cube_api-1             |     at PreAggregationLoader.runWriteStrategy (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1025:25)
plexuscube-cube_api-1             |     at Object.query (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:602:26)
plexuscube-cube_api-1             |     at QueryQueue.processQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:842:25)
plexuscube-cube_api-1             | Error while querying: scheduler-0f33ae2c-67e4-4efa-80b5-02ec5803c36b (16875ms)

I’ve ensured that the service account has the necessary permissions:

![image](https://github.com/user-attachments/assets/6bbd51bc-088b-4193-8958-0fc47955f6db)

**It’s worth noting that I can see the pre-aggregation tables in BigQuery, and they contain data as expected.**

Any guidance or suggestions would be greatly appreciated.

Thanks in advance!

**Comment by HassanAtWecrunch** [comment]
Update: I was able to resolve it by manually creating a bucket and referring it vis environment variables in docker-compose.yml like this :
     

>  - CUBEJS_DB_EXPORT_BUCKET=cubestore_plexus_001
>       - CUBEJS_DB_EXPORT_BUCKET_TYPE=gcp
>

**Comment by HassanAtWecrunch** [comment]
Final Update: I implemented pre-aggregations, which helped reduce the delay to some extent. Moving forward, I plan to explore direct communication with Cube.js for each interaction, thereby removing crossfilter.js from the workflow. 
Special thanks to @igorlukanin  for the invaluable guidance.
