### ISSUE TITLE
Cube sends Repsonse with statusCode 200 but "error": "Continue wait"

### ISSUE THREAD

**Issue by thePermission** [cube-js/cube#8532]
**Describe the bug**
When i query my cube instance the first time i get a response with statusCode 200 but the body is:
```
{
    "error": "Continue wait"
}
```

**To Reproduce**
I can just give my cube.js config and the fact that is running in a kubernetes Cluster
```
const fetch = require("node-fetch");


// Cube.js configuration options: https://cube.dev/docs/config
module.exports = {
    allowUngroupedWithoutPrimaryKey: true,
    contextToAppId: ({securityContext}) => {
        return `CUBEJS_APP_${Math.random(100000)}`;
    },
    repositoryFactory: ({securityContext}) => {
        return {
            dataSchemaFiles: async () =>
                await (
                    await fetch(process.env.MODELL_SERVICE_URL)
                ).json()
        };
    },
    scheduledRefreshTimer: 60
};
```
**Expected behavior**
I expect to get data, but even if i dont get my data i expect the status Code to be sth like >400 if the request fails and not 200 but an error message.

**Screenshots**
![image](https://github.com/user-attachments/assets/98752235-6d44-4446-8f98-227d547366eb)

**Version:**
[e.g. 0.35.18]

**Comment by ifokeev** [comment]
Hi! It's expected behavior. Please check https://cube.dev/docs/product/apis-integrations/rest-api#continue-wait.

**Comment by thePermission** [comment]
Okay, but wouldn’t a 503 and retry-after header be expected in that case? I mean this would be a feature request and not an issue then, but just my thought

**Comment by ifokeev** [comment]
Historically, "continue wait" is some kind of long polling mechanism, so Cube only has this right now.

**Comment by igorlukanin** [comment]
@thePermission FYI, the JavaScript SDK handles these "continue wait" timeouts completely transparently, so I would definitely recommend to use it: https://cube.dev/docs/reference/frontend/cubejs-client-core

**Comment by criveratro** [comment]
> [@thePermission](https://github.com/thePermission) FYI, the JavaScript SDK handles these "continue wait" timeouts completely transparently, so I would definitely recommend to use it: https://cube.dev/docs/reference/frontend/cubejs-client-core

Is there anyway to increase the interval between retries? I tried with `pollInterval` but it doesn't seem to have any effect, might be for something else.
