### ISSUE TITLE
PR#8520 breaks pre-aggregations with s3

### ISSUE THREAD

**Issue by rogal111** [cube-js/cube#8536]
**Describe the bug**
with release 0.35.65 that includes #8520 , s3 pre-aggregations stopped working.

**To Reproduce**
1. install cubejs 0.35.65
2. configure Export Bucket pre-aggregations strategy using S3 (e.g. with Redshift)
3. try to define & run model with pre_aggregations
4. cubestore router fails with error `Unable to import from http location, status code: 403 Forbidden` when attempting to compute preagregations

**Expected behavior**
Pre-aggregations should work.

**Version:**
0.35.65

**Additional context**
[`location_file_size` helper](https://github.com/cube-js/cube/pull/8520/files#diff-bca4da1c91da80f75efdbaf20d879fb3b398a84faf882623079d120dcf9f1d01L854 ) function uses HEAD request to fetch size of imported remote file. While S3 integration uses predesigned URLs ([doc here](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)) to import files located in s3. File URL provided to the helper is signed for GET method, while `location_file_size` attempts to use it with HEAD request - it leads to 403 response from S3 api.

Before changes introduced in #8520, this helper silently ignored `403 response` from S3 and returned `None` - which I guess was no obstacle to the pre-aggregation import.

**Comment by ovr** [comment]
Fixed & released in v0.35.66
