### ISSUE TITLE
Troubleshooting setting Multiple Athena Datasources 

### ISSUE THREAD

**Issue by amartinezcortizas** [cube-js/cube#8548]
Hi, 
Just unsuccessfully trying to set up multiple AWS Athena datasources with the following .env file at Cube Core:

CUBEJS_DATASOURCES=additional,default

# DEFAULT DATASOURCE
CUBEJS_AWS_KEY=..........
CUBEJS_AWS_SECRET=...............
CUBEJS_AWS_REGION=eu-west-1
CUBEJS_AWS_S3_OUTPUT_LOCATION=s3://........./........../.........../
CUBEJS_DB_TYPE=athena
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_DEV_MODE=true
CUBEJS_SCHEMA_PATH=model
CUBEJS_DB_NAME=.....

# ADDITIONAL DATASOURCE
CUBEJS_DS_ADDITIONAL_AWS_KEY=.............
CUBEJS_DS_ADDITIONAL_AWS_SECRET=............
CUBEJS_DS_ADDITIONAL_AWS_REGION=eu-west-1
CUBEJS_DS_ADDITIONAL_AWS_S3_OUTPUT_LOCATION=s3://......../........./........./
CUBEJS_DS_ADDITIONAL_DB_TYPE=athena
CUBEJS_DS_ADDITIONAL_EXTERNAL_DEFAULT=true
CUBEJS_DS_ADDITIONAL_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_DS_ADDITIONAL_DEV_MODE=true
CUBEJS_DS_ADDITIONAL_SCHEMA_PATH=model
CUBEJS_DS_ADDITIONAL_DB_NAME=........

The "default" source successfully connect, the database tables are shown, but no luck with "additional" source, no database neither tables are shown. 
More info: If I try to setup just the "additional" database, the database and tables are shown, so the connection settings for the "additional" database are right.

**Comment by amartinezcortizas** [comment]
Same result defining env vars at docker-compose.yml

**Comment by igorlukanin** [comment]
@amartinezcortizas Were you referring to [this one](https://github.com/cube-js/cube/issues/6960#issuecomment-1882827055)? Anyhow, I'm glad this got resolved.
