### ISSUE TITLE
Docker manifest missing arm arch cubestore manifest

### ISSUE THREAD

**Issue by pauldheinrichs** [cube-js/cube#8570]
**Describe the bug**
Somewhere between `v0.35.57` and now the CI is no longer publishing the main tags with both amd / arm architectures in the manifest in cubestore image.

![image](https://github.com/user-attachments/assets/b5a881b1-9685-4918-8845-698cb22c8275)

It previously was in .57 and prior, and now no longer is. 

I would anticipate that in the releases / main tags there should be both included.

**Comment by ovr** [comment]
Hello @pauldheinrichs ,

It didn't, We are using a separate tag for `arm64` arch:

`cubejs/cubestore:arm64v8`

https://hub.docker.com/layers/cubejs/cubestore/arm64v8/images/sha256-aa333f41af7f1fac1140a6b9b9fecd430eedb1b4055074fe7784a83069df5994?context=explore

Thanks

**Comment by pauldheinrichs** [comment]
@ovr Ahhh okay - curious the reason for not publishing the manifest with both arch and different images?

This change causes causes extra bloat in CI steps trying to account for both amd / arm architectures in trying to detect

```
if arm append vx.x.x-arm

ELSE

vx.x.x
```

**Comment by ovr** [comment]
We use a separate machine to build `arm64`, which leads to the problem that we need to merge the manifest as a final step on CI. We still haven't had a chance to work on it.

Contributions are welcome. Feel free to submit a PR with that feature 👍 

Thanks
