### ISSUE TITLE
Connecting to Apache Pinot as a data source

### ISSUE THREAD

**Issue by AnishNair94** [cube-js/cube#8579]
**Is your feature request related to a problem? Please describe.**
The lack of Apache Pinot integration in Cube creates a bottleneck in our analytics workflow, limiting our ability to fully leverage the benefits of Cube headless BI approach. 

**Describe the solution you'd like**
I would like Cube to add native integration with Apache Pinot by developing a dedicated driver or connector.

**Describe alternatives you've considered**
It seems like the only other alternatives are to look for another headless BI tool or create our own.

**Additional context**
Apache Pinot version 1.0, Looking for Multi-Stage Engine Support which has join, subquery etc and closer to ANSI-SQL.

**Comment by igorlukanin** [comment]
@AnishNair94 Thanks for the proposal! I think it would be great if someone from the community volunteers to create a Pinot driver. We have some contribution guidelines here: https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md#contributing-database-drivers

**Comment by igorlukanin** [comment]
Hi @jronsse 👋 

Amazing! Thanks for taking the lead on this!

**Comment by AnishNair94** [comment]
Hey @jronsse 
This is awesome!!
Will try it out.

**Comment by jronsse** [comment]
Hello @AnishNair94 !

I just tried it on my end with the latest version `v1.1.2`. Pinot does not show up in the selection of datasources in the UI but you can still set it up through environment variables. 
Here's an example:
```bash
CUBEJS_DB_TYPE=pinot
CUBEJS_DB_HOST=http[s]://pinot.broker.host
CUBEJS_DB_PORT=8099
CUBEJS_DB_USER=pinot_user
CUBEJS_DB_PASS=**********
```

The user and password are not mandatory.

Please let me know if you encounter any issues using the driver once you've got it up and running.

**Comment by igorlukanin** [comment]
I've added a note on the UI vs. env vars in the docs on the Pinot page. With that, I guess we're good to close this issue as resolved. Huge thanks for your contribution @jronsse 🙌
