### ISSUE TITLE
(peer dependencies) Install @cubejs-backend/postgres-driver failed

### ISSUE THREAD

**Issue by mokeyish** [cube-js/cube#8601]
**Describe the bug**

Install @cubejs-backend/postgres-driver failed.

It seems to be a peer dependencies version conflict issue.

**To Reproduce**
1. Docker run
    ```sh
    docker run -p 4000:4000 \
      -p 15432:15432 \
      -v ${PWD}:/cube/conf \
      -e CUBEJS_DEV_MODE=true \
      cubejs/cube:dev
    ````
3. Open http://127.0.0.1:4000
4. Set Up a Database connection
5. Install postgres-driver

   
   <img width="528" alt="image" src="https://github.com/user-attachments/assets/1eee343e-5bc7-456c-bec1-cd02189c08fc">

7. See error

   
    <img width="930" alt="image" src="https://github.com/user-attachments/assets/40e0b1c2-ee3a-43bf-b22f-ddb59be51775">

    npm install @cubejs-backend/postgres-driver --save-dev failed with exit code 1. Please check your console.

**Expected behavior**
Install postgres-driver successfully.

**Screenshots**

![image](https://github.com/user-attachments/assets/c2b19d06-2dbb-490e-b46e-45927714e4bc)

![image](https://github.com/user-attachments/assets/e53c65ae-55b1-49f5-b9ca-8aa4d518f53c)

**Version:**
v0.35.72（latest）

**Additional context**

Seeing pnpm dealing with this kind of problem is smoother.

https://pnpm.io/how-peers-are-resolved

**Comment by igorlukanin** [comment]
Hi @mokeyish 👋 

> Install postgres

What do you mean by that, exactly? It would be great to get more details.

I have just went through the steps described [here](https://cube.dev/docs/product/getting-started/core/create-a-project) and everything worked smoothly. I did not have to install any Postgres driver though as it's bundled with Cube in its Docker container.

**Comment by mokeyish** [comment]
@igorlukanin I've update the Step To Reproduce with screenshot.

**Comment by mokeyish** [comment]
My temporary solution is creating a directory with following structure

```
cubework
├── justfile
├── package.json
```

1. `package.json`, copy from https://github.com/cube-js/cube/blob/master/packages/cubejs-docker/package.json
2. `justfile`

    ```makefile
    export PATH := absolute_path("node_modules/.bin:") + env_var("PATH")
    
    export CUBEJS_DEV_MODE := "true"

    setup:
        pnpm install
    
    serve:
        cubejs server
    
    
    cleanup:
        rm -rf .cubestore
        rm -rf .env
        rm -rf model
    ```

3. startup
    1. install just https://just.systems/man/en/chapter_4.html
    2. install pnpm https://pnpm.io/installation
    3. just setup
    4. just server
    5. open http://127.0.0.1:4000/

**Comment by igorlukanin** [comment]
Does this only happen with the `dev` image? Could you please try `latest`?

**Comment by mokeyish** [comment]
> Does this only happen with the `dev` image? Could you please try `latest`?

With the `latest` tag, `npm install @cubejs-backend/postgres-driver` is  long time no response. I also tried other npm registry mirror, the same is true.

**Comment by igorlukanin** [comment]
Hi @mokeyish 👋 

Here's what I mentioned in one of my previous messaged:

>  I did not have to install any Postgres driver though as it's bundled with Cube in its Docker container.

Here's what you responded:

> I've update the Step To Reproduce with screenshot.

However, I still don't understand what do you mean by "step 4 — Install postgres-driver" and why do you need to do that at all. After "step 3 —  Set Up a Database connection", if that is a Postgres database, you will have a working connection, no driver installation required.

I'm afraid I'll need more details from you to understand what is the issue. If you can record a video where you follow the steps that you've described, that would be helpful.
