### ISSUE TITLE
Data Modeling File Structure - Cube Cloud vs Docs

### ISSUE THREAD

**Issue by sabinevidal** [cube-js/cube#8602]
I've noticed a mismatch in how the files are structured in regards to Data modeling. In the [Data modeling documentation ](https://cube.dev/docs/product/data-modeling/syntax#folder-structure), the file structure is suggested as 
```
model
├── cubes
│   ├── orders.yml
│   ├── products.yml
│   └── users.yml
└── views
    └── revenue.yml
```
However, in Cube Cloud the file structure generated when creating a new data model using Snowflake is:
```
/ 
├── model
│   ├── orders.yml
│   ├── products.yml
│   └── users.yml
└── views
    └── revenue.yml
```
Is there a difference? And is there a preference? 
Thank you!

**Comment by igorlukanin** [comment]
Hi @sabinevidal 👋 

> However, in Cube Cloud the file structure generated when creating a new data model using Snowflake is:

Are you absolutely sure about that? I have just tried this with a fresh deployment, here's what I've got:
<img width="879" alt="Screenshot 2024-08-20 at 15 53 50" src="https://github.com/user-attachments/assets/028cd3cd-d7ac-4093-ac65-6069e23f033b">

So, as you can see, the `cubes` folder is inside the `model` folder, as it should be.

If there's no mistake here, could you please record a video that shows how you generate the data model? It would be really helpful!

**Comment by sabinevidal** [comment]
Okay, recording the video and now it's correct! I'm not sure where and how I got this altered file structure, thought it might have been related to using Snowflake. But all seems to be correct now. Thank you and apologies for that!
