### ISSUE TITLE
Examples reference removed option initApp

### ISSUE THREAD

**Issue by kd7lxl** [cube-js/cube#8640]
**Describe the bug**
I am trying to add an API endpoint based on this example: https://github.com/cube-js/cube/blob/1afa934b1db7379a87ee913816e9ce855783d2bb/examples/real-time-dashboard/cube.js#L10-L11

When run, it returns this error: `Error: Invalid cube-server-core options: "initApp" is not allowed`

**To Reproduce**
Follow the guide at https://github.com/cube-js/cube/blob/1afa934b1db7379a87ee913816e9ce855783d2bb/examples/real-time-dashboard/README.md

**Expected behavior**
Expected behavior is that the examples will run without error.

**Version:**
v0.35.76

**Comment by igorlukanin** [comment]
Hi @kd7lxl 👋 

Thanks for reporting this!

The example that you've came across was created years ago and does not represent the recommended way to use Cube anymore. I've "fixed" this by removing that example: https://github.com/cube-js/cube/commit/c9d42dac5f04bf4f5b684654a3b8499a6ced5dc6.

The obvious solution here would be to move that `app.post('/collect', ...` function to a separate Express application that would be independent from Cube.
