### ISSUE TITLE
configure a "select * from xxx" query in cube-js

### ISSUE THREAD

**Issue by fskz** [cube-js/cube#8663]
hello, how can I configure a "select * from xxx" query in cube-js? Do you have any sample references? thank you.

**Comment by igorlukanin** [comment]
Hi @fskz 👋 

I'm not sure what your question is about exactly but probably you're looking for `sql_table` and `sql` parameters in the data model: https://cube.dev/docs/reference/data-model/cube#sql_table, https://cube.dev/docs/reference/data-model/cube#sql
