### ISSUE TITLE
ERROR [cubestore::http] pid:1 Websocket error: Protocol(ResetWithoutClosingHandshake)

### ISSUE THREAD

**Issue by jlloyd-widen** [cube-js/cube#8669]
**Describe the bug**
The cubestore router and any workers will produce the follow error logs under certain conditions:
```
2023-10-07 09:06:54,513 ERROR [cubestore::cluster] pid:1 Network error: Connection closed unexpectedly. Please check your worker and meta connection environment variables.
2023-10-07 09:07:46,733 ERROR [cubestore::http] pid:1 Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-07 09:07:47,433 ERROR [cubestore::http] pid:1 Websocket error: Protocol(ResetWithoutClosingHandshake)
...
```

**To Reproduce**
1. Create an opensource deployment. I'm on AWS EKS but I think this happens on other deployment models too. My deployment is based on the [gadsme chart](https://github.com/gadsme/charts/tree/main). 1 API, 1 worker, 1 cubestore router, cubestore workers are optional, ingress enabled. I'm working with a Snowflake source but I doubt that even needs to be configured.
2. Minimal config is required. I have nothing in my `cube.js` file and only 1 cube with a single measure, and 3 dimensions. No preaggs
3. The trigger seems to be switching `devMode` from `true` to `false`. When `devMode` is enabled, everything works fine. When it's disabled the above errors begin to appear.

**Expected behavior**
Everything should work without errors in devMode

**Version:**
0.35.22

**Additional context**
Similar issues are reported in the following places:

- https://github.com/cube-js/cube/issues/6932 This one was closed, I believe, inappropriately
- https://github.com/gadsme/charts/issues/35
- https://github.com/cube-js/cube/issues/4473 I don't think this is related but the same error was mentioned in one of the comments
- https://github.com/gadsme/charts/issues/38 I suspect this may be related but nothing in the comments proves it.

**Comment by jlloyd-widen** [comment]
> How does the "switching" happen? You update the env vars and restart the whole cluster, correct?

Yes, basically. In my case, it's updating the K8s/helm `values.yaml` value for `devMode` which just injects the env var and then update the deployment.


> Also, I have to note that running Cube in a dev mode only makes sense for a single-node instance. Cube is not designed to work in a dev mode **in a cluster setting**. Why would you want to run Cube in a dev mode in your production environment?

I agree. I don't want to run dev mode in my k8s cluster but this error invalidates my deployment and therefore forces me to run in dev mode if I want anything to work.

**Comment by igorlukanin** [comment]
> When devMode is enabled, everything works fine. When it's disabled the above errors begin to appear.

> forces me to run in dev mode if I want anything to work.

I see. I have a hunch that everything work in a dev mode because Cube Store is basically [not used](https://cube.dev/docs/product/configuration#development-mode) (hard to say for sure without checking your env vars). But it sounds pretty pleasing that once you run in prod mode, then Cube Store is used—and because of some (networking?) issues in a Cube Store cluster you now see these errors from the opening message.

I would recommend to double-check the networking configuration/quality and also check the [resources](https://cube.dev/docs/product/deployment/production-checklist#appropriate-cluster-sizing) that you provisioned. Might anything be just deprived of them?

**Comment by jlloyd-widen** [comment]
@igorlukanin Good call. The resources do appear to be the problem. I upped the resources in my deployment to match the guidance you linked to and the errors appear to have disappeared. Thank you for your help!
