### ISSUE TITLE
Non-Default Server Core + Driver Exports Unavailable via ESM

### ISSUE THREAD

**Issue by joealden** [cube-js/cube#8755]
**Describe the bug**

Due to how exports are handled in https://github.com/cube-js/cube/blob/master/packages/cubejs-server-core/index.js, Node's CJS -> ESM conversion doesn't match what the TS types say are exposed.

Note that this problem does not happen for `@cubejs-backend/server`, as exports are actually defined on `module.exports` (`module.exports.x = y`) rather than `module.exports` being set to an object value `module.exports = { x: y }`.

So with this in mind, I believe Node treats `module.exports = ...` as only the default export in ESM, whereas named exports need to be defined directly on `module.exports`.

Maybe the `for of` logic will still work if done directly on the export (`module.exports[key] = module`)?

ESM import examples for `@cubejs-backend/server-core`

```js
import { CubejsServerCore } from "@cubejs-backend/server-core"
console.log(CubejsServerCore); // undefined, but TS doesn't complain

import * as Cube from "@cubejs-backend/server-core"
console.log(Cube.CubejsServerCore); // undefined, but TS doesn't complain

import CubejsServerCore from "@cubejs-backend/server-core"
console.log(CubejsServerCore); // defined as expected 
```

ESM import examples for `@cubejs-backend/server`

```js
import { CubejsServer } from "@cubejs-backend/server";
console.log(CubejsServer); // defined as expected 

import * as Cube from "@cubejs-backend/server"
console.log(Cube.CubejsServer); // defined as expected 

import CubejsServer from "@cubejs-backend/server";
console.log(CubejsServer); // defined as expected
```

Comparison of what Node sees the modules to contain (note everything getting added to `default`):

```
{
  "@cubejs-backend/server-core": [Module: null prototype] {
    default: <ref *1> [class CubejsServerCore] {
      driverDependencies: [Function: driverDependencies],
      lookupDriverClass: [Function: lookupDriverClass],
      createDriver: [Function: createDriver],
      getDriverMaxPool: [AsyncFunction: getDriverMaxPool],
      FileRepository: [class FileRepository],
      devLogger: [Function: devLogger],
      prodLogger: [Function: prodLogger],
      CubejsServerCore: [Circular *1],
      RefreshScheduler: [class RefreshScheduler],
      OrchestratorApi: [class OrchestratorApi],
      CompilerApi: [class CompilerApi],
      default: [Circular *1]
    }
  },
  "@cubejs-backend/server": [Module: null prototype] {
    CubejsServer: <ref *2> [class CubejsServer] {
      CubejsServer: [Circular *2],
      ServerContainer: [class ServerContainer],
      run: [Function: run]
    },
    ServerContainer: [class ServerContainer],
    default: <ref *2> [class CubejsServer] {
      CubejsServer: [Circular *2],
      ServerContainer: [class ServerContainer],
      run: [Function: run]
    },
    run: [Function: run]
  }
}

```

**To Reproduce**
I'm not sure I can get a good repro for this via StackBlitz - but I think the problem is self evident.

**Expected behavior**
All ways of importing `CubejsServerCore` should work the same as `CubejsServer` (and as the type suggest).

**Version:**
0.36.4

**Comment by joealden** [comment]
The problematic export pattern also appears to be used in all driver packages:

https://github.com/search?q=repo%3Acube-js%2Fcube%20toExport%5Bkey%5D%20%3D%20module%3B&type=code

**Comment by johancube** [comment]
Hi @joealden! Could you please provide your nodejs version?

**Comment by joealden** [comment]
@johancube I was originally testing this with `20.11.1`, but I can also reproduce it with `20.17.0` and `22.9.0`.

**Comment by igorlukanin** [comment]
Hi @joealden 👋 Thanks for filing this! Could you please also elaborate on your use case? I wonder why the way exports are handled is an issue for you—and how you discovered it in the first place. Would be great to dig deeper into this.

**Comment by joealden** [comment]
Hey - I guess we are still using cube in a way you aren't really supporting anymore. We are running cube directly in node via the `CubeServer` class, not via your docker image or Cube Cloud.

Can you confirm that this way of using cube isn't supported now (as I can't see that your docs mention anything about the backend packages anymore)?

**Comment by ovr** [comment]
@joealden 

> Can you confirm that this way of using a cube isn't supported now

Confirm. Embedding Cube within Express was deprecated.

https://github.com/cube-js/cube.js/blob/master/DEPRECATION.md#embedding-cubejs-within-express

I will close this issue because this API is not public anymore.
