### ISSUE TITLE
Health check should be configurable to not run against Redshift serverless datasource

### ISSUE THREAD

**Issue by GabeInDevOps** [cube-js/cube#8816]
https://github.com/cube-js/cube/blob/a8f48f289ebf11ce3b0480cf3713ba060c7e0270/packages/cubejs-redshift-driver/src/RedshiftDriver.ts#L73

The health check that is inherited from the postgres driver can cause significant costs when the target is a redshift serverless cluster. This query specifically: https://github.com/cube-js/cube/blob/a8f48f289ebf11ce3b0480cf3713ba060c7e0270/packages/cubejs-postgres-driver/src/PostgresDriver.ts#L229

Scenario: The cube container was in some sort of hung state, and ran the SELECT $1 query over 30,000 times against a redshift serverless cluster, causing over $1000 a day of RPU usage. If the query is run every 30 seconds, and only takes 1ms to complete, you still get charged for the minimum 60 seconds. If this is continued throughout a 24 hour period, you are charged for your clusters base capacity for the entire 24 hour period, even though it was only this query that was running. 

This query seems to be used to validate the connection to the datasource. It is my opinion that the connection should be validated with tcp, and the health check should either be configurable so that it can be disabled, or not run at all if the target is Redshift serverless.

**Comment by KSDaemon** [comment]
Closed via https://github.com/cube-js/cube/pull/8847

**Comment by GabeInDevOps** [comment]
Thank you @KSDaemon !

**Comment by KSDaemon** [comment]
You're welcome! Ping me if you face any problems!
