### ISSUE TITLE
Clarify "missing_partition" status

### ISSUE THREAD

**Issue by itaischwartz** [cube-js/cube#9016]
https://cube.dev/docs/reference/rest-api#v1pre-aggregationsjobs does not describe possible status values and their meaning.

What does "missing_partition" status mean?

**Comment by igorlukanin** [comment]
Hi @itaischwartz 👋 

As far as I see, this is one of the possible statuses: an erroneous one, specifically: https://github.com/cube-js/cube/blob/8f45afa28d568ad48b52b44a167f945b61a6e5eb/packages/cubejs-testing/test/rest-test-suite.ts#L209-L213

I agree this can be documented in a better way.
