### ISSUE TITLE
Fill the gaps in data for the runningTotal measure

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#958]
**Is your feature request related to a problem? Please describe.**
Please see the attached screenshot:
* the Playground with my query where I group data by weeks (on the left)
* the cube with two measures, one of them is a `runningTotal` measure (on the right)

<img width="2560" alt="Screenshot 2020-08-05 at 12 52 16 (2)" src="https://user-images.githubusercontent.com/3852894/89438311-59f87780-d751-11ea-9717-bbb805476e96.png">

I believe that one expect that the `runningTotal` measure, by the definition of the _running total_, once it becomes greater than 0, will never ever become 0 again. However, it looks like for a number of weeks this measure has no value which essentially becomes 0 on the chart. 

**Describe the solution you'd like**
I suggest that the Cube.js server might add _missing values_ for such a week by copying the value of the previous week and returning them in the result set.

**Describe alternatives you've considered**
This is solvable with post-processing on the frontend. However, it is totally and transparently doable on the backend too.

I can't think of any user scenarios which may be broken by this change. In case they exist, a special flag may be added to turn this function on/off by a developer.

Please consider implementing this request so that the `runningTotal` measures can work as one would expect. Thank you!

**Comment by paveltiunov** [comment]
This only reproduces when there's regular and rolling measures are queried together due to the flaw in generated SQL.

**Comment by igorlukanin** [comment]
Recently, we've deprecated running total measures in favor of the rolling window option: https://cube.dev/blog/cube-core-v0-33-43-duckdb-support-langchain-integration#running_total-deprecation
